//++Dubrovnik.CodeGenerator System_Runtime_InteropServices_UnmanagedType.h
//
// Managed enumeration : UnmanagedType
//
typedef NS_ENUM(int32_t, System_Runtime_InteropServices_UnmanagedType) {
	System_Runtime_InteropServices_UnmanagedType_AnsiBStr = 35,
	System_Runtime_InteropServices_UnmanagedType_AsAny = 40,
	System_Runtime_InteropServices_UnmanagedType_Bool = 2,
	System_Runtime_InteropServices_UnmanagedType_BStr = 19,
	System_Runtime_InteropServices_UnmanagedType_ByValArray = 30,
	System_Runtime_InteropServices_UnmanagedType_ByValTStr = 23,
	System_Runtime_InteropServices_UnmanagedType_Currency = 15,
	System_Runtime_InteropServices_UnmanagedType_CustomMarshaler = 44,
	System_Runtime_InteropServices_UnmanagedType_Error = 45,
	System_Runtime_InteropServices_UnmanagedType_FunctionPtr = 38,
	System_Runtime_InteropServices_UnmanagedType_HString = 47,
	System_Runtime_InteropServices_UnmanagedType_I1 = 3,
	System_Runtime_InteropServices_UnmanagedType_I2 = 5,
	System_Runtime_InteropServices_UnmanagedType_I4 = 7,
	System_Runtime_InteropServices_UnmanagedType_I8 = 9,
	System_Runtime_InteropServices_UnmanagedType_IDispatch = 26,
	System_Runtime_InteropServices_UnmanagedType_IInspectable = 46,
	System_Runtime_InteropServices_UnmanagedType_Interface = 28,
	System_Runtime_InteropServices_UnmanagedType_IUnknown = 25,
	System_Runtime_InteropServices_UnmanagedType_LPArray = 42,
	System_Runtime_InteropServices_UnmanagedType_LPStr = 20,
	System_Runtime_InteropServices_UnmanagedType_LPStruct = 43,
	System_Runtime_InteropServices_UnmanagedType_LPTStr = 22,
	System_Runtime_InteropServices_UnmanagedType_LPWStr = 21,
	System_Runtime_InteropServices_UnmanagedType_R4 = 11,
	System_Runtime_InteropServices_UnmanagedType_R8 = 12,
	System_Runtime_InteropServices_UnmanagedType_SafeArray = 29,
	System_Runtime_InteropServices_UnmanagedType_Struct = 27,
	System_Runtime_InteropServices_UnmanagedType_SysInt = 31,
	System_Runtime_InteropServices_UnmanagedType_SysUInt = 32,
	System_Runtime_InteropServices_UnmanagedType_TBStr = 36,
	System_Runtime_InteropServices_UnmanagedType_U1 = 4,
	System_Runtime_InteropServices_UnmanagedType_U2 = 6,
	System_Runtime_InteropServices_UnmanagedType_U4 = 8,
	System_Runtime_InteropServices_UnmanagedType_U8 = 10,
	System_Runtime_InteropServices_UnmanagedType_VariantBool = 37,
	System_Runtime_InteropServices_UnmanagedType_VBByRefStr = 34,
};
//--Dubrovnik.CodeGenerator