//++Dubrovnik.CodeGenerator System_Runtime_InteropServices_RegistrationClassContext.h
//
// Managed enumeration : RegistrationClassContext
//
typedef NS_ENUM(int32_t, System_Runtime_InteropServices_RegistrationClassContext) {
	System_Runtime_InteropServices_RegistrationClassContext_DisableActivateAsActivator = 32768,
	System_Runtime_InteropServices_RegistrationClassContext_EnableActivateAsActivator = 65536,
	System_Runtime_InteropServices_RegistrationClassContext_EnableCodeDownload = 8192,
	System_Runtime_InteropServices_RegistrationClassContext_FromDefaultContext = 131072,
	System_Runtime_InteropServices_RegistrationClassContext_InProcessHandler = 2,
	System_Runtime_InteropServices_RegistrationClassContext_InProcessHandler16 = 32,
	System_Runtime_InteropServices_RegistrationClassContext_InProcessServer = 1,
	System_Runtime_InteropServices_RegistrationClassContext_InProcessServer16 = 8,
	System_Runtime_InteropServices_RegistrationClassContext_LocalServer = 4,
	System_Runtime_InteropServices_RegistrationClassContext_NoCodeDownload = 1024,
	System_Runtime_InteropServices_RegistrationClassContext_NoCustomMarshal = 4096,
	System_Runtime_InteropServices_RegistrationClassContext_NoFailureLog = 16384,
	System_Runtime_InteropServices_RegistrationClassContext_RemoteServer = 16,
	System_Runtime_InteropServices_RegistrationClassContext_Reserved1 = 64,
	System_Runtime_InteropServices_RegistrationClassContext_Reserved2 = 128,
	System_Runtime_InteropServices_RegistrationClassContext_Reserved3 = 256,
	System_Runtime_InteropServices_RegistrationClassContext_Reserved4 = 512,
	System_Runtime_InteropServices_RegistrationClassContext_Reserved5 = 2048,
};
//--Dubrovnik.CodeGenerator