//++Dubrovnik.CodeGenerator System_Security_Permissions_IsolatedStorageContainment.h
//
// Managed enumeration : IsolatedStorageContainment
//
typedef NS_ENUM(int32_t, System_Security_Permissions_IsolatedStorageContainment) {
	System_Security_Permissions_IsolatedStorageContainment_AdministerIsolatedStorageByUser = 112,
	System_Security_Permissions_IsolatedStorageContainment_ApplicationIsolationByMachine = 69,
	System_Security_Permissions_IsolatedStorageContainment_ApplicationIsolationByRoamingUser = 101,
	System_Security_Permissions_IsolatedStorageContainment_ApplicationIsolationByUser = 21,
	System_Security_Permissions_IsolatedStorageContainment_AssemblyIsolationByMachine = 64,
	System_Security_Permissions_IsolatedStorageContainment_AssemblyIsolationByRoamingUser = 96,
	System_Security_Permissions_IsolatedStorageContainment_AssemblyIsolationByUser = 32,
	System_Security_Permissions_IsolatedStorageContainment_DomainIsolationByMachine = 48,
	System_Security_Permissions_IsolatedStorageContainment_DomainIsolationByRoamingUser = 80,
	System_Security_Permissions_IsolatedStorageContainment_DomainIsolationByUser = 16,
	System_Security_Permissions_IsolatedStorageContainment_None = 0,
	System_Security_Permissions_IsolatedStorageContainment_UnrestrictedIsolatedStorage = 240,
};
//--Dubrovnik.CodeGenerator