//++Dubrovnik.CodeGenerator System_Security_Principal_WellKnownSidType.h
//
// Managed enumeration : WellKnownSidType
//
typedef NS_ENUM(int32_t, System_Security_Principal_WellKnownSidType) {
	System_Security_Principal_WellKnownSidType_AccountAdministratorSid = 38,
	System_Security_Principal_WellKnownSidType_AccountCertAdminsSid = 46,
	System_Security_Principal_WellKnownSidType_AccountComputersSid = 44,
	System_Security_Principal_WellKnownSidType_AccountControllersSid = 45,
	System_Security_Principal_WellKnownSidType_AccountDomainAdminsSid = 41,
	System_Security_Principal_WellKnownSidType_AccountDomainGuestsSid = 43,
	System_Security_Principal_WellKnownSidType_AccountDomainUsersSid = 42,
	System_Security_Principal_WellKnownSidType_AccountEnterpriseAdminsSid = 48,
	System_Security_Principal_WellKnownSidType_AccountGuestSid = 39,
	System_Security_Principal_WellKnownSidType_AccountKrbtgtSid = 40,
	System_Security_Principal_WellKnownSidType_AccountPolicyAdminsSid = 49,
	System_Security_Principal_WellKnownSidType_AccountRasAndIasServersSid = 50,
	System_Security_Principal_WellKnownSidType_AccountSchemaAdminsSid = 47,
	System_Security_Principal_WellKnownSidType_AnonymousSid = 13,
	System_Security_Principal_WellKnownSidType_AuthenticatedUserSid = 17,
	System_Security_Principal_WellKnownSidType_BatchSid = 10,
	System_Security_Principal_WellKnownSidType_BuiltinAccountOperatorsSid = 30,
	System_Security_Principal_WellKnownSidType_BuiltinAdministratorsSid = 26,
	System_Security_Principal_WellKnownSidType_BuiltinAuthorizationAccessSid = 59,
	System_Security_Principal_WellKnownSidType_BuiltinBackupOperatorsSid = 33,
	System_Security_Principal_WellKnownSidType_BuiltinDomainSid = 25,
	System_Security_Principal_WellKnownSidType_BuiltinGuestsSid = 28,
	System_Security_Principal_WellKnownSidType_BuiltinIncomingForestTrustBuildersSid = 56,
	System_Security_Principal_WellKnownSidType_BuiltinNetworkConfigurationOperatorsSid = 37,
	System_Security_Principal_WellKnownSidType_BuiltinPerformanceLoggingUsersSid = 58,
	System_Security_Principal_WellKnownSidType_BuiltinPerformanceMonitoringUsersSid = 57,
	System_Security_Principal_WellKnownSidType_BuiltinPowerUsersSid = 29,
	System_Security_Principal_WellKnownSidType_BuiltinPreWindows2000CompatibleAccessSid = 35,
	System_Security_Principal_WellKnownSidType_BuiltinPrintOperatorsSid = 32,
	System_Security_Principal_WellKnownSidType_BuiltinRemoteDesktopUsersSid = 36,
	System_Security_Principal_WellKnownSidType_BuiltinReplicatorSid = 34,
	System_Security_Principal_WellKnownSidType_BuiltinSystemOperatorsSid = 31,
	System_Security_Principal_WellKnownSidType_BuiltinUsersSid = 27,
	System_Security_Principal_WellKnownSidType_CreatorGroupServerSid = 6,
	System_Security_Principal_WellKnownSidType_CreatorGroupSid = 4,
	System_Security_Principal_WellKnownSidType_CreatorOwnerServerSid = 5,
	System_Security_Principal_WellKnownSidType_CreatorOwnerSid = 3,
	System_Security_Principal_WellKnownSidType_DialupSid = 8,
	System_Security_Principal_WellKnownSidType_DigestAuthenticationSid = 52,
	System_Security_Principal_WellKnownSidType_EnterpriseControllersSid = 15,
	System_Security_Principal_WellKnownSidType_InteractiveSid = 11,
	System_Security_Principal_WellKnownSidType_LocalServiceSid = 23,
	System_Security_Principal_WellKnownSidType_LocalSid = 2,
	System_Security_Principal_WellKnownSidType_LocalSystemSid = 22,
	System_Security_Principal_WellKnownSidType_LogonIdsSid = 21,
	System_Security_Principal_WellKnownSidType_MaxDefined = 60,
	System_Security_Principal_WellKnownSidType_NetworkServiceSid = 24,
	System_Security_Principal_WellKnownSidType_NetworkSid = 9,
	System_Security_Principal_WellKnownSidType_NTAuthoritySid = 7,
	System_Security_Principal_WellKnownSidType_NtlmAuthenticationSid = 51,
	System_Security_Principal_WellKnownSidType_NullSid = 0,
	System_Security_Principal_WellKnownSidType_OtherOrganizationSid = 55,
	System_Security_Principal_WellKnownSidType_ProxySid = 14,
	System_Security_Principal_WellKnownSidType_RemoteLogonIdSid = 20,
	System_Security_Principal_WellKnownSidType_RestrictedCodeSid = 18,
	System_Security_Principal_WellKnownSidType_SChannelAuthenticationSid = 53,
	System_Security_Principal_WellKnownSidType_SelfSid = 16,
	System_Security_Principal_WellKnownSidType_ServiceSid = 12,
	System_Security_Principal_WellKnownSidType_TerminalServerSid = 19,
	System_Security_Principal_WellKnownSidType_ThisOrganizationSid = 54,
	System_Security_Principal_WellKnownSidType_WinBuiltinTerminalServerLicenseServersSid = 60,
	System_Security_Principal_WellKnownSidType_WorldSid = 1,
};
//--Dubrovnik.CodeGenerator