//++Dubrovnik.CodeGenerator System.Environment_SpecialFolder.h
//
// Managed enumeration : Environment.SpecialFolder
//
typedef NS_ENUM(int32_t, System_Environment__SpecialFolder) {
	System_Environment__SpecialFolder_AdminTools = 48,
	System_Environment__SpecialFolder_ApplicationData = 26,
	System_Environment__SpecialFolder_CDBurning = 59,
	System_Environment__SpecialFolder_CommonAdminTools = 47,
	System_Environment__SpecialFolder_CommonApplicationData = 35,
	System_Environment__SpecialFolder_CommonDesktopDirectory = 25,
	System_Environment__SpecialFolder_CommonDocuments = 46,
	System_Environment__SpecialFolder_CommonMusic = 53,
	System_Environment__SpecialFolder_CommonOemLinks = 58,
	System_Environment__SpecialFolder_CommonPictures = 54,
	System_Environment__SpecialFolder_CommonProgramFiles = 43,
	System_Environment__SpecialFolder_CommonProgramFilesX86 = 44,
	System_Environment__SpecialFolder_CommonPrograms = 23,
	System_Environment__SpecialFolder_CommonStartMenu = 22,
	System_Environment__SpecialFolder_CommonStartup = 24,
	System_Environment__SpecialFolder_CommonTemplates = 45,
	System_Environment__SpecialFolder_CommonVideos = 55,
	System_Environment__SpecialFolder_Cookies = 33,
	System_Environment__SpecialFolder_Desktop = 0,
	System_Environment__SpecialFolder_DesktopDirectory = 16,
	System_Environment__SpecialFolder_Favorites = 6,
	System_Environment__SpecialFolder_Fonts = 20,
	System_Environment__SpecialFolder_History = 34,
	System_Environment__SpecialFolder_InternetCache = 32,
	System_Environment__SpecialFolder_LocalApplicationData = 28,
	System_Environment__SpecialFolder_LocalizedResources = 57,
	System_Environment__SpecialFolder_MyComputer = 17,
	System_Environment__SpecialFolder_MyDocuments = 5,
	System_Environment__SpecialFolder_MyMusic = 13,
	System_Environment__SpecialFolder_MyPictures = 39,
	System_Environment__SpecialFolder_MyVideos = 14,
	System_Environment__SpecialFolder_NetworkShortcuts = 19,
	System_Environment__SpecialFolder_Personal = 5,
	System_Environment__SpecialFolder_PrinterShortcuts = 27,
	System_Environment__SpecialFolder_ProgramFiles = 38,
	System_Environment__SpecialFolder_ProgramFilesX86 = 42,
	System_Environment__SpecialFolder_Programs = 2,
	System_Environment__SpecialFolder_Recent = 8,
	System_Environment__SpecialFolder_Resources = 56,
	System_Environment__SpecialFolder_SendTo = 9,
	System_Environment__SpecialFolder_StartMenu = 11,
	System_Environment__SpecialFolder_Startup = 7,
	System_Environment__SpecialFolder_System = 37,
	System_Environment__SpecialFolder_SystemX86 = 41,
	System_Environment__SpecialFolder_Templates = 21,
	System_Environment__SpecialFolder_UserProfile = 40,
	System_Environment__SpecialFolder_Windows = 36,
};
//--Dubrovnik.CodeGenerator