//------------------------------------------------------------------------------
// <auto-generated tool="Dubrovnik.CodeGenerator">
//
// DBCocoaExample.m
//
// Dubrovnik based OS X Cocoa Objective-C to Mono bindings.
//
// This code was generated using a tool available as part of:
// http://github.com/ThesaurusSoftware/Dubrovnik
// This code has dependencies on the above project.
//
// Date:     18/06/2018 17:46:26
//
// Assembly: DBCocoaExample
// Fullname: DBCocoaExample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Path:     C:\Users\Jonathan\Documents\Dubrovnik\Framework\examples\DBCocoaExample\DBCocoaExample\DBCocoaExample\bin\Debug\DBCocoaExample.dll
//
// Platform: Microsoft Windows NT 6.2.9200.0
// OS Arch:  64 bit
// Process:  32 bit
// Target:   mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Runtime:  4.0.30319.42000
//
// Asm Ref:  mscorlib
// Fullname: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Asm Ref:  System
// Fullname: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
#import "DBCocoaExample.h"

// ARC is required
#if  ! __has_feature(objc_arc)
#error This file requires ARC. 
#endif


/*

Assembly type imports

*/
// Dubrovnik.CodeGenerator made DBCocoaExample_CurrencyConverter.m
// Dubrovnik.CodeGenerator made Dubrovnik_ClientApplication_EventHelper.m
// Dubrovnik.CodeGenerator made Dubrovnik_ClientApplication_IEventHelper.m
