//------------------------------------------------------------------------------
// <auto-generated tool="Dubrovnik.CodeGenerator">
//
// DBCocoaExample.h
//
// Dubrovnik based OS X Cocoa Objective-C to Mono bindings.
//
// This code was generated using a tool available as part of:
// http://github.com/ThesaurusSoftware/Dubrovnik
// This code has dependencies on the above project.
//
// Date:     12/2/2014 4:44:20 PM
//
// Assembly: DBCocoaExample
// Fullname: DBCocoaExample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Path:     C:\Users\jonathan\Documents\Thesaurus\Development\Dubrovnik\Framework\examples\DBCocoaExample\DBCocoaExample\DBCocoaExample\bin\Debug\DBCocoaExample.dll
//
// Platform: Microsoft Windows NT 6.1.7601 Service Pack 1
// OS Arch:  64 bit
// Process:  32 bit
// Target:   mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Runtime:  4.0.30319.18444
//
// Asm Ref:  mscorlib
// Fullname: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Asm Ref:  System
// Fullname: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
#import <Cocoa/Cocoa.h>
#import <Dubrovnik/Dubrovnik.h>

//
// Extra include
//
#ifdef INCLUDE_DBCOCOAEXAMPLE_EXTRA
#import "DBCocoaExample.__Extra__.h"	// Not auto generated. Add manually to project.
#endif


//
// Referenced assemblies
//
#ifndef MSCORLIB_INCLUDED
//#import "mscorlib.h"
#endif

#ifndef SYSTEM_INCLUDED
//#import "System.h"
#endif


//
// Forward class declarations and class aliases
//
@class DBCocoaExample_CurrencyConverter;
#ifdef DCurrencyConverter_
#warning DCurrencyConverter_ class name collision.
#else
#define DCurrencyConverter_ DBCocoaExample_CurrencyConverter
#endif


/*

Order here is Enumerations, Interface protocols, Structs, Classes, Explicit interface classes

*/

#import "DBCocoaExample_CurrencyConverter.h"
