//++Dubrovnik.CodeGenerator System_Net_FtpStatusCode.h
//
// Managed enumeration : FtpStatusCode
//
typedef NS_ENUM(int32_t, System_Net_FtpStatusCode) {
	System_Net_FtpStatusCode_AccountNeeded = 532,
	System_Net_FtpStatusCode_ActionAbortedLocalProcessingError = 451,
	System_Net_FtpStatusCode_ActionAbortedUnknownPageType = 551,
	System_Net_FtpStatusCode_ActionNotTakenFilenameNotAllowed = 553,
	System_Net_FtpStatusCode_ActionNotTakenFileUnavailable = 550,
	System_Net_FtpStatusCode_ActionNotTakenFileUnavailableOrBusy = 450,
	System_Net_FtpStatusCode_ActionNotTakenInsufficientSpace = 452,
	System_Net_FtpStatusCode_ArgumentSyntaxError = 501,
	System_Net_FtpStatusCode_BadCommandSequence = 503,
	System_Net_FtpStatusCode_CantOpenData = 425,
	System_Net_FtpStatusCode_ClosingControl = 221,
	System_Net_FtpStatusCode_ClosingData = 226,
	System_Net_FtpStatusCode_CommandExtraneous = 202,
	System_Net_FtpStatusCode_CommandNotImplemented = 502,
	System_Net_FtpStatusCode_CommandOK = 200,
	System_Net_FtpStatusCode_CommandSyntaxError = 500,
	System_Net_FtpStatusCode_ConnectionClosed = 426,
	System_Net_FtpStatusCode_DataAlreadyOpen = 125,
	System_Net_FtpStatusCode_DirectoryStatus = 212,
	System_Net_FtpStatusCode_EnteringPassive = 227,
	System_Net_FtpStatusCode_FileActionAborted = 552,
	System_Net_FtpStatusCode_FileActionOK = 250,
	System_Net_FtpStatusCode_FileCommandPending = 350,
	System_Net_FtpStatusCode_FileStatus = 213,
	System_Net_FtpStatusCode_LoggedInProceed = 230,
	System_Net_FtpStatusCode_NeedLoginAccount = 332,
	System_Net_FtpStatusCode_NotLoggedIn = 530,
	System_Net_FtpStatusCode_OpeningData = 150,
	System_Net_FtpStatusCode_PathnameCreated = 257,
	System_Net_FtpStatusCode_RestartMarker = 110,
	System_Net_FtpStatusCode_SendPasswordCommand = 331,
	System_Net_FtpStatusCode_SendUserCommand = 220,
	System_Net_FtpStatusCode_ServerWantsSecureSession = 234,
	System_Net_FtpStatusCode_ServiceNotAvailable = 421,
	System_Net_FtpStatusCode_ServiceTemporarilyNotAvailable = 120,
	System_Net_FtpStatusCode_SystemType = 215,
	System_Net_FtpStatusCode_Undefined = 0,
};
//--Dubrovnik.CodeGenerator