//++Dubrovnik.CodeGenerator System_Security_Cryptography_X509Certificates_X509SubjectKeyIdentifierHashAlgorithm.h
//
// Managed enumeration : X509SubjectKeyIdentifierHashAlgorithm
//
typedef NS_ENUM(int32_t, System_Security_Cryptography_X509Certificates_X509SubjectKeyIdentifierHashAlgorithm) {
	System_Security_Cryptography_X509Certificates_X509SubjectKeyIdentifierHashAlgorithm_CapiSha1 = 2,
	System_Security_Cryptography_X509Certificates_X509SubjectKeyIdentifierHashAlgorithm_Sha1 = 0,
	System_Security_Cryptography_X509Certificates_X509SubjectKeyIdentifierHashAlgorithm_ShortSha1 = 1,
};
//--Dubrovnik.CodeGenerator