//++Dubrovnik.CodeGenerator System_Net_HttpRequestHeader.h
//
// Managed enumeration : HttpRequestHeader
//
typedef NS_ENUM(int32_t, System_Net_HttpRequestHeader) {
	System_Net_HttpRequestHeader_Accept = 20,
	System_Net_HttpRequestHeader_AcceptCharset = 21,
	System_Net_HttpRequestHeader_AcceptEncoding = 22,
	System_Net_HttpRequestHeader_AcceptLanguage = 23,
	System_Net_HttpRequestHeader_Allow = 10,
	System_Net_HttpRequestHeader_Authorization = 24,
	System_Net_HttpRequestHeader_CacheControl = 0,
	System_Net_HttpRequestHeader_Connection = 1,
	System_Net_HttpRequestHeader_ContentEncoding = 13,
	System_Net_HttpRequestHeader_ContentLanguage = 14,
	System_Net_HttpRequestHeader_ContentLength = 11,
	System_Net_HttpRequestHeader_ContentLocation = 15,
	System_Net_HttpRequestHeader_ContentMd5 = 16,
	System_Net_HttpRequestHeader_ContentRange = 17,
	System_Net_HttpRequestHeader_ContentType = 12,
	System_Net_HttpRequestHeader_Cookie = 25,
	System_Net_HttpRequestHeader_Date = 2,
	System_Net_HttpRequestHeader_Expect = 26,
	System_Net_HttpRequestHeader_Expires = 18,
	System_Net_HttpRequestHeader_From = 27,
	System_Net_HttpRequestHeader_Host = 28,
	System_Net_HttpRequestHeader_IfMatch = 29,
	System_Net_HttpRequestHeader_IfModifiedSince = 30,
	System_Net_HttpRequestHeader_IfNoneMatch = 31,
	System_Net_HttpRequestHeader_IfRange = 32,
	System_Net_HttpRequestHeader_IfUnmodifiedSince = 33,
	System_Net_HttpRequestHeader_KeepAlive = 3,
	System_Net_HttpRequestHeader_LastModified = 19,
	System_Net_HttpRequestHeader_MaxForwards = 34,
	System_Net_HttpRequestHeader_Pragma = 4,
	System_Net_HttpRequestHeader_ProxyAuthorization = 35,
	System_Net_HttpRequestHeader_Range = 37,
	System_Net_HttpRequestHeader_Referer = 36,
	System_Net_HttpRequestHeader_Te = 38,
	System_Net_HttpRequestHeader_Trailer = 5,
	System_Net_HttpRequestHeader_TransferEncoding = 6,
	System_Net_HttpRequestHeader_Translate = 39,
	System_Net_HttpRequestHeader_Upgrade = 7,
	System_Net_HttpRequestHeader_UserAgent = 40,
	System_Net_HttpRequestHeader_Via = 8,
	System_Net_HttpRequestHeader_Warning = 9,
};
//--Dubrovnik.CodeGenerator