//++Dubrovnik.CodeGenerator System_Net_Sockets_SocketError.h
//
// Managed enumeration : SocketError
//
typedef NS_ENUM(int32_t, System_Net_Sockets_SocketError) {
	System_Net_Sockets_SocketError_AccessDenied = 10013,
	System_Net_Sockets_SocketError_AddressAlreadyInUse = 10048,
	System_Net_Sockets_SocketError_AddressFamilyNotSupported = 10047,
	System_Net_Sockets_SocketError_AddressNotAvailable = 10049,
	System_Net_Sockets_SocketError_AlreadyInProgress = 10037,
	System_Net_Sockets_SocketError_ConnectionAborted = 10053,
	System_Net_Sockets_SocketError_ConnectionRefused = 10061,
	System_Net_Sockets_SocketError_ConnectionReset = 10054,
	System_Net_Sockets_SocketError_DestinationAddressRequired = 10039,
	System_Net_Sockets_SocketError_Disconnecting = 10101,
	System_Net_Sockets_SocketError_Fault = 10014,
	System_Net_Sockets_SocketError_HostDown = 10064,
	System_Net_Sockets_SocketError_HostNotFound = 11001,
	System_Net_Sockets_SocketError_HostUnreachable = 10065,
	System_Net_Sockets_SocketError_InProgress = 10036,
	System_Net_Sockets_SocketError_Interrupted = 10004,
	System_Net_Sockets_SocketError_InvalidArgument = 10022,
	System_Net_Sockets_SocketError_IOPending = 997,
	System_Net_Sockets_SocketError_IsConnected = 10056,
	System_Net_Sockets_SocketError_MessageSize = 10040,
	System_Net_Sockets_SocketError_NetworkDown = 10050,
	System_Net_Sockets_SocketError_NetworkReset = 10052,
	System_Net_Sockets_SocketError_NetworkUnreachable = 10051,
	System_Net_Sockets_SocketError_NoBufferSpaceAvailable = 10055,
	System_Net_Sockets_SocketError_NoData = 11004,
	System_Net_Sockets_SocketError_NoRecovery = 11003,
	System_Net_Sockets_SocketError_NotConnected = 10057,
	System_Net_Sockets_SocketError_NotInitialized = 10093,
	System_Net_Sockets_SocketError_NotSocket = 10038,
	System_Net_Sockets_SocketError_OperationAborted = 995,
	System_Net_Sockets_SocketError_OperationNotSupported = 10045,
	System_Net_Sockets_SocketError_ProcessLimit = 10067,
	System_Net_Sockets_SocketError_ProtocolFamilyNotSupported = 10046,
	System_Net_Sockets_SocketError_ProtocolNotSupported = 10043,
	System_Net_Sockets_SocketError_ProtocolOption = 10042,
	System_Net_Sockets_SocketError_ProtocolType = 10041,
	System_Net_Sockets_SocketError_Shutdown = 10058,
	System_Net_Sockets_SocketError_SocketError = -1,
	System_Net_Sockets_SocketError_SocketNotSupported = 10044,
	System_Net_Sockets_SocketError_Success = 0,
	System_Net_Sockets_SocketError_SystemNotReady = 10091,
	System_Net_Sockets_SocketError_TimedOut = 10060,
	System_Net_Sockets_SocketError_TooManyOpenSockets = 10024,
	System_Net_Sockets_SocketError_TryAgain = 11002,
	System_Net_Sockets_SocketError_TypeNotFound = 10109,
	System_Net_Sockets_SocketError_VersionNotSupported = 10092,
	System_Net_Sockets_SocketError_WouldBlock = 10035,
};
//--Dubrovnik.CodeGenerator