//++Dubrovnik.CodeGenerator System_Net_Sockets_SocketOptionName.h
//
// Managed enumeration : SocketOptionName
//
typedef NS_ENUM(int32_t, System_Net_Sockets_SocketOptionName) {
	System_Net_Sockets_SocketOptionName_AcceptConnection = 2,
	System_Net_Sockets_SocketOptionName_AddMembership = 12,
	System_Net_Sockets_SocketOptionName_AddSourceMembership = 15,
	System_Net_Sockets_SocketOptionName_BlockSource = 17,
	System_Net_Sockets_SocketOptionName_Broadcast = 32,
	System_Net_Sockets_SocketOptionName_BsdUrgent = 2,
	System_Net_Sockets_SocketOptionName_ChecksumCoverage = 20,
	System_Net_Sockets_SocketOptionName_Debug = 1,
	System_Net_Sockets_SocketOptionName_DontFragment = 14,
	System_Net_Sockets_SocketOptionName_DontLinger = -129,
	System_Net_Sockets_SocketOptionName_DontRoute = 16,
	System_Net_Sockets_SocketOptionName_DropMembership = 13,
	System_Net_Sockets_SocketOptionName_DropSourceMembership = 16,
	System_Net_Sockets_SocketOptionName_Error = 4103,
	System_Net_Sockets_SocketOptionName_ExclusiveAddressUse = -5,
	System_Net_Sockets_SocketOptionName_Expedited = 2,
	System_Net_Sockets_SocketOptionName_HeaderIncluded = 2,
	System_Net_Sockets_SocketOptionName_HopLimit = 21,
	System_Net_Sockets_SocketOptionName_IPOptions = 1,
	System_Net_Sockets_SocketOptionName_IPProtectionLevel = 23,
	System_Net_Sockets_SocketOptionName_IpTimeToLive = 4,
	System_Net_Sockets_SocketOptionName_IPv6Only = 27,
	System_Net_Sockets_SocketOptionName_KeepAlive = 8,
	System_Net_Sockets_SocketOptionName_Linger = 128,
	System_Net_Sockets_SocketOptionName_MaxConnections = 2147483647,
	System_Net_Sockets_SocketOptionName_MulticastInterface = 9,
	System_Net_Sockets_SocketOptionName_MulticastLoopback = 11,
	System_Net_Sockets_SocketOptionName_MulticastTimeToLive = 10,
	System_Net_Sockets_SocketOptionName_NoChecksum = 1,
	System_Net_Sockets_SocketOptionName_NoDelay = 1,
	System_Net_Sockets_SocketOptionName_OutOfBandInline = 256,
	System_Net_Sockets_SocketOptionName_PacketInformation = 19,
	System_Net_Sockets_SocketOptionName_ReceiveBuffer = 4098,
	System_Net_Sockets_SocketOptionName_ReceiveLowWater = 4100,
	System_Net_Sockets_SocketOptionName_ReceiveTimeout = 4102,
	System_Net_Sockets_SocketOptionName_ReuseAddress = 4,
	System_Net_Sockets_SocketOptionName_ReuseUnicastPort = 12295,
	System_Net_Sockets_SocketOptionName_SendBuffer = 4097,
	System_Net_Sockets_SocketOptionName_SendLowWater = 4099,
	System_Net_Sockets_SocketOptionName_SendTimeout = 4101,
	System_Net_Sockets_SocketOptionName_Type = 4104,
	System_Net_Sockets_SocketOptionName_TypeOfService = 3,
	System_Net_Sockets_SocketOptionName_UnblockSource = 18,
	System_Net_Sockets_SocketOptionName_UpdateAcceptContext = 28683,
	System_Net_Sockets_SocketOptionName_UpdateConnectContext = 28688,
	System_Net_Sockets_SocketOptionName_UseLoopback = 64,
};
//--Dubrovnik.CodeGenerator