//++Dubrovnik.CodeGenerator System_Security_Cryptography_X509Certificates_X509FindType.h
//
// Managed enumeration : X509FindType
//
typedef NS_ENUM(int32_t, System_Security_Cryptography_X509Certificates_X509FindType) {
	System_Security_Cryptography_X509Certificates_X509FindType_FindByApplicationPolicy = 10,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByCertificatePolicy = 11,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByExtension = 12,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByIssuerDistinguishedName = 4,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByIssuerName = 3,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByKeyUsage = 13,
	System_Security_Cryptography_X509Certificates_X509FindType_FindBySerialNumber = 5,
	System_Security_Cryptography_X509Certificates_X509FindType_FindBySubjectDistinguishedName = 2,
	System_Security_Cryptography_X509Certificates_X509FindType_FindBySubjectKeyIdentifier = 14,
	System_Security_Cryptography_X509Certificates_X509FindType_FindBySubjectName = 1,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByTemplateName = 9,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByThumbprint = 0,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByTimeExpired = 8,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByTimeNotYetValid = 7,
	System_Security_Cryptography_X509Certificates_X509FindType_FindByTimeValid = 6,
};
//--Dubrovnik.CodeGenerator