//++Dubrovnik.CodeGenerator System_Net_HttpStatusCode.h
//
// Managed enumeration : HttpStatusCode
//
typedef NS_ENUM(int32_t, System_Net_HttpStatusCode) {
	System_Net_HttpStatusCode_Accepted = 202,
	System_Net_HttpStatusCode_Ambiguous = 300,
	System_Net_HttpStatusCode_BadGateway = 502,
	System_Net_HttpStatusCode_BadRequest = 400,
	System_Net_HttpStatusCode_Conflict = 409,
	System_Net_HttpStatusCode_Continue = 100,
	System_Net_HttpStatusCode_Created = 201,
	System_Net_HttpStatusCode_ExpectationFailed = 417,
	System_Net_HttpStatusCode_Forbidden = 403,
	System_Net_HttpStatusCode_Found = 302,
	System_Net_HttpStatusCode_GatewayTimeout = 504,
	System_Net_HttpStatusCode_Gone = 410,
	System_Net_HttpStatusCode_HttpVersionNotSupported = 505,
	System_Net_HttpStatusCode_InternalServerError = 500,
	System_Net_HttpStatusCode_LengthRequired = 411,
	System_Net_HttpStatusCode_MethodNotAllowed = 405,
	System_Net_HttpStatusCode_Moved = 301,
	System_Net_HttpStatusCode_MovedPermanently = 301,
	System_Net_HttpStatusCode_MultipleChoices = 300,
	System_Net_HttpStatusCode_NoContent = 204,
	System_Net_HttpStatusCode_NonAuthoritativeInformation = 203,
	System_Net_HttpStatusCode_NotAcceptable = 406,
	System_Net_HttpStatusCode_NotFound = 404,
	System_Net_HttpStatusCode_NotImplemented = 501,
	System_Net_HttpStatusCode_NotModified = 304,
	System_Net_HttpStatusCode_OK = 200,
	System_Net_HttpStatusCode_PartialContent = 206,
	System_Net_HttpStatusCode_PaymentRequired = 402,
	System_Net_HttpStatusCode_PreconditionFailed = 412,
	System_Net_HttpStatusCode_ProxyAuthenticationRequired = 407,
	System_Net_HttpStatusCode_Redirect = 302,
	System_Net_HttpStatusCode_RedirectKeepVerb = 307,
	System_Net_HttpStatusCode_RedirectMethod = 303,
	System_Net_HttpStatusCode_RequestedRangeNotSatisfiable = 416,
	System_Net_HttpStatusCode_RequestEntityTooLarge = 413,
	System_Net_HttpStatusCode_RequestTimeout = 408,
	System_Net_HttpStatusCode_RequestUriTooLong = 414,
	System_Net_HttpStatusCode_ResetContent = 205,
	System_Net_HttpStatusCode_SeeOther = 303,
	System_Net_HttpStatusCode_ServiceUnavailable = 503,
	System_Net_HttpStatusCode_SwitchingProtocols = 101,
	System_Net_HttpStatusCode_TemporaryRedirect = 307,
	System_Net_HttpStatusCode_Unauthorized = 401,
	System_Net_HttpStatusCode_UnsupportedMediaType = 415,
	System_Net_HttpStatusCode_Unused = 306,
	System_Net_HttpStatusCode_UpgradeRequired = 426,
	System_Net_HttpStatusCode_UseProxy = 305,
};
//--Dubrovnik.CodeGenerator