//++Dubrovnik.CodeGenerator System_Security_Cryptography_X509Certificates_X509VerificationFlags.h
//
// Managed enumeration : X509VerificationFlags
//
typedef NS_ENUM(int32_t, System_Security_Cryptography_X509Certificates_X509VerificationFlags) {
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_AllFlags = 4095,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_AllowUnknownCertificateAuthority = 16,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreCertificateAuthorityRevocationUnknown = 1024,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreCtlNotTimeValid = 2,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreCtlSignerRevocationUnknown = 512,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreEndRevocationUnknown = 256,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreInvalidBasicConstraints = 8,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreInvalidName = 64,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreInvalidPolicy = 128,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreNotTimeNested = 4,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreNotTimeValid = 1,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreRootRevocationUnknown = 2048,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_IgnoreWrongUsage = 32,
	System_Security_Cryptography_X509Certificates_X509VerificationFlags_NoFlag = 0,
};
//--Dubrovnik.CodeGenerator