//------------------------------------------------------------------------------
// <auto-generated tool="Dubrovnik.CodeGenerator">
//
// System_Core.h
//
// Dubrovnik based OS X Cocoa Objective-C to Mono bindings.
//
// This code was generated using a tool available as part of:
// http://github.com/ThesaurusSoftware/Dubrovnik
// This code has dependencies on the above project.
//
// Date:     20/09/2017 11:09:39
//
// Assembly: System.Core
// Fullname: System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Path:     C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Core.dll
//
// Platform: Microsoft Windows NT 6.2.9200.0
// OS Arch:  64 bit
// Process:  32 bit
// Target:   mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Runtime:  4.0.30319.42000
//
// Asm Ref:  mscorlib
// Fullname: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Asm Ref:  System
// Fullname: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Asm Ref:  System.Xml
// Fullname: System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Asm Ref:  System.Numerics
// Fullname: System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Asm Ref:  System.Security
// Fullname: System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
#import <Cocoa/Cocoa.h>
#import <Dubrovnik/Dubrovnik.h>

//
// Extra include
//
#if __has_include("System_Core.__Extra__.h")
#import "System_Core.__Extra__.h"	// Not auto generated. Add manually to project.
#endif


//
// Referenced assemblies
//
#ifndef MSCORLIB_INCLUDED
//#import "mscorlib.h"
#endif

#ifndef SYSTEM_INCLUDED
//#import "System.h"
#endif

#ifndef SYSTEM_XML_INCLUDED
//#import "System.Xml.h"
#endif

#ifndef SYSTEM_NUMERICS_INCLUDED
//#import "System.Numerics.h"
#endif

#ifndef SYSTEM_SECURITY_INCLUDED
//#import "System.Security.h"
#endif


//
// Forward class declarations and class aliases
//
@class Microsoft_Win32_SafeHandles_SafeMemoryMappedFileHandle;
#ifdef MWSSafeMemoryMappedFileHandle_
#warning MWSSafeMemoryMappedFileHandle_ class name collision.
#else
#define MWSSafeMemoryMappedFileHandle_ Microsoft_Win32_SafeHandles_SafeMemoryMappedFileHandle
#endif

@class Microsoft_Win32_SafeHandles_SafeMemoryMappedViewHandle;
#ifdef MWSSafeMemoryMappedViewHandle_
#warning MWSSafeMemoryMappedViewHandle_ class name collision.
#else
#define MWSSafeMemoryMappedViewHandle_ Microsoft_Win32_SafeHandles_SafeMemoryMappedViewHandle
#endif

@class Microsoft_Win32_SafeHandles_SafeNCryptHandle;
#ifdef MWSSafeNCryptHandle_
#warning MWSSafeNCryptHandle_ class name collision.
#else
#define MWSSafeNCryptHandle_ Microsoft_Win32_SafeHandles_SafeNCryptHandle
#endif

@class Microsoft_Win32_SafeHandles_SafeNCryptKeyHandle;
#ifdef MWSSafeNCryptKeyHandle_
#warning MWSSafeNCryptKeyHandle_ class name collision.
#else
#define MWSSafeNCryptKeyHandle_ Microsoft_Win32_SafeHandles_SafeNCryptKeyHandle
#endif

@class Microsoft_Win32_SafeHandles_SafeNCryptProviderHandle;
#ifdef MWSSafeNCryptProviderHandle_
#warning MWSSafeNCryptProviderHandle_ class name collision.
#else
#define MWSSafeNCryptProviderHandle_ Microsoft_Win32_SafeHandles_SafeNCryptProviderHandle
#endif

@class Microsoft_Win32_SafeHandles_SafeNCryptSecretHandle;
#ifdef MWSSafeNCryptSecretHandle_
#warning MWSSafeNCryptSecretHandle_ class name collision.
#else
#define MWSSafeNCryptSecretHandle_ Microsoft_Win32_SafeHandles_SafeNCryptSecretHandle
#endif

@class Microsoft_Win32_SafeHandles_SafePipeHandle;
#ifdef MWSSafePipeHandle_
#warning MWSSafePipeHandle_ class name collision.
#else
#define MWSSafePipeHandle_ Microsoft_Win32_SafeHandles_SafePipeHandle
#endif

@class System_ActionA10;
#ifdef SActionA10_
#warning SActionA10_ class name collision.
#else
#define SActionA10_ System_ActionA10
#endif

@class System_ActionA11;
#ifdef SActionA11_
#warning SActionA11_ class name collision.
#else
#define SActionA11_ System_ActionA11
#endif

@class System_ActionA12;
#ifdef SActionA12_
#warning SActionA12_ class name collision.
#else
#define SActionA12_ System_ActionA12
#endif

@class System_ActionA13;
#ifdef SActionA13_
#warning SActionA13_ class name collision.
#else
#define SActionA13_ System_ActionA13
#endif

@class System_ActionA14;
#ifdef SActionA14_
#warning SActionA14_ class name collision.
#else
#define SActionA14_ System_ActionA14
#endif

@class System_ActionA15;
#ifdef SActionA15_
#warning SActionA15_ class name collision.
#else
#define SActionA15_ System_ActionA15
#endif

@class System_ActionA16;
#ifdef SActionA16_
#warning SActionA16_ class name collision.
#else
#define SActionA16_ System_ActionA16
#endif

@class System_ActionA9;
#ifdef SActionA9_
#warning SActionA9_ class name collision.
#else
#define SActionA9_ System_ActionA9
#endif

@class System_FuncA10;
#ifdef SFuncA10_
#warning SFuncA10_ class name collision.
#else
#define SFuncA10_ System_FuncA10
#endif

@class System_FuncA11;
#ifdef SFuncA11_
#warning SFuncA11_ class name collision.
#else
#define SFuncA11_ System_FuncA11
#endif

@class System_FuncA12;
#ifdef SFuncA12_
#warning SFuncA12_ class name collision.
#else
#define SFuncA12_ System_FuncA12
#endif

@class System_FuncA13;
#ifdef SFuncA13_
#warning SFuncA13_ class name collision.
#else
#define SFuncA13_ System_FuncA13
#endif

@class System_FuncA14;
#ifdef SFuncA14_
#warning SFuncA14_ class name collision.
#else
#define SFuncA14_ System_FuncA14
#endif

@class System_FuncA15;
#ifdef SFuncA15_
#warning SFuncA15_ class name collision.
#else
#define SFuncA15_ System_FuncA15
#endif

@class System_FuncA16;
#ifdef SFuncA16_
#warning SFuncA16_ class name collision.
#else
#define SFuncA16_ System_FuncA16
#endif

@class System_FuncA17;
#ifdef SFuncA17_
#warning SFuncA17_ class name collision.
#else
#define SFuncA17_ System_FuncA17
#endif

@class System_Collections_Generic_HashSetA1;
#ifdef SCGHashSetA1_
#warning SCGHashSetA1_ class name collision.
#else
#define SCGHashSetA1_ System_Collections_Generic_HashSetA1
#endif

@class System_Collections_Generic_HashSetA1__Enumerator;
#ifdef SCGHashSetA1_Enumerator_
#warning SCGHashSetA1_Enumerator_ class name collision.
#else
#define SCGHashSetA1_Enumerator_ System_Collections_Generic_HashSetA1__Enumerator
#endif

@class System_Diagnostics_EventSchemaTraceListener;
#ifdef SDEventSchemaTraceListener_
#warning SDEventSchemaTraceListener_ class name collision.
#else
#define SDEventSchemaTraceListener_ System_Diagnostics_EventSchemaTraceListener
#endif

@class System_Diagnostics_UnescapedXmlDiagnosticData;
#ifdef SDUnescapedXmlDiagnosticData_
#warning SDUnescapedXmlDiagnosticData_ class name collision.
#else
#define SDUnescapedXmlDiagnosticData_ System_Diagnostics_UnescapedXmlDiagnosticData
#endif

@class System_Diagnostics_TraceLogRetentionOption;
#ifdef SDTraceLogRetentionOption_
#warning SDTraceLogRetentionOption_ class name collision.
#else
#define SDTraceLogRetentionOption_ System_Diagnostics_TraceLogRetentionOption
#endif

@class System_Diagnostics_Eventing_EventProvider;
#ifdef SDEEventProvider_
#warning SDEEventProvider_ class name collision.
#else
#define SDEEventProvider_ System_Diagnostics_Eventing_EventProvider
#endif

@class System_Diagnostics_Eventing_EventProviderTraceListener;
#ifdef SDEEventProviderTraceListener_
#warning SDEEventProviderTraceListener_ class name collision.
#else
#define SDEEventProviderTraceListener_ System_Diagnostics_Eventing_EventProviderTraceListener
#endif

@class System_Diagnostics_Eventing_EventDescriptor;
#ifdef SDEEventDescriptor_
#warning SDEEventDescriptor_ class name collision.
#else
#define SDEEventDescriptor_ System_Diagnostics_Eventing_EventDescriptor
#endif

@class System_Diagnostics_Eventing_EventProvider__WriteEventErrorCode;
#ifdef SDEEventProvider_WriteEventErrorCode_
#warning SDEEventProvider_WriteEventErrorCode_ class name collision.
#else
#define SDEEventProvider_WriteEventErrorCode_ System_Diagnostics_Eventing_EventProvider__WriteEventErrorCode
#endif

@class System_Diagnostics_Eventing_Reader_EventBookmark;
#ifdef SDEREventBookmark_
#warning SDEREventBookmark_ class name collision.
#else
#define SDEREventBookmark_ System_Diagnostics_Eventing_Reader_EventBookmark
#endif

@class System_Diagnostics_Eventing_Reader_EventKeyword;
#ifdef SDEREventKeyword_
#warning SDEREventKeyword_ class name collision.
#else
#define SDEREventKeyword_ System_Diagnostics_Eventing_Reader_EventKeyword
#endif

@class System_Diagnostics_Eventing_Reader_EventLevel;
#ifdef SDEREventLevel_
#warning SDEREventLevel_ class name collision.
#else
#define SDEREventLevel_ System_Diagnostics_Eventing_Reader_EventLevel
#endif

@class System_Diagnostics_Eventing_Reader_EventLogConfiguration;
#ifdef SDEREventLogConfiguration_
#warning SDEREventLogConfiguration_ class name collision.
#else
#define SDEREventLogConfiguration_ System_Diagnostics_Eventing_Reader_EventLogConfiguration
#endif

@class System_Diagnostics_Eventing_Reader_EventLogException;
#ifdef SDEREventLogException_
#warning SDEREventLogException_ class name collision.
#else
#define SDEREventLogException_ System_Diagnostics_Eventing_Reader_EventLogException
#endif

@class System_Diagnostics_Eventing_Reader_EventLogInformation;
#ifdef SDEREventLogInformation_
#warning SDEREventLogInformation_ class name collision.
#else
#define SDEREventLogInformation_ System_Diagnostics_Eventing_Reader_EventLogInformation
#endif

@class System_Diagnostics_Eventing_Reader_EventLogInvalidDataException;
#ifdef SDEREventLogInvalidDataException_
#warning SDEREventLogInvalidDataException_ class name collision.
#else
#define SDEREventLogInvalidDataException_ System_Diagnostics_Eventing_Reader_EventLogInvalidDataException
#endif

@class System_Diagnostics_Eventing_Reader_EventLogLink;
#ifdef SDEREventLogLink_
#warning SDEREventLogLink_ class name collision.
#else
#define SDEREventLogLink_ System_Diagnostics_Eventing_Reader_EventLogLink
#endif

@class System_Diagnostics_Eventing_Reader_EventLogNotFoundException;
#ifdef SDEREventLogNotFoundException_
#warning SDEREventLogNotFoundException_ class name collision.
#else
#define SDEREventLogNotFoundException_ System_Diagnostics_Eventing_Reader_EventLogNotFoundException
#endif

@class System_Diagnostics_Eventing_Reader_EventLogPropertySelector;
#ifdef SDEREventLogPropertySelector_
#warning SDEREventLogPropertySelector_ class name collision.
#else
#define SDEREventLogPropertySelector_ System_Diagnostics_Eventing_Reader_EventLogPropertySelector
#endif

@class System_Diagnostics_Eventing_Reader_EventLogProviderDisabledException;
#ifdef SDEREventLogProviderDisabledException_
#warning SDEREventLogProviderDisabledException_ class name collision.
#else
#define SDEREventLogProviderDisabledException_ System_Diagnostics_Eventing_Reader_EventLogProviderDisabledException
#endif

@class System_Diagnostics_Eventing_Reader_EventLogQuery;
#ifdef SDEREventLogQuery_
#warning SDEREventLogQuery_ class name collision.
#else
#define SDEREventLogQuery_ System_Diagnostics_Eventing_Reader_EventLogQuery
#endif

@class System_Diagnostics_Eventing_Reader_EventLogReader;
#ifdef SDEREventLogReader_
#warning SDEREventLogReader_ class name collision.
#else
#define SDEREventLogReader_ System_Diagnostics_Eventing_Reader_EventLogReader
#endif

@class System_Diagnostics_Eventing_Reader_EventLogReadingException;
#ifdef SDEREventLogReadingException_
#warning SDEREventLogReadingException_ class name collision.
#else
#define SDEREventLogReadingException_ System_Diagnostics_Eventing_Reader_EventLogReadingException
#endif

@class System_Diagnostics_Eventing_Reader_EventLogRecord;
#ifdef SDEREventLogRecord_
#warning SDEREventLogRecord_ class name collision.
#else
#define SDEREventLogRecord_ System_Diagnostics_Eventing_Reader_EventLogRecord
#endif

@class System_Diagnostics_Eventing_Reader_EventLogSession;
#ifdef SDEREventLogSession_
#warning SDEREventLogSession_ class name collision.
#else
#define SDEREventLogSession_ System_Diagnostics_Eventing_Reader_EventLogSession
#endif

@class System_Diagnostics_Eventing_Reader_EventLogStatus;
#ifdef SDEREventLogStatus_
#warning SDEREventLogStatus_ class name collision.
#else
#define SDEREventLogStatus_ System_Diagnostics_Eventing_Reader_EventLogStatus
#endif

@class System_Diagnostics_Eventing_Reader_EventLogWatcher;
#ifdef SDEREventLogWatcher_
#warning SDEREventLogWatcher_ class name collision.
#else
#define SDEREventLogWatcher_ System_Diagnostics_Eventing_Reader_EventLogWatcher
#endif

@class System_Diagnostics_Eventing_Reader_EventMetadata;
#ifdef SDEREventMetadata_
#warning SDEREventMetadata_ class name collision.
#else
#define SDEREventMetadata_ System_Diagnostics_Eventing_Reader_EventMetadata
#endif

@class System_Diagnostics_Eventing_Reader_EventOpcode;
#ifdef SDEREventOpcode_
#warning SDEREventOpcode_ class name collision.
#else
#define SDEREventOpcode_ System_Diagnostics_Eventing_Reader_EventOpcode
#endif

@class System_Diagnostics_Eventing_Reader_EventProperty;
#ifdef SDEREventProperty_
#warning SDEREventProperty_ class name collision.
#else
#define SDEREventProperty_ System_Diagnostics_Eventing_Reader_EventProperty
#endif

@class System_Diagnostics_Eventing_Reader_EventRecord;
#ifdef SDEREventRecord_
#warning SDEREventRecord_ class name collision.
#else
#define SDEREventRecord_ System_Diagnostics_Eventing_Reader_EventRecord
#endif

@class System_Diagnostics_Eventing_Reader_EventRecordWrittenEventArgs;
#ifdef SDEREventRecordWrittenEventArgs_
#warning SDEREventRecordWrittenEventArgs_ class name collision.
#else
#define SDEREventRecordWrittenEventArgs_ System_Diagnostics_Eventing_Reader_EventRecordWrittenEventArgs
#endif

@class System_Diagnostics_Eventing_Reader_EventTask;
#ifdef SDEREventTask_
#warning SDEREventTask_ class name collision.
#else
#define SDEREventTask_ System_Diagnostics_Eventing_Reader_EventTask
#endif

@class System_Diagnostics_Eventing_Reader_ProviderMetadata;
#ifdef SDERProviderMetadata_
#warning SDERProviderMetadata_ class name collision.
#else
#define SDERProviderMetadata_ System_Diagnostics_Eventing_Reader_ProviderMetadata
#endif

@class System_Diagnostics_Eventing_Reader_EventLogIsolation;
#ifdef SDEREventLogIsolation_
#warning SDEREventLogIsolation_ class name collision.
#else
#define SDEREventLogIsolation_ System_Diagnostics_Eventing_Reader_EventLogIsolation
#endif

@class System_Diagnostics_Eventing_Reader_EventLogMode;
#ifdef SDEREventLogMode_
#warning SDEREventLogMode_ class name collision.
#else
#define SDEREventLogMode_ System_Diagnostics_Eventing_Reader_EventLogMode
#endif

@class System_Diagnostics_Eventing_Reader_EventLogType;
#ifdef SDEREventLogType_
#warning SDEREventLogType_ class name collision.
#else
#define SDEREventLogType_ System_Diagnostics_Eventing_Reader_EventLogType
#endif

@class System_Diagnostics_Eventing_Reader_PathType;
#ifdef SDERPathType_
#warning SDERPathType_ class name collision.
#else
#define SDERPathType_ System_Diagnostics_Eventing_Reader_PathType
#endif

@class System_Diagnostics_Eventing_Reader_SessionAuthentication;
#ifdef SDERSessionAuthentication_
#warning SDERSessionAuthentication_ class name collision.
#else
#define SDERSessionAuthentication_ System_Diagnostics_Eventing_Reader_SessionAuthentication
#endif

@class System_Diagnostics_Eventing_Reader_StandardEventKeywords;
#ifdef SDERStandardEventKeywords_
#warning SDERStandardEventKeywords_ class name collision.
#else
#define SDERStandardEventKeywords_ System_Diagnostics_Eventing_Reader_StandardEventKeywords
#endif

@class System_Diagnostics_Eventing_Reader_StandardEventLevel;
#ifdef SDERStandardEventLevel_
#warning SDERStandardEventLevel_ class name collision.
#else
#define SDERStandardEventLevel_ System_Diagnostics_Eventing_Reader_StandardEventLevel
#endif

@class System_Diagnostics_Eventing_Reader_StandardEventOpcode;
#ifdef SDERStandardEventOpcode_
#warning SDERStandardEventOpcode_ class name collision.
#else
#define SDERStandardEventOpcode_ System_Diagnostics_Eventing_Reader_StandardEventOpcode
#endif

@class System_Diagnostics_Eventing_Reader_StandardEventTask;
#ifdef SDERStandardEventTask_
#warning SDERStandardEventTask_ class name collision.
#else
#define SDERStandardEventTask_ System_Diagnostics_Eventing_Reader_StandardEventTask
#endif

@class System_Diagnostics_PerformanceData_CounterData;
#ifdef SDPCounterData_
#warning SDPCounterData_ class name collision.
#else
#define SDPCounterData_ System_Diagnostics_PerformanceData_CounterData
#endif

@class System_Diagnostics_PerformanceData_CounterSet;
#ifdef SDPCounterSet_
#warning SDPCounterSet_ class name collision.
#else
#define SDPCounterSet_ System_Diagnostics_PerformanceData_CounterSet
#endif

@class System_Diagnostics_PerformanceData_CounterSetInstance;
#ifdef SDPCounterSetInstance_
#warning SDPCounterSetInstance_ class name collision.
#else
#define SDPCounterSetInstance_ System_Diagnostics_PerformanceData_CounterSetInstance
#endif

@class System_Diagnostics_PerformanceData_CounterSetInstanceCounterDataSet;
#ifdef SDPCounterSetInstanceCounterDataSet_
#warning SDPCounterSetInstanceCounterDataSet_ class name collision.
#else
#define SDPCounterSetInstanceCounterDataSet_ System_Diagnostics_PerformanceData_CounterSetInstanceCounterDataSet
#endif

@class System_Diagnostics_PerformanceData_CounterSetInstanceType;
#ifdef SDPCounterSetInstanceType_
#warning SDPCounterSetInstanceType_ class name collision.
#else
#define SDPCounterSetInstanceType_ System_Diagnostics_PerformanceData_CounterSetInstanceType
#endif

@class System_Diagnostics_PerformanceData_CounterType;
#ifdef SDPCounterType_
#warning SDPCounterType_ class name collision.
#else
#define SDPCounterType_ System_Diagnostics_PerformanceData_CounterType
#endif

@class System_Dynamic_BinaryOperationBinder;
#ifdef SDBinaryOperationBinder_
#warning SDBinaryOperationBinder_ class name collision.
#else
#define SDBinaryOperationBinder_ System_Dynamic_BinaryOperationBinder
#endif

@class System_Dynamic_BindingRestrictions;
#ifdef SDBindingRestrictions_
#warning SDBindingRestrictions_ class name collision.
#else
#define SDBindingRestrictions_ System_Dynamic_BindingRestrictions
#endif

@class System_Dynamic_CallInfo;
#ifdef SDCallInfo_
#warning SDCallInfo_ class name collision.
#else
#define SDCallInfo_ System_Dynamic_CallInfo
#endif

@class System_Dynamic_ConvertBinder;
#ifdef SDConvertBinder_
#warning SDConvertBinder_ class name collision.
#else
#define SDConvertBinder_ System_Dynamic_ConvertBinder
#endif

@class System_Dynamic_CreateInstanceBinder;
#ifdef SDCreateInstanceBinder_
#warning SDCreateInstanceBinder_ class name collision.
#else
#define SDCreateInstanceBinder_ System_Dynamic_CreateInstanceBinder
#endif

@class System_Dynamic_DeleteIndexBinder;
#ifdef SDDeleteIndexBinder_
#warning SDDeleteIndexBinder_ class name collision.
#else
#define SDDeleteIndexBinder_ System_Dynamic_DeleteIndexBinder
#endif

@class System_Dynamic_DeleteMemberBinder;
#ifdef SDDeleteMemberBinder_
#warning SDDeleteMemberBinder_ class name collision.
#else
#define SDDeleteMemberBinder_ System_Dynamic_DeleteMemberBinder
#endif

@class System_Dynamic_DynamicMetaObject;
#ifdef SDDynamicMetaObject_
#warning SDDynamicMetaObject_ class name collision.
#else
#define SDDynamicMetaObject_ System_Dynamic_DynamicMetaObject
#endif

@class System_Dynamic_DynamicMetaObjectBinder;
#ifdef SDDynamicMetaObjectBinder_
#warning SDDynamicMetaObjectBinder_ class name collision.
#else
#define SDDynamicMetaObjectBinder_ System_Dynamic_DynamicMetaObjectBinder
#endif

@class System_Dynamic_DynamicObject;
#ifdef SDDynamicObject_
#warning SDDynamicObject_ class name collision.
#else
#define SDDynamicObject_ System_Dynamic_DynamicObject
#endif

@class System_Dynamic_ExpandoObject;
#ifdef SDExpandoObject_
#warning SDExpandoObject_ class name collision.
#else
#define SDExpandoObject_ System_Dynamic_ExpandoObject
#endif

@class System_Dynamic_GetIndexBinder;
#ifdef SDGetIndexBinder_
#warning SDGetIndexBinder_ class name collision.
#else
#define SDGetIndexBinder_ System_Dynamic_GetIndexBinder
#endif

@class System_Dynamic_GetMemberBinder;
#ifdef SDGetMemberBinder_
#warning SDGetMemberBinder_ class name collision.
#else
#define SDGetMemberBinder_ System_Dynamic_GetMemberBinder
#endif

@class System_Dynamic_InvokeBinder;
#ifdef SDInvokeBinder_
#warning SDInvokeBinder_ class name collision.
#else
#define SDInvokeBinder_ System_Dynamic_InvokeBinder
#endif

@class System_Dynamic_InvokeMemberBinder;
#ifdef SDInvokeMemberBinder_
#warning SDInvokeMemberBinder_ class name collision.
#else
#define SDInvokeMemberBinder_ System_Dynamic_InvokeMemberBinder
#endif

@class System_Dynamic_SetIndexBinder;
#ifdef SDSetIndexBinder_
#warning SDSetIndexBinder_ class name collision.
#else
#define SDSetIndexBinder_ System_Dynamic_SetIndexBinder
#endif

@class System_Dynamic_SetMemberBinder;
#ifdef SDSetMemberBinder_
#warning SDSetMemberBinder_ class name collision.
#else
#define SDSetMemberBinder_ System_Dynamic_SetMemberBinder
#endif

@class System_Dynamic_UnaryOperationBinder;
#ifdef SDUnaryOperationBinder_
#warning SDUnaryOperationBinder_ class name collision.
#else
#define SDUnaryOperationBinder_ System_Dynamic_UnaryOperationBinder
#endif

@class System_Dynamic_IDynamicMetaObjectProvider;
#ifdef SDIDynamicMetaObjectProvider_
#warning SDIDynamicMetaObjectProvider_ class name collision.
#else
#define SDIDynamicMetaObjectProvider_ System_Dynamic_IDynamicMetaObjectProvider
#endif

@class System_Dynamic_IInvokeOnGetBinder;
#ifdef SDIInvokeOnGetBinder_
#warning SDIInvokeOnGetBinder_ class name collision.
#else
#define SDIInvokeOnGetBinder_ System_Dynamic_IInvokeOnGetBinder
#endif

@class System_IO_HandleInheritability;
#ifdef SIHandleInheritability_
#warning SIHandleInheritability_ class name collision.
#else
#define SIHandleInheritability_ System_IO_HandleInheritability
#endif

@class System_IO_MemoryMappedFiles_MemoryMappedFile;
#ifdef SIMMemoryMappedFile_
#warning SIMMemoryMappedFile_ class name collision.
#else
#define SIMMemoryMappedFile_ System_IO_MemoryMappedFiles_MemoryMappedFile
#endif

@class System_IO_MemoryMappedFiles_MemoryMappedFileSecurity;
#ifdef SIMMemoryMappedFileSecurity_
#warning SIMMemoryMappedFileSecurity_ class name collision.
#else
#define SIMMemoryMappedFileSecurity_ System_IO_MemoryMappedFiles_MemoryMappedFileSecurity
#endif

@class System_IO_MemoryMappedFiles_MemoryMappedViewAccessor;
#ifdef SIMMemoryMappedViewAccessor_
#warning SIMMemoryMappedViewAccessor_ class name collision.
#else
#define SIMMemoryMappedViewAccessor_ System_IO_MemoryMappedFiles_MemoryMappedViewAccessor
#endif

@class System_IO_MemoryMappedFiles_MemoryMappedViewStream;
#ifdef SIMMemoryMappedViewStream_
#warning SIMMemoryMappedViewStream_ class name collision.
#else
#define SIMMemoryMappedViewStream_ System_IO_MemoryMappedFiles_MemoryMappedViewStream
#endif

@class System_IO_MemoryMappedFiles_MemoryMappedFileAccess;
#ifdef SIMMemoryMappedFileAccess_
#warning SIMMemoryMappedFileAccess_ class name collision.
#else
#define SIMMemoryMappedFileAccess_ System_IO_MemoryMappedFiles_MemoryMappedFileAccess
#endif

@class System_IO_MemoryMappedFiles_MemoryMappedFileOptions;
#ifdef SIMMemoryMappedFileOptions_
#warning SIMMemoryMappedFileOptions_ class name collision.
#else
#define SIMMemoryMappedFileOptions_ System_IO_MemoryMappedFiles_MemoryMappedFileOptions
#endif

@class System_IO_MemoryMappedFiles_MemoryMappedFileRights;
#ifdef SIMMemoryMappedFileRights_
#warning SIMMemoryMappedFileRights_ class name collision.
#else
#define SIMMemoryMappedFileRights_ System_IO_MemoryMappedFiles_MemoryMappedFileRights
#endif

@class System_IO_Pipes_AnonymousPipeClientStream;
#ifdef SIPAnonymousPipeClientStream_
#warning SIPAnonymousPipeClientStream_ class name collision.
#else
#define SIPAnonymousPipeClientStream_ System_IO_Pipes_AnonymousPipeClientStream
#endif

@class System_IO_Pipes_AnonymousPipeServerStream;
#ifdef SIPAnonymousPipeServerStream_
#warning SIPAnonymousPipeServerStream_ class name collision.
#else
#define SIPAnonymousPipeServerStream_ System_IO_Pipes_AnonymousPipeServerStream
#endif

@class System_IO_Pipes_NamedPipeClientStream;
#ifdef SIPNamedPipeClientStream_
#warning SIPNamedPipeClientStream_ class name collision.
#else
#define SIPNamedPipeClientStream_ System_IO_Pipes_NamedPipeClientStream
#endif

@class System_IO_Pipes_NamedPipeServerStream;
#ifdef SIPNamedPipeServerStream_
#warning SIPNamedPipeServerStream_ class name collision.
#else
#define SIPNamedPipeServerStream_ System_IO_Pipes_NamedPipeServerStream
#endif

@class System_IO_Pipes_PipeAccessRule;
#ifdef SIPPipeAccessRule_
#warning SIPPipeAccessRule_ class name collision.
#else
#define SIPPipeAccessRule_ System_IO_Pipes_PipeAccessRule
#endif

@class System_IO_Pipes_PipeAuditRule;
#ifdef SIPPipeAuditRule_
#warning SIPPipeAuditRule_ class name collision.
#else
#define SIPPipeAuditRule_ System_IO_Pipes_PipeAuditRule
#endif

@class System_IO_Pipes_PipeSecurity;
#ifdef SIPPipeSecurity_
#warning SIPPipeSecurity_ class name collision.
#else
#define SIPPipeSecurity_ System_IO_Pipes_PipeSecurity
#endif

@class System_IO_Pipes_PipeStream;
#ifdef SIPPipeStream_
#warning SIPPipeStream_ class name collision.
#else
#define SIPPipeStream_ System_IO_Pipes_PipeStream
#endif

@class System_IO_Pipes_PipeStreamImpersonationWorker;
#ifdef SIPPipeStreamImpersonationWorker_
#warning SIPPipeStreamImpersonationWorker_ class name collision.
#else
#define SIPPipeStreamImpersonationWorker_ System_IO_Pipes_PipeStreamImpersonationWorker
#endif

@class System_IO_Pipes_PipeAccessRights;
#ifdef SIPPipeAccessRights_
#warning SIPPipeAccessRights_ class name collision.
#else
#define SIPPipeAccessRights_ System_IO_Pipes_PipeAccessRights
#endif

@class System_IO_Pipes_PipeDirection;
#ifdef SIPPipeDirection_
#warning SIPPipeDirection_ class name collision.
#else
#define SIPPipeDirection_ System_IO_Pipes_PipeDirection
#endif

@class System_IO_Pipes_PipeOptions;
#ifdef SIPPipeOptions_
#warning SIPPipeOptions_ class name collision.
#else
#define SIPPipeOptions_ System_IO_Pipes_PipeOptions
#endif

@class System_IO_Pipes_PipeTransmissionMode;
#ifdef SIPPipeTransmissionMode_
#warning SIPPipeTransmissionMode_ class name collision.
#else
#define SIPPipeTransmissionMode_ System_IO_Pipes_PipeTransmissionMode
#endif

@class System_Linq_Enumerable;
#ifdef SLEnumerable_
#warning SLEnumerable_ class name collision.
#else
#define SLEnumerable_ System_Linq_Enumerable
#endif

@class System_Linq_EnumerableExecutor;
#ifdef SLEnumerableExecutor_
#warning SLEnumerableExecutor_ class name collision.
#else
#define SLEnumerableExecutor_ System_Linq_EnumerableExecutor
#endif

@class System_Linq_EnumerableExecutorA1;
#ifdef SLEnumerableExecutorA1_
#warning SLEnumerableExecutorA1_ class name collision.
#else
#define SLEnumerableExecutorA1_ System_Linq_EnumerableExecutorA1
#endif

@class System_Linq_EnumerableQuery;
#ifdef SLEnumerableQuery_
#warning SLEnumerableQuery_ class name collision.
#else
#define SLEnumerableQuery_ System_Linq_EnumerableQuery
#endif

@class System_Linq_EnumerableQueryA1;
#ifdef SLEnumerableQueryA1_
#warning SLEnumerableQueryA1_ class name collision.
#else
#define SLEnumerableQueryA1_ System_Linq_EnumerableQueryA1
#endif

@class System_Linq_LookupA2;
#ifdef SLLookupA2_
#warning SLLookupA2_ class name collision.
#else
#define SLLookupA2_ System_Linq_LookupA2
#endif

@class System_Linq_OrderedParallelQueryA1;
#ifdef SLOrderedParallelQueryA1_
#warning SLOrderedParallelQueryA1_ class name collision.
#else
#define SLOrderedParallelQueryA1_ System_Linq_OrderedParallelQueryA1
#endif

@class System_Linq_ParallelEnumerable;
#ifdef SLParallelEnumerable_
#warning SLParallelEnumerable_ class name collision.
#else
#define SLParallelEnumerable_ System_Linq_ParallelEnumerable
#endif

@class System_Linq_ParallelQuery;
#ifdef SLParallelQuery_
#warning SLParallelQuery_ class name collision.
#else
#define SLParallelQuery_ System_Linq_ParallelQuery
#endif

@class System_Linq_ParallelQueryA1;
#ifdef SLParallelQueryA1_
#warning SLParallelQueryA1_ class name collision.
#else
#define SLParallelQueryA1_ System_Linq_ParallelQueryA1
#endif

@class System_Linq_Queryable;
#ifdef SLQueryable_
#warning SLQueryable_ class name collision.
#else
#define SLQueryable_ System_Linq_Queryable
#endif

@class System_Linq_IGroupingA2;
#ifdef SLIGroupingA2_
#warning SLIGroupingA2_ class name collision.
#else
#define SLIGroupingA2_ System_Linq_IGroupingA2
#endif

@class System_Linq_ILookupA2;
#ifdef SLILookupA2_
#warning SLILookupA2_ class name collision.
#else
#define SLILookupA2_ System_Linq_ILookupA2
#endif

@class System_Linq_IOrderedEnumerableA1;
#ifdef SLIOrderedEnumerableA1_
#warning SLIOrderedEnumerableA1_ class name collision.
#else
#define SLIOrderedEnumerableA1_ System_Linq_IOrderedEnumerableA1
#endif

@class System_Linq_IOrderedQueryable;
#ifdef SLIOrderedQueryable_
#warning SLIOrderedQueryable_ class name collision.
#else
#define SLIOrderedQueryable_ System_Linq_IOrderedQueryable
#endif

@class System_Linq_IOrderedQueryableA1;
#ifdef SLIOrderedQueryableA1_
#warning SLIOrderedQueryableA1_ class name collision.
#else
#define SLIOrderedQueryableA1_ System_Linq_IOrderedQueryableA1
#endif

@class System_Linq_IQueryable;
#ifdef SLIQueryable_
#warning SLIQueryable_ class name collision.
#else
#define SLIQueryable_ System_Linq_IQueryable
#endif

@class System_Linq_IQueryableA1;
#ifdef SLIQueryableA1_
#warning SLIQueryableA1_ class name collision.
#else
#define SLIQueryableA1_ System_Linq_IQueryableA1
#endif

@class System_Linq_IQueryProvider;
#ifdef SLIQueryProvider_
#warning SLIQueryProvider_ class name collision.
#else
#define SLIQueryProvider_ System_Linq_IQueryProvider
#endif

@class System_Linq_ParallelExecutionMode;
#ifdef SLParallelExecutionMode_
#warning SLParallelExecutionMode_ class name collision.
#else
#define SLParallelExecutionMode_ System_Linq_ParallelExecutionMode
#endif

@class System_Linq_ParallelMergeOptions;
#ifdef SLParallelMergeOptions_
#warning SLParallelMergeOptions_ class name collision.
#else
#define SLParallelMergeOptions_ System_Linq_ParallelMergeOptions
#endif

@class System_Linq_Expressions_BinaryExpression;
#ifdef SLEBinaryExpression_
#warning SLEBinaryExpression_ class name collision.
#else
#define SLEBinaryExpression_ System_Linq_Expressions_BinaryExpression
#endif

@class System_Linq_Expressions_BlockExpression;
#ifdef SLEBlockExpression_
#warning SLEBlockExpression_ class name collision.
#else
#define SLEBlockExpression_ System_Linq_Expressions_BlockExpression
#endif

@class System_Linq_Expressions_CatchBlock;
#ifdef SLECatchBlock_
#warning SLECatchBlock_ class name collision.
#else
#define SLECatchBlock_ System_Linq_Expressions_CatchBlock
#endif

@class System_Linq_Expressions_ConditionalExpression;
#ifdef SLEConditionalExpression_
#warning SLEConditionalExpression_ class name collision.
#else
#define SLEConditionalExpression_ System_Linq_Expressions_ConditionalExpression
#endif

@class System_Linq_Expressions_ConstantExpression;
#ifdef SLEConstantExpression_
#warning SLEConstantExpression_ class name collision.
#else
#define SLEConstantExpression_ System_Linq_Expressions_ConstantExpression
#endif

@class System_Linq_Expressions_DebugInfoExpression;
#ifdef SLEDebugInfoExpression_
#warning SLEDebugInfoExpression_ class name collision.
#else
#define SLEDebugInfoExpression_ System_Linq_Expressions_DebugInfoExpression
#endif

@class System_Linq_Expressions_DefaultExpression;
#ifdef SLEDefaultExpression_
#warning SLEDefaultExpression_ class name collision.
#else
#define SLEDefaultExpression_ System_Linq_Expressions_DefaultExpression
#endif

@class System_Linq_Expressions_DynamicExpression;
#ifdef SLEDynamicExpression_
#warning SLEDynamicExpression_ class name collision.
#else
#define SLEDynamicExpression_ System_Linq_Expressions_DynamicExpression
#endif

@class System_Linq_Expressions_DynamicExpressionVisitor;
#ifdef SLEDynamicExpressionVisitor_
#warning SLEDynamicExpressionVisitor_ class name collision.
#else
#define SLEDynamicExpressionVisitor_ System_Linq_Expressions_DynamicExpressionVisitor
#endif

@class System_Linq_Expressions_ElementInit;
#ifdef SLEElementInit_
#warning SLEElementInit_ class name collision.
#else
#define SLEElementInit_ System_Linq_Expressions_ElementInit
#endif

@class System_Linq_Expressions_Expression;
#ifdef SLEExpression_
#warning SLEExpression_ class name collision.
#else
#define SLEExpression_ System_Linq_Expressions_Expression
#endif

@class System_Linq_Expressions_ExpressionA1;
#ifdef SLEExpressionA1_
#warning SLEExpressionA1_ class name collision.
#else
#define SLEExpressionA1_ System_Linq_Expressions_ExpressionA1
#endif

@class System_Linq_Expressions_ExpressionVisitor;
#ifdef SLEExpressionVisitor_
#warning SLEExpressionVisitor_ class name collision.
#else
#define SLEExpressionVisitor_ System_Linq_Expressions_ExpressionVisitor
#endif

@class System_Linq_Expressions_GotoExpression;
#ifdef SLEGotoExpression_
#warning SLEGotoExpression_ class name collision.
#else
#define SLEGotoExpression_ System_Linq_Expressions_GotoExpression
#endif

@class System_Linq_Expressions_IndexExpression;
#ifdef SLEIndexExpression_
#warning SLEIndexExpression_ class name collision.
#else
#define SLEIndexExpression_ System_Linq_Expressions_IndexExpression
#endif

@class System_Linq_Expressions_InvocationExpression;
#ifdef SLEInvocationExpression_
#warning SLEInvocationExpression_ class name collision.
#else
#define SLEInvocationExpression_ System_Linq_Expressions_InvocationExpression
#endif

@class System_Linq_Expressions_LabelExpression;
#ifdef SLELabelExpression_
#warning SLELabelExpression_ class name collision.
#else
#define SLELabelExpression_ System_Linq_Expressions_LabelExpression
#endif

@class System_Linq_Expressions_LabelTarget;
#ifdef SLELabelTarget_
#warning SLELabelTarget_ class name collision.
#else
#define SLELabelTarget_ System_Linq_Expressions_LabelTarget
#endif

@class System_Linq_Expressions_LambdaExpression;
#ifdef SLELambdaExpression_
#warning SLELambdaExpression_ class name collision.
#else
#define SLELambdaExpression_ System_Linq_Expressions_LambdaExpression
#endif

@class System_Linq_Expressions_ListInitExpression;
#ifdef SLEListInitExpression_
#warning SLEListInitExpression_ class name collision.
#else
#define SLEListInitExpression_ System_Linq_Expressions_ListInitExpression
#endif

@class System_Linq_Expressions_LoopExpression;
#ifdef SLELoopExpression_
#warning SLELoopExpression_ class name collision.
#else
#define SLELoopExpression_ System_Linq_Expressions_LoopExpression
#endif

@class System_Linq_Expressions_MemberAssignment;
#ifdef SLEMemberAssignment_
#warning SLEMemberAssignment_ class name collision.
#else
#define SLEMemberAssignment_ System_Linq_Expressions_MemberAssignment
#endif

@class System_Linq_Expressions_MemberBinding;
#ifdef SLEMemberBinding_
#warning SLEMemberBinding_ class name collision.
#else
#define SLEMemberBinding_ System_Linq_Expressions_MemberBinding
#endif

@class System_Linq_Expressions_MemberExpression;
#ifdef SLEMemberExpression_
#warning SLEMemberExpression_ class name collision.
#else
#define SLEMemberExpression_ System_Linq_Expressions_MemberExpression
#endif

@class System_Linq_Expressions_MemberInitExpression;
#ifdef SLEMemberInitExpression_
#warning SLEMemberInitExpression_ class name collision.
#else
#define SLEMemberInitExpression_ System_Linq_Expressions_MemberInitExpression
#endif

@class System_Linq_Expressions_MemberListBinding;
#ifdef SLEMemberListBinding_
#warning SLEMemberListBinding_ class name collision.
#else
#define SLEMemberListBinding_ System_Linq_Expressions_MemberListBinding
#endif

@class System_Linq_Expressions_MemberMemberBinding;
#ifdef SLEMemberMemberBinding_
#warning SLEMemberMemberBinding_ class name collision.
#else
#define SLEMemberMemberBinding_ System_Linq_Expressions_MemberMemberBinding
#endif

@class System_Linq_Expressions_MethodCallExpression;
#ifdef SLEMethodCallExpression_
#warning SLEMethodCallExpression_ class name collision.
#else
#define SLEMethodCallExpression_ System_Linq_Expressions_MethodCallExpression
#endif

@class System_Linq_Expressions_NewArrayExpression;
#ifdef SLENewArrayExpression_
#warning SLENewArrayExpression_ class name collision.
#else
#define SLENewArrayExpression_ System_Linq_Expressions_NewArrayExpression
#endif

@class System_Linq_Expressions_NewExpression;
#ifdef SLENewExpression_
#warning SLENewExpression_ class name collision.
#else
#define SLENewExpression_ System_Linq_Expressions_NewExpression
#endif

@class System_Linq_Expressions_ParameterExpression;
#ifdef SLEParameterExpression_
#warning SLEParameterExpression_ class name collision.
#else
#define SLEParameterExpression_ System_Linq_Expressions_ParameterExpression
#endif

@class System_Linq_Expressions_RuntimeVariablesExpression;
#ifdef SLERuntimeVariablesExpression_
#warning SLERuntimeVariablesExpression_ class name collision.
#else
#define SLERuntimeVariablesExpression_ System_Linq_Expressions_RuntimeVariablesExpression
#endif

@class System_Linq_Expressions_SwitchCase;
#ifdef SLESwitchCase_
#warning SLESwitchCase_ class name collision.
#else
#define SLESwitchCase_ System_Linq_Expressions_SwitchCase
#endif

@class System_Linq_Expressions_SwitchExpression;
#ifdef SLESwitchExpression_
#warning SLESwitchExpression_ class name collision.
#else
#define SLESwitchExpression_ System_Linq_Expressions_SwitchExpression
#endif

@class System_Linq_Expressions_SymbolDocumentInfo;
#ifdef SLESymbolDocumentInfo_
#warning SLESymbolDocumentInfo_ class name collision.
#else
#define SLESymbolDocumentInfo_ System_Linq_Expressions_SymbolDocumentInfo
#endif

@class System_Linq_Expressions_TryExpression;
#ifdef SLETryExpression_
#warning SLETryExpression_ class name collision.
#else
#define SLETryExpression_ System_Linq_Expressions_TryExpression
#endif

@class System_Linq_Expressions_TypeBinaryExpression;
#ifdef SLETypeBinaryExpression_
#warning SLETypeBinaryExpression_ class name collision.
#else
#define SLETypeBinaryExpression_ System_Linq_Expressions_TypeBinaryExpression
#endif

@class System_Linq_Expressions_UnaryExpression;
#ifdef SLEUnaryExpression_
#warning SLEUnaryExpression_ class name collision.
#else
#define SLEUnaryExpression_ System_Linq_Expressions_UnaryExpression
#endif

@class System_Linq_Expressions_IArgumentProvider;
#ifdef SLEIArgumentProvider_
#warning SLEIArgumentProvider_ class name collision.
#else
#define SLEIArgumentProvider_ System_Linq_Expressions_IArgumentProvider
#endif

@class System_Linq_Expressions_IDynamicExpression;
#ifdef SLEIDynamicExpression_
#warning SLEIDynamicExpression_ class name collision.
#else
#define SLEIDynamicExpression_ System_Linq_Expressions_IDynamicExpression
#endif

@class System_Linq_Expressions_ExpressionType;
#ifdef SLEExpressionType_
#warning SLEExpressionType_ class name collision.
#else
#define SLEExpressionType_ System_Linq_Expressions_ExpressionType
#endif

@class System_Linq_Expressions_GotoExpressionKind;
#ifdef SLEGotoExpressionKind_
#warning SLEGotoExpressionKind_ class name collision.
#else
#define SLEGotoExpressionKind_ System_Linq_Expressions_GotoExpressionKind
#endif

@class System_Linq_Expressions_MemberBindingType;
#ifdef SLEMemberBindingType_
#warning SLEMemberBindingType_ class name collision.
#else
#define SLEMemberBindingType_ System_Linq_Expressions_MemberBindingType
#endif

@class System_Management_Instrumentation_InstanceNotFoundException;
#ifdef SMIInstanceNotFoundException_
#warning SMIInstanceNotFoundException_ class name collision.
#else
#define SMIInstanceNotFoundException_ System_Management_Instrumentation_InstanceNotFoundException
#endif

@class System_Management_Instrumentation_InstrumentationBaseException;
#ifdef SMIInstrumentationBaseException_
#warning SMIInstrumentationBaseException_ class name collision.
#else
#define SMIInstrumentationBaseException_ System_Management_Instrumentation_InstrumentationBaseException
#endif

@class System_Management_Instrumentation_InstrumentationException;
#ifdef SMIInstrumentationException_
#warning SMIInstrumentationException_ class name collision.
#else
#define SMIInstrumentationException_ System_Management_Instrumentation_InstrumentationException
#endif

@class System_Management_Instrumentation_ManagementBindAttribute;
#ifdef SMIManagementBindAttribute_
#warning SMIManagementBindAttribute_ class name collision.
#else
#define SMIManagementBindAttribute_ System_Management_Instrumentation_ManagementBindAttribute
#endif

@class System_Management_Instrumentation_ManagementCommitAttribute;
#ifdef SMIManagementCommitAttribute_
#warning SMIManagementCommitAttribute_ class name collision.
#else
#define SMIManagementCommitAttribute_ System_Management_Instrumentation_ManagementCommitAttribute
#endif

@class System_Management_Instrumentation_ManagementConfigurationAttribute;
#ifdef SMIManagementConfigurationAttribute_
#warning SMIManagementConfigurationAttribute_ class name collision.
#else
#define SMIManagementConfigurationAttribute_ System_Management_Instrumentation_ManagementConfigurationAttribute
#endif

@class System_Management_Instrumentation_ManagementCreateAttribute;
#ifdef SMIManagementCreateAttribute_
#warning SMIManagementCreateAttribute_ class name collision.
#else
#define SMIManagementCreateAttribute_ System_Management_Instrumentation_ManagementCreateAttribute
#endif

@class System_Management_Instrumentation_ManagementEntityAttribute;
#ifdef SMIManagementEntityAttribute_
#warning SMIManagementEntityAttribute_ class name collision.
#else
#define SMIManagementEntityAttribute_ System_Management_Instrumentation_ManagementEntityAttribute
#endif

@class System_Management_Instrumentation_ManagementEnumeratorAttribute;
#ifdef SMIManagementEnumeratorAttribute_
#warning SMIManagementEnumeratorAttribute_ class name collision.
#else
#define SMIManagementEnumeratorAttribute_ System_Management_Instrumentation_ManagementEnumeratorAttribute
#endif

@class System_Management_Instrumentation_ManagementKeyAttribute;
#ifdef SMIManagementKeyAttribute_
#warning SMIManagementKeyAttribute_ class name collision.
#else
#define SMIManagementKeyAttribute_ System_Management_Instrumentation_ManagementKeyAttribute
#endif

@class System_Management_Instrumentation_ManagementMemberAttribute;
#ifdef SMIManagementMemberAttribute_
#warning SMIManagementMemberAttribute_ class name collision.
#else
#define SMIManagementMemberAttribute_ System_Management_Instrumentation_ManagementMemberAttribute
#endif

@class System_Management_Instrumentation_ManagementNameAttribute;
#ifdef SMIManagementNameAttribute_
#warning SMIManagementNameAttribute_ class name collision.
#else
#define SMIManagementNameAttribute_ System_Management_Instrumentation_ManagementNameAttribute
#endif

@class System_Management_Instrumentation_ManagementNewInstanceAttribute;
#ifdef SMIManagementNewInstanceAttribute_
#warning SMIManagementNewInstanceAttribute_ class name collision.
#else
#define SMIManagementNewInstanceAttribute_ System_Management_Instrumentation_ManagementNewInstanceAttribute
#endif

@class System_Management_Instrumentation_ManagementProbeAttribute;
#ifdef SMIManagementProbeAttribute_
#warning SMIManagementProbeAttribute_ class name collision.
#else
#define SMIManagementProbeAttribute_ System_Management_Instrumentation_ManagementProbeAttribute
#endif

@class System_Management_Instrumentation_ManagementReferenceAttribute;
#ifdef SMIManagementReferenceAttribute_
#warning SMIManagementReferenceAttribute_ class name collision.
#else
#define SMIManagementReferenceAttribute_ System_Management_Instrumentation_ManagementReferenceAttribute
#endif

@class System_Management_Instrumentation_ManagementRemoveAttribute;
#ifdef SMIManagementRemoveAttribute_
#warning SMIManagementRemoveAttribute_ class name collision.
#else
#define SMIManagementRemoveAttribute_ System_Management_Instrumentation_ManagementRemoveAttribute
#endif

@class System_Management_Instrumentation_ManagementTaskAttribute;
#ifdef SMIManagementTaskAttribute_
#warning SMIManagementTaskAttribute_ class name collision.
#else
#define SMIManagementTaskAttribute_ System_Management_Instrumentation_ManagementTaskAttribute
#endif

@class System_Management_Instrumentation_WmiConfigurationAttribute;
#ifdef SMIWmiConfigurationAttribute_
#warning SMIWmiConfigurationAttribute_ class name collision.
#else
#define SMIWmiConfigurationAttribute_ System_Management_Instrumentation_WmiConfigurationAttribute
#endif

@class System_Management_Instrumentation_ManagementConfigurationType;
#ifdef SMIManagementConfigurationType_
#warning SMIManagementConfigurationType_ class name collision.
#else
#define SMIManagementConfigurationType_ System_Management_Instrumentation_ManagementConfigurationType
#endif

@class System_Management_Instrumentation_ManagementHostingModel;
#ifdef SMIManagementHostingModel_
#warning SMIManagementHostingModel_ class name collision.
#else
#define SMIManagementHostingModel_ System_Management_Instrumentation_ManagementHostingModel
#endif

@class System_Runtime_CompilerServices_CallSite;
#ifdef SRCCallSite_
#warning SRCCallSite_ class name collision.
#else
#define SRCCallSite_ System_Runtime_CompilerServices_CallSite
#endif

@class System_Runtime_CompilerServices_CallSiteA1;
#ifdef SRCCallSiteA1_
#warning SRCCallSiteA1_ class name collision.
#else
#define SRCCallSiteA1_ System_Runtime_CompilerServices_CallSiteA1
#endif

@class System_Runtime_CompilerServices_CallSiteBinder;
#ifdef SRCCallSiteBinder_
#warning SRCCallSiteBinder_ class name collision.
#else
#define SRCCallSiteBinder_ System_Runtime_CompilerServices_CallSiteBinder
#endif

@class System_Runtime_CompilerServices_CallSiteHelpers;
#ifdef SRCCallSiteHelpers_
#warning SRCCallSiteHelpers_ class name collision.
#else
#define SRCCallSiteHelpers_ System_Runtime_CompilerServices_CallSiteHelpers
#endif

@class System_Runtime_CompilerServices_CallSiteOps;
#ifdef SRCCallSiteOps_
#warning SRCCallSiteOps_ class name collision.
#else
#define SRCCallSiteOps_ System_Runtime_CompilerServices_CallSiteOps
#endif

@class System_Runtime_CompilerServices_Closure;
#ifdef SRCClosure_
#warning SRCClosure_ class name collision.
#else
#define SRCClosure_ System_Runtime_CompilerServices_Closure
#endif

@class System_Runtime_CompilerServices_DebugInfoGenerator;
#ifdef SRCDebugInfoGenerator_
#warning SRCDebugInfoGenerator_ class name collision.
#else
#define SRCDebugInfoGenerator_ System_Runtime_CompilerServices_DebugInfoGenerator
#endif

@class System_Runtime_CompilerServices_DynamicAttribute;
#ifdef SRCDynamicAttribute_
#warning SRCDynamicAttribute_ class name collision.
#else
#define SRCDynamicAttribute_ System_Runtime_CompilerServices_DynamicAttribute
#endif

@class System_Runtime_CompilerServices_ExecutionScope;
#ifdef SRCExecutionScope_
#warning SRCExecutionScope_ class name collision.
#else
#define SRCExecutionScope_ System_Runtime_CompilerServices_ExecutionScope
#endif

@class System_Runtime_CompilerServices_ReadOnlyCollectionBuilderA1;
#ifdef SRCReadOnlyCollectionBuilderA1_
#warning SRCReadOnlyCollectionBuilderA1_ class name collision.
#else
#define SRCReadOnlyCollectionBuilderA1_ System_Runtime_CompilerServices_ReadOnlyCollectionBuilderA1
#endif

@class System_Runtime_CompilerServices_RuleCacheA1;
#ifdef SRCRuleCacheA1_
#warning SRCRuleCacheA1_ class name collision.
#else
#define SRCRuleCacheA1_ System_Runtime_CompilerServices_RuleCacheA1
#endif

@class System_Runtime_CompilerServices_RuntimeOps;
#ifdef SRCRuntimeOps_
#warning SRCRuntimeOps_ class name collision.
#else
#define SRCRuntimeOps_ System_Runtime_CompilerServices_RuntimeOps
#endif

@class System_Runtime_CompilerServices_StrongBoxA1;
#ifdef SRCStrongBoxA1_
#warning SRCStrongBoxA1_ class name collision.
#else
#define SRCStrongBoxA1_ System_Runtime_CompilerServices_StrongBoxA1
#endif

@class System_Runtime_CompilerServices_IRuntimeVariables;
#ifdef SRCIRuntimeVariables_
#warning SRCIRuntimeVariables_ class name collision.
#else
#define SRCIRuntimeVariables_ System_Runtime_CompilerServices_IRuntimeVariables
#endif

@class System_Runtime_CompilerServices_IStrongBox;
#ifdef SRCIStrongBox_
#warning SRCIStrongBox_ class name collision.
#else
#define SRCIStrongBox_ System_Runtime_CompilerServices_IStrongBox
#endif

@class System_Runtime_InteropServices_ComAwareEventInfo;
#ifdef SRIComAwareEventInfo_
#warning SRIComAwareEventInfo_ class name collision.
#else
#define SRIComAwareEventInfo_ System_Runtime_InteropServices_ComAwareEventInfo
#endif

@class System_Security_ManifestKinds;
#ifdef SSManifestKinds_
#warning SSManifestKinds_ class name collision.
#else
#define SSManifestKinds_ System_Security_ManifestKinds
#endif

@class System_Security_Cryptography_AesCng;
#ifdef SSCAesCng_
#warning SSCAesCng_ class name collision.
#else
#define SSCAesCng_ System_Security_Cryptography_AesCng
#endif

@class System_Security_Cryptography_AesCryptoServiceProvider;
#ifdef SSCAesCryptoServiceProvider_
#warning SSCAesCryptoServiceProvider_ class name collision.
#else
#define SSCAesCryptoServiceProvider_ System_Security_Cryptography_AesCryptoServiceProvider
#endif

@class System_Security_Cryptography_AesManaged;
#ifdef SSCAesManaged_
#warning SSCAesManaged_ class name collision.
#else
#define SSCAesManaged_ System_Security_Cryptography_AesManaged
#endif

@class System_Security_Cryptography_CngAlgorithm;
#ifdef SSCCngAlgorithm_
#warning SSCCngAlgorithm_ class name collision.
#else
#define SSCCngAlgorithm_ System_Security_Cryptography_CngAlgorithm
#endif

@class System_Security_Cryptography_CngAlgorithmGroup;
#ifdef SSCCngAlgorithmGroup_
#warning SSCCngAlgorithmGroup_ class name collision.
#else
#define SSCCngAlgorithmGroup_ System_Security_Cryptography_CngAlgorithmGroup
#endif

@class System_Security_Cryptography_CngKey;
#ifdef SSCCngKey_
#warning SSCCngKey_ class name collision.
#else
#define SSCCngKey_ System_Security_Cryptography_CngKey
#endif

@class System_Security_Cryptography_CngKeyBlobFormat;
#ifdef SSCCngKeyBlobFormat_
#warning SSCCngKeyBlobFormat_ class name collision.
#else
#define SSCCngKeyBlobFormat_ System_Security_Cryptography_CngKeyBlobFormat
#endif

@class System_Security_Cryptography_CngKeyCreationParameters;
#ifdef SSCCngKeyCreationParameters_
#warning SSCCngKeyCreationParameters_ class name collision.
#else
#define SSCCngKeyCreationParameters_ System_Security_Cryptography_CngKeyCreationParameters
#endif

@class System_Security_Cryptography_CngPropertyCollection;
#ifdef SSCCngPropertyCollection_
#warning SSCCngPropertyCollection_ class name collision.
#else
#define SSCCngPropertyCollection_ System_Security_Cryptography_CngPropertyCollection
#endif

@class System_Security_Cryptography_CngProvider;
#ifdef SSCCngProvider_
#warning SSCCngProvider_ class name collision.
#else
#define SSCCngProvider_ System_Security_Cryptography_CngProvider
#endif

@class System_Security_Cryptography_CngUIPolicy;
#ifdef SSCCngUIPolicy_
#warning SSCCngUIPolicy_ class name collision.
#else
#define SSCCngUIPolicy_ System_Security_Cryptography_CngUIPolicy
#endif

@class System_Security_Cryptography_DSACng;
#ifdef SSCDSACng_
#warning SSCDSACng_ class name collision.
#else
#define SSCDSACng_ System_Security_Cryptography_DSACng
#endif

@class System_Security_Cryptography_ECCurve__NamedCurves;
#ifdef SSCECCurve_NamedCurves_
#warning SSCECCurve_NamedCurves_ class name collision.
#else
#define SSCECCurve_NamedCurves_ System_Security_Cryptography_ECCurve__NamedCurves
#endif

@class System_Security_Cryptography_ECDiffieHellman;
#ifdef SSCECDiffieHellman_
#warning SSCECDiffieHellman_ class name collision.
#else
#define SSCECDiffieHellman_ System_Security_Cryptography_ECDiffieHellman
#endif

@class System_Security_Cryptography_ECDiffieHellmanCng;
#ifdef SSCECDiffieHellmanCng_
#warning SSCECDiffieHellmanCng_ class name collision.
#else
#define SSCECDiffieHellmanCng_ System_Security_Cryptography_ECDiffieHellmanCng
#endif

@class System_Security_Cryptography_ECDiffieHellmanCngPublicKey;
#ifdef SSCECDiffieHellmanCngPublicKey_
#warning SSCECDiffieHellmanCngPublicKey_ class name collision.
#else
#define SSCECDiffieHellmanCngPublicKey_ System_Security_Cryptography_ECDiffieHellmanCngPublicKey
#endif

@class System_Security_Cryptography_ECDiffieHellmanPublicKey;
#ifdef SSCECDiffieHellmanPublicKey_
#warning SSCECDiffieHellmanPublicKey_ class name collision.
#else
#define SSCECDiffieHellmanPublicKey_ System_Security_Cryptography_ECDiffieHellmanPublicKey
#endif

@class System_Security_Cryptography_ECDsa;
#ifdef SSCECDsa_
#warning SSCECDsa_ class name collision.
#else
#define SSCECDsa_ System_Security_Cryptography_ECDsa
#endif

@class System_Security_Cryptography_ECDsaCng;
#ifdef SSCECDsaCng_
#warning SSCECDsaCng_ class name collision.
#else
#define SSCECDsaCng_ System_Security_Cryptography_ECDsaCng
#endif

@class System_Security_Cryptography_ManifestSignatureInformation;
#ifdef SSCManifestSignatureInformation_
#warning SSCManifestSignatureInformation_ class name collision.
#else
#define SSCManifestSignatureInformation_ System_Security_Cryptography_ManifestSignatureInformation
#endif

@class System_Security_Cryptography_ManifestSignatureInformationCollection;
#ifdef SSCManifestSignatureInformationCollection_
#warning SSCManifestSignatureInformationCollection_ class name collision.
#else
#define SSCManifestSignatureInformationCollection_ System_Security_Cryptography_ManifestSignatureInformationCollection
#endif

@class System_Security_Cryptography_MD5Cng;
#ifdef SSCMD5Cng_
#warning SSCMD5Cng_ class name collision.
#else
#define SSCMD5Cng_ System_Security_Cryptography_MD5Cng
#endif

@class System_Security_Cryptography_RSACng;
#ifdef SSCRSACng_
#warning SSCRSACng_ class name collision.
#else
#define SSCRSACng_ System_Security_Cryptography_RSACng
#endif

@class System_Security_Cryptography_SHA1Cng;
#ifdef SSCSHA1Cng_
#warning SSCSHA1Cng_ class name collision.
#else
#define SSCSHA1Cng_ System_Security_Cryptography_SHA1Cng
#endif

@class System_Security_Cryptography_SHA256Cng;
#ifdef SSCSHA256Cng_
#warning SSCSHA256Cng_ class name collision.
#else
#define SSCSHA256Cng_ System_Security_Cryptography_SHA256Cng
#endif

@class System_Security_Cryptography_SHA256CryptoServiceProvider;
#ifdef SSCSHA256CryptoServiceProvider_
#warning SSCSHA256CryptoServiceProvider_ class name collision.
#else
#define SSCSHA256CryptoServiceProvider_ System_Security_Cryptography_SHA256CryptoServiceProvider
#endif

@class System_Security_Cryptography_SHA384Cng;
#ifdef SSCSHA384Cng_
#warning SSCSHA384Cng_ class name collision.
#else
#define SSCSHA384Cng_ System_Security_Cryptography_SHA384Cng
#endif

@class System_Security_Cryptography_SHA384CryptoServiceProvider;
#ifdef SSCSHA384CryptoServiceProvider_
#warning SSCSHA384CryptoServiceProvider_ class name collision.
#else
#define SSCSHA384CryptoServiceProvider_ System_Security_Cryptography_SHA384CryptoServiceProvider
#endif

@class System_Security_Cryptography_SHA512Cng;
#ifdef SSCSHA512Cng_
#warning SSCSHA512Cng_ class name collision.
#else
#define SSCSHA512Cng_ System_Security_Cryptography_SHA512Cng
#endif

@class System_Security_Cryptography_SHA512CryptoServiceProvider;
#ifdef SSCSHA512CryptoServiceProvider_
#warning SSCSHA512CryptoServiceProvider_ class name collision.
#else
#define SSCSHA512CryptoServiceProvider_ System_Security_Cryptography_SHA512CryptoServiceProvider
#endif

@class System_Security_Cryptography_StrongNameSignatureInformation;
#ifdef SSCStrongNameSignatureInformation_
#warning SSCStrongNameSignatureInformation_ class name collision.
#else
#define SSCStrongNameSignatureInformation_ System_Security_Cryptography_StrongNameSignatureInformation
#endif

@class System_Security_Cryptography_TripleDESCng;
#ifdef SSCTripleDESCng_
#warning SSCTripleDESCng_ class name collision.
#else
#define SSCTripleDESCng_ System_Security_Cryptography_TripleDESCng
#endif

@class System_Security_Cryptography_CngProperty;
#ifdef SSCCngProperty_
#warning SSCCngProperty_ class name collision.
#else
#define SSCCngProperty_ System_Security_Cryptography_CngProperty
#endif

@class System_Security_Cryptography_ECCurve;
#ifdef SSCECCurve_
#warning SSCECCurve_ class name collision.
#else
#define SSCECCurve_ System_Security_Cryptography_ECCurve
#endif

@class System_Security_Cryptography_ECParameters;
#ifdef SSCECParameters_
#warning SSCECParameters_ class name collision.
#else
#define SSCECParameters_ System_Security_Cryptography_ECParameters
#endif

@class System_Security_Cryptography_ECPoint;
#ifdef SSCECPoint_
#warning SSCECPoint_ class name collision.
#else
#define SSCECPoint_ System_Security_Cryptography_ECPoint
#endif

@class System_Security_Cryptography_CngExportPolicies;
#ifdef SSCCngExportPolicies_
#warning SSCCngExportPolicies_ class name collision.
#else
#define SSCCngExportPolicies_ System_Security_Cryptography_CngExportPolicies
#endif

@class System_Security_Cryptography_CngKeyCreationOptions;
#ifdef SSCCngKeyCreationOptions_
#warning SSCCngKeyCreationOptions_ class name collision.
#else
#define SSCCngKeyCreationOptions_ System_Security_Cryptography_CngKeyCreationOptions
#endif

@class System_Security_Cryptography_CngKeyHandleOpenOptions;
#ifdef SSCCngKeyHandleOpenOptions_
#warning SSCCngKeyHandleOpenOptions_ class name collision.
#else
#define SSCCngKeyHandleOpenOptions_ System_Security_Cryptography_CngKeyHandleOpenOptions
#endif

@class System_Security_Cryptography_CngKeyOpenOptions;
#ifdef SSCCngKeyOpenOptions_
#warning SSCCngKeyOpenOptions_ class name collision.
#else
#define SSCCngKeyOpenOptions_ System_Security_Cryptography_CngKeyOpenOptions
#endif

@class System_Security_Cryptography_CngKeyUsages;
#ifdef SSCCngKeyUsages_
#warning SSCCngKeyUsages_ class name collision.
#else
#define SSCCngKeyUsages_ System_Security_Cryptography_CngKeyUsages
#endif

@class System_Security_Cryptography_CngPropertyOptions;
#ifdef SSCCngPropertyOptions_
#warning SSCCngPropertyOptions_ class name collision.
#else
#define SSCCngPropertyOptions_ System_Security_Cryptography_CngPropertyOptions
#endif

@class System_Security_Cryptography_CngUIProtectionLevels;
#ifdef SSCCngUIProtectionLevels_
#warning SSCCngUIProtectionLevels_ class name collision.
#else
#define SSCCngUIProtectionLevels_ System_Security_Cryptography_CngUIProtectionLevels
#endif

@class System_Security_Cryptography_ECCurve__ECCurveType;
#ifdef SSCECCurve_ECCurveType_
#warning SSCECCurve_ECCurveType_ class name collision.
#else
#define SSCECCurve_ECCurveType_ System_Security_Cryptography_ECCurve__ECCurveType
#endif

@class System_Security_Cryptography_ECDiffieHellmanKeyDerivationFunction;
#ifdef SSCECDiffieHellmanKeyDerivationFunction_
#warning SSCECDiffieHellmanKeyDerivationFunction_ class name collision.
#else
#define SSCECDiffieHellmanKeyDerivationFunction_ System_Security_Cryptography_ECDiffieHellmanKeyDerivationFunction
#endif

@class System_Security_Cryptography_ECKeyXmlFormat;
#ifdef SSCECKeyXmlFormat_
#warning SSCECKeyXmlFormat_ class name collision.
#else
#define SSCECKeyXmlFormat_ System_Security_Cryptography_ECKeyXmlFormat
#endif

@class System_Security_Cryptography_SignatureVerificationResult;
#ifdef SSCSignatureVerificationResult_
#warning SSCSignatureVerificationResult_ class name collision.
#else
#define SSCSignatureVerificationResult_ System_Security_Cryptography_SignatureVerificationResult
#endif

@class System_Security_Cryptography_X509Certificates_AuthenticodeSignatureInformation;
#ifdef SSCXAuthenticodeSignatureInformation_
#warning SSCXAuthenticodeSignatureInformation_ class name collision.
#else
#define SSCXAuthenticodeSignatureInformation_ System_Security_Cryptography_X509Certificates_AuthenticodeSignatureInformation
#endif

@class System_Security_Cryptography_X509Certificates_DSACertificateExtensions;
#ifdef SSCXDSACertificateExtensions_
#warning SSCXDSACertificateExtensions_ class name collision.
#else
#define SSCXDSACertificateExtensions_ System_Security_Cryptography_X509Certificates_DSACertificateExtensions
#endif

@class System_Security_Cryptography_X509Certificates_ECDsaCertificateExtensions;
#ifdef SSCXECDsaCertificateExtensions_
#warning SSCXECDsaCertificateExtensions_ class name collision.
#else
#define SSCXECDsaCertificateExtensions_ System_Security_Cryptography_X509Certificates_ECDsaCertificateExtensions
#endif

@class System_Security_Cryptography_X509Certificates_RSACertificateExtensions;
#ifdef SSCXRSACertificateExtensions_
#warning SSCXRSACertificateExtensions_ class name collision.
#else
#define SSCXRSACertificateExtensions_ System_Security_Cryptography_X509Certificates_RSACertificateExtensions
#endif

@class System_Security_Cryptography_X509Certificates_TimestampInformation;
#ifdef SSCXTimestampInformation_
#warning SSCXTimestampInformation_ class name collision.
#else
#define SSCXTimestampInformation_ System_Security_Cryptography_X509Certificates_TimestampInformation
#endif

@class System_Security_Cryptography_X509Certificates_TrustStatus;
#ifdef SSCXTrustStatus_
#warning SSCXTrustStatus_ class name collision.
#else
#define SSCXTrustStatus_ System_Security_Cryptography_X509Certificates_TrustStatus
#endif

@class System_Threading_ReaderWriterLockSlim;
#ifdef STReaderWriterLockSlim_
#warning STReaderWriterLockSlim_ class name collision.
#else
#define STReaderWriterLockSlim_ System_Threading_ReaderWriterLockSlim
#endif

@class System_Threading_LockRecursionPolicy;
#ifdef STLockRecursionPolicy_
#warning STLockRecursionPolicy_ class name collision.
#else
#define STLockRecursionPolicy_ System_Threading_LockRecursionPolicy
#endif

@class System_Threading_Tasks_TaskExtensions;
#ifdef STTTaskExtensions_
#warning STTTaskExtensions_ class name collision.
#else
#define STTTaskExtensions_ System_Threading_Tasks_TaskExtensions
#endif


/*

Order here is Enumerations, Interface protocols, Structs, Classes, Explicit interface classes

*/

#import "System_Diagnostics_TraceLogRetentionOption.h"
#import "System_Diagnostics_Eventing_EventProvider__WriteEventErrorCode.h"
#import "System_Diagnostics_Eventing_Reader_EventLogIsolation.h"
#import "System_Diagnostics_Eventing_Reader_EventLogMode.h"
#import "System_Diagnostics_Eventing_Reader_EventLogType.h"
#import "System_Diagnostics_Eventing_Reader_PathType.h"
#import "System_Diagnostics_Eventing_Reader_SessionAuthentication.h"
#import "System_Diagnostics_Eventing_Reader_StandardEventKeywords.h"
#import "System_Diagnostics_Eventing_Reader_StandardEventLevel.h"
#import "System_Diagnostics_Eventing_Reader_StandardEventOpcode.h"
#import "System_Diagnostics_Eventing_Reader_StandardEventTask.h"
#import "System_Diagnostics_PerformanceData_CounterSetInstanceType.h"
#import "System_Diagnostics_PerformanceData_CounterType.h"
#import "System_IO_HandleInheritability.h"
#import "System_IO_MemoryMappedFiles_MemoryMappedFileAccess.h"
#import "System_IO_MemoryMappedFiles_MemoryMappedFileOptions.h"
#import "System_IO_MemoryMappedFiles_MemoryMappedFileRights.h"
#import "System_IO_Pipes_PipeAccessRights.h"
#import "System_IO_Pipes_PipeDirection.h"
#import "System_IO_Pipes_PipeOptions.h"
#import "System_IO_Pipes_PipeTransmissionMode.h"
#import "System_Linq_ParallelExecutionMode.h"
#import "System_Linq_ParallelMergeOptions.h"
#import "System_Linq_Expressions_ExpressionType.h"
#import "System_Linq_Expressions_GotoExpressionKind.h"
#import "System_Linq_Expressions_MemberBindingType.h"
#import "System_Management_Instrumentation_ManagementConfigurationType.h"
#import "System_Management_Instrumentation_ManagementHostingModel.h"
#import "System_Security_ManifestKinds.h"
#import "System_Security_Cryptography_CngExportPolicies.h"
#import "System_Security_Cryptography_CngKeyCreationOptions.h"
#import "System_Security_Cryptography_CngKeyHandleOpenOptions.h"
#import "System_Security_Cryptography_CngKeyOpenOptions.h"
#import "System_Security_Cryptography_CngKeyUsages.h"
#import "System_Security_Cryptography_CngPropertyOptions.h"
#import "System_Security_Cryptography_CngUIProtectionLevels.h"
#import "System_Security_Cryptography_ECCurve__ECCurveType.h"
#import "System_Security_Cryptography_ECDiffieHellmanKeyDerivationFunction.h"
#import "System_Security_Cryptography_ECKeyXmlFormat.h"
#import "System_Security_Cryptography_SignatureVerificationResult.h"
#import "System_Security_Cryptography_X509Certificates_TrustStatus.h"
#import "System_Threading_LockRecursionPolicy.h"
#import "System_Dynamic_IDynamicMetaObjectProvider_Protocol.h"
#import "System_Dynamic_IInvokeOnGetBinder_Protocol.h"
#import "System_Linq_IGroupingA2_Protocol.h"
#import "System_Linq_ILookupA2_Protocol.h"
#import "System_Linq_IOrderedEnumerableA1_Protocol.h"
#import "System_Linq_IQueryable_Protocol.h"
#import "System_Linq_IOrderedQueryable_Protocol.h"
#import "System_Linq_IQueryableA1_Protocol.h"
#import "System_Linq_IOrderedQueryableA1_Protocol.h"
#import "System_Linq_IQueryProvider_Protocol.h"
#import "System_Linq_Expressions_IArgumentProvider_Protocol.h"
#import "System_Linq_Expressions_IDynamicExpression_Protocol.h"
#import "System_Runtime_CompilerServices_IRuntimeVariables_Protocol.h"
#import "System_Runtime_CompilerServices_IStrongBox_Protocol.h"
#import "System_Collections_Generic_HashSetA1__Enumerator.h"
#import "System_Diagnostics_Eventing_EventDescriptor.h"
#import "System_Security_Cryptography_CngProperty.h"
#import "System_Security_Cryptography_ECCurve.h"
#import "System_Security_Cryptography_ECParameters.h"
#import "System_Security_Cryptography_ECPoint.h"
#import "Microsoft_Win32_SafeHandles_SafeMemoryMappedFileHandle.h"
#import "Microsoft_Win32_SafeHandles_SafeMemoryMappedViewHandle.h"
#import "Microsoft_Win32_SafeHandles_SafeNCryptHandle.h"
#import "Microsoft_Win32_SafeHandles_SafeNCryptKeyHandle.h"
#import "Microsoft_Win32_SafeHandles_SafeNCryptProviderHandle.h"
#import "Microsoft_Win32_SafeHandles_SafeNCryptSecretHandle.h"
#import "Microsoft_Win32_SafeHandles_SafePipeHandle.h"
#import "System_ActionA10.h"
#import "System_ActionA11.h"
#import "System_ActionA12.h"
#import "System_ActionA13.h"
#import "System_ActionA14.h"
#import "System_ActionA15.h"
#import "System_ActionA16.h"
#import "System_ActionA9.h"
#import "System_FuncA10.h"
#import "System_FuncA11.h"
#import "System_FuncA12.h"
#import "System_FuncA13.h"
#import "System_FuncA14.h"
#import "System_FuncA15.h"
#import "System_FuncA16.h"
#import "System_FuncA17.h"
#import "System_Collections_Generic_HashSetA1.h"
#import "System_Diagnostics_EventSchemaTraceListener.h"
#import "System_Diagnostics_UnescapedXmlDiagnosticData.h"
#import "System_Diagnostics_Eventing_EventProvider.h"
#import "System_Diagnostics_Eventing_EventProviderTraceListener.h"
#import "System_Diagnostics_Eventing_Reader_EventBookmark.h"
#import "System_Diagnostics_Eventing_Reader_EventKeyword.h"
#import "System_Diagnostics_Eventing_Reader_EventLevel.h"
#import "System_Diagnostics_Eventing_Reader_EventLogConfiguration.h"
#import "System_Diagnostics_Eventing_Reader_EventLogException.h"
#import "System_Diagnostics_Eventing_Reader_EventLogInformation.h"
#import "System_Diagnostics_Eventing_Reader_EventLogInvalidDataException.h"
#import "System_Diagnostics_Eventing_Reader_EventLogLink.h"
#import "System_Diagnostics_Eventing_Reader_EventLogNotFoundException.h"
#import "System_Diagnostics_Eventing_Reader_EventLogPropertySelector.h"
#import "System_Diagnostics_Eventing_Reader_EventLogProviderDisabledException.h"
#import "System_Diagnostics_Eventing_Reader_EventLogQuery.h"
#import "System_Diagnostics_Eventing_Reader_EventLogReader.h"
#import "System_Diagnostics_Eventing_Reader_EventLogReadingException.h"
#import "System_Diagnostics_Eventing_Reader_EventRecord.h"
#import "System_Diagnostics_Eventing_Reader_EventLogRecord.h"
#import "System_Diagnostics_Eventing_Reader_EventLogSession.h"
#import "System_Diagnostics_Eventing_Reader_EventLogStatus.h"
#import "System_Diagnostics_Eventing_Reader_EventLogWatcher.h"
#import "System_Diagnostics_Eventing_Reader_EventMetadata.h"
#import "System_Diagnostics_Eventing_Reader_EventOpcode.h"
#import "System_Diagnostics_Eventing_Reader_EventProperty.h"
#import "System_Diagnostics_Eventing_Reader_EventRecordWrittenEventArgs.h"
#import "System_Diagnostics_Eventing_Reader_EventTask.h"
#import "System_Diagnostics_Eventing_Reader_ProviderMetadata.h"
#import "System_Diagnostics_PerformanceData_CounterData.h"
#import "System_Diagnostics_PerformanceData_CounterSet.h"
#import "System_Diagnostics_PerformanceData_CounterSetInstance.h"
#import "System_Diagnostics_PerformanceData_CounterSetInstanceCounterDataSet.h"
#import "System_Runtime_CompilerServices_CallSiteBinder.h"
#import "System_Dynamic_DynamicMetaObjectBinder.h"
#import "System_Dynamic_BinaryOperationBinder.h"
#import "System_Dynamic_BindingRestrictions.h"
#import "System_Dynamic_CallInfo.h"
#import "System_Dynamic_ConvertBinder.h"
#import "System_Dynamic_CreateInstanceBinder.h"
#import "System_Dynamic_DeleteIndexBinder.h"
#import "System_Dynamic_DeleteMemberBinder.h"
#import "System_Dynamic_DynamicMetaObject.h"
#import "System_Dynamic_DynamicObject.h"
#import "System_Dynamic_ExpandoObject.h"
#import "System_Dynamic_GetIndexBinder.h"
#import "System_Dynamic_GetMemberBinder.h"
#import "System_Dynamic_InvokeBinder.h"
#import "System_Dynamic_InvokeMemberBinder.h"
#import "System_Dynamic_SetIndexBinder.h"
#import "System_Dynamic_SetMemberBinder.h"
#import "System_Dynamic_UnaryOperationBinder.h"
#import "System_IO_MemoryMappedFiles_MemoryMappedFile.h"
#import "System_IO_MemoryMappedFiles_MemoryMappedFileSecurity.h"
#import "System_IO_MemoryMappedFiles_MemoryMappedViewAccessor.h"
#import "System_IO_MemoryMappedFiles_MemoryMappedViewStream.h"
#import "System_IO_Pipes_PipeStream.h"
#import "System_IO_Pipes_AnonymousPipeClientStream.h"
#import "System_IO_Pipes_AnonymousPipeServerStream.h"
#import "System_IO_Pipes_NamedPipeClientStream.h"
#import "System_IO_Pipes_NamedPipeServerStream.h"
#import "System_IO_Pipes_PipeAccessRule.h"
#import "System_IO_Pipes_PipeAuditRule.h"
#import "System_IO_Pipes_PipeSecurity.h"
#import "System_IO_Pipes_PipeStreamImpersonationWorker.h"
#import "System_Linq_Enumerable.h"
#import "System_Linq_EnumerableExecutor.h"
#import "System_Linq_EnumerableExecutorA1.h"
#import "System_Linq_EnumerableQuery.h"
#import "System_Linq_EnumerableQueryA1.h"
#import "System_Linq_LookupA2.h"
#import "System_Linq_ParallelQuery.h"
#import "System_Linq_ParallelQueryA1.h"
#import "System_Linq_OrderedParallelQueryA1.h"
#import "System_Linq_ParallelEnumerable.h"
#import "System_Linq_Queryable.h"
#import "System_Linq_Expressions_Expression.h"
#import "System_Linq_Expressions_BinaryExpression.h"
#import "System_Linq_Expressions_BlockExpression.h"
#import "System_Linq_Expressions_CatchBlock.h"
#import "System_Linq_Expressions_ConditionalExpression.h"
#import "System_Linq_Expressions_ConstantExpression.h"
#import "System_Linq_Expressions_DebugInfoExpression.h"
#import "System_Linq_Expressions_DefaultExpression.h"
#import "System_Linq_Expressions_DynamicExpression.h"
#import "System_Linq_Expressions_ExpressionVisitor.h"
#import "System_Linq_Expressions_DynamicExpressionVisitor.h"
#import "System_Linq_Expressions_ElementInit.h"
#import "System_Linq_Expressions_LambdaExpression.h"
#import "System_Linq_Expressions_ExpressionA1.h"
#import "System_Linq_Expressions_GotoExpression.h"
#import "System_Linq_Expressions_IndexExpression.h"
#import "System_Linq_Expressions_InvocationExpression.h"
#import "System_Linq_Expressions_LabelExpression.h"
#import "System_Linq_Expressions_LabelTarget.h"
#import "System_Linq_Expressions_ListInitExpression.h"
#import "System_Linq_Expressions_LoopExpression.h"
#import "System_Linq_Expressions_MemberBinding.h"
#import "System_Linq_Expressions_MemberAssignment.h"
#import "System_Linq_Expressions_MemberExpression.h"
#import "System_Linq_Expressions_MemberInitExpression.h"
#import "System_Linq_Expressions_MemberListBinding.h"
#import "System_Linq_Expressions_MemberMemberBinding.h"
#import "System_Linq_Expressions_MethodCallExpression.h"
#import "System_Linq_Expressions_NewArrayExpression.h"
#import "System_Linq_Expressions_NewExpression.h"
#import "System_Linq_Expressions_ParameterExpression.h"
#import "System_Linq_Expressions_RuntimeVariablesExpression.h"
#import "System_Linq_Expressions_SwitchCase.h"
#import "System_Linq_Expressions_SwitchExpression.h"
#import "System_Linq_Expressions_SymbolDocumentInfo.h"
#import "System_Linq_Expressions_TryExpression.h"
#import "System_Linq_Expressions_TypeBinaryExpression.h"
#import "System_Linq_Expressions_UnaryExpression.h"
#import "System_Management_Instrumentation_InstrumentationBaseException.h"
#import "System_Management_Instrumentation_InstrumentationException.h"
#import "System_Management_Instrumentation_InstanceNotFoundException.h"
#import "System_Management_Instrumentation_ManagementMemberAttribute.h"
#import "System_Management_Instrumentation_ManagementNewInstanceAttribute.h"
#import "System_Management_Instrumentation_ManagementBindAttribute.h"
#import "System_Management_Instrumentation_ManagementCommitAttribute.h"
#import "System_Management_Instrumentation_ManagementConfigurationAttribute.h"
#import "System_Management_Instrumentation_ManagementCreateAttribute.h"
#import "System_Management_Instrumentation_ManagementEntityAttribute.h"
#import "System_Management_Instrumentation_ManagementEnumeratorAttribute.h"
#import "System_Management_Instrumentation_ManagementKeyAttribute.h"
#import "System_Management_Instrumentation_ManagementNameAttribute.h"
#import "System_Management_Instrumentation_ManagementProbeAttribute.h"
#import "System_Management_Instrumentation_ManagementReferenceAttribute.h"
#import "System_Management_Instrumentation_ManagementRemoveAttribute.h"
#import "System_Management_Instrumentation_ManagementTaskAttribute.h"
#import "System_Management_Instrumentation_WmiConfigurationAttribute.h"
#import "System_Runtime_CompilerServices_CallSite.h"
#import "System_Runtime_CompilerServices_CallSiteA1.h"
#import "System_Runtime_CompilerServices_CallSiteHelpers.h"
#import "System_Runtime_CompilerServices_CallSiteOps.h"
#import "System_Runtime_CompilerServices_Closure.h"
#import "System_Runtime_CompilerServices_DebugInfoGenerator.h"
#import "System_Runtime_CompilerServices_DynamicAttribute.h"
#import "System_Runtime_CompilerServices_ExecutionScope.h"
#import "System_Runtime_CompilerServices_ReadOnlyCollectionBuilderA1.h"
#import "System_Runtime_CompilerServices_RuleCacheA1.h"
#import "System_Runtime_CompilerServices_RuntimeOps.h"
#import "System_Runtime_CompilerServices_StrongBoxA1.h"
#import "System_Runtime_InteropServices_ComAwareEventInfo.h"
#import "System_Security_Cryptography_AesCng.h"
#import "System_Security_Cryptography_AesCryptoServiceProvider.h"
#import "System_Security_Cryptography_AesManaged.h"
#import "System_Security_Cryptography_CngAlgorithm.h"
#import "System_Security_Cryptography_CngAlgorithmGroup.h"
#import "System_Security_Cryptography_CngKey.h"
#import "System_Security_Cryptography_CngKeyBlobFormat.h"
#import "System_Security_Cryptography_CngKeyCreationParameters.h"
#import "System_Security_Cryptography_CngPropertyCollection.h"
#import "System_Security_Cryptography_CngProvider.h"
#import "System_Security_Cryptography_CngUIPolicy.h"
#import "System_Security_Cryptography_DSACng.h"
#import "System_Security_Cryptography_ECCurve__NamedCurves.h"
#import "System_Security_Cryptography_ECDiffieHellman.h"
#import "System_Security_Cryptography_ECDiffieHellmanCng.h"
#import "System_Security_Cryptography_ECDiffieHellmanPublicKey.h"
#import "System_Security_Cryptography_ECDiffieHellmanCngPublicKey.h"
#import "System_Security_Cryptography_ECDsa.h"
#import "System_Security_Cryptography_ECDsaCng.h"
#import "System_Security_Cryptography_ManifestSignatureInformation.h"
#import "System_Security_Cryptography_ManifestSignatureInformationCollection.h"
#import "System_Security_Cryptography_MD5Cng.h"
#import "System_Security_Cryptography_RSACng.h"
#import "System_Security_Cryptography_SHA1Cng.h"
#import "System_Security_Cryptography_SHA256Cng.h"
#import "System_Security_Cryptography_SHA256CryptoServiceProvider.h"
#import "System_Security_Cryptography_SHA384Cng.h"
#import "System_Security_Cryptography_SHA384CryptoServiceProvider.h"
#import "System_Security_Cryptography_SHA512Cng.h"
#import "System_Security_Cryptography_SHA512CryptoServiceProvider.h"
#import "System_Security_Cryptography_StrongNameSignatureInformation.h"
#import "System_Security_Cryptography_TripleDESCng.h"
#import "System_Security_Cryptography_X509Certificates_AuthenticodeSignatureInformation.h"
#import "System_Security_Cryptography_X509Certificates_DSACertificateExtensions.h"
#import "System_Security_Cryptography_X509Certificates_ECDsaCertificateExtensions.h"
#import "System_Security_Cryptography_X509Certificates_RSACertificateExtensions.h"
#import "System_Security_Cryptography_X509Certificates_TimestampInformation.h"
#import "System_Threading_ReaderWriterLockSlim.h"
#import "System_Threading_Tasks_TaskExtensions.h"
#import "System_Dynamic_IDynamicMetaObjectProvider.h"
#import "System_Dynamic_IInvokeOnGetBinder.h"
#import "System_Linq_IGroupingA2.h"
#import "System_Linq_ILookupA2.h"
#import "System_Linq_IOrderedEnumerableA1.h"
#import "System_Linq_IQueryable.h"
#import "System_Linq_IOrderedQueryable.h"
#import "System_Linq_IQueryableA1.h"
#import "System_Linq_IOrderedQueryableA1.h"
#import "System_Linq_IQueryProvider.h"
#import "System_Linq_Expressions_IArgumentProvider.h"
#import "System_Linq_Expressions_IDynamicExpression.h"
#import "System_Runtime_CompilerServices_IRuntimeVariables.h"
#import "System_Runtime_CompilerServices_IStrongBox.h"
