//
//  Dubrovnik_Unit_Tests.m
//  Dubrovnik Unit Tests
//
//  Created by Jonathan on 02/07/2013.
//
//
#import <Dubrovnik/Dubrovnik.h>
#import "Dubrovnik_Unit_Tests.h"
#import "DBUReferenceObject.h"
#import "DBUIReferenceObject.h"
#import "DBUGenericReferenceObjectA2.h"
#import <mono.mscorlib/DBSystem_Object.h>

static BOOL m_runningAutoGenCodeTest = NO;

// toggle 0-1
// it may be useful to disable certain tests when adding support for new features

/*

 two sets of unit test data exist.
 one is hand coded, the other generated by the code gen.

 when DB_RUN_MANUAL_CODE_TEST evaluates to 0 the tests
 are not run against the manually generated unit test model.

 when DB_RUN_AUTO_GENERATED_CODE_TEST evaluates to 0 the tests
 are not run against the generated unit test model.
 
 */
#define DB_RUN_MANUAL_CODE_TEST 1
#define DB_RUN_AUTO_GENERATED_CODE_TEST 1

#define DB_VALUETYPE_BY_REFERENCE_SUPPORT 1

#if DB_RUN_AUTO_GENERATED_CODE_TEST == 1
#import "Dubrovnik_UnitTests.h"
#endif


@implementation NSObject (Dubrovnik_UnitTests)
- (BOOL)dbTestString:(NSString *)string
{
    return (string && [string isKindOfClass:[NSString class]] && [(id)self rangeOfString:string].location != NSNotFound) ? YES : NO;
}
@end

NSString *DBUTestString = @"Dubrovnik";

// test failure notices
NSString *DBUObjectNotCreated = @"Object not created";
NSString *DBUObjectIsNil = @"Object is nil";
NSString *DBUBooleanTestFailed = @"Boolean test failed";
NSString *DBUEqualityTestFailed = @"Equality test failed";
NSString *DBUInequalityTestFailed = @"Inequality test failed";
NSString *DBULessThanTestFailed = @"Less than test failed";
NSString *DBUGreaterThanTestFailed = @"Greater than test failed";
NSString *DBUSubstringTestFailed = @"Substring not found";
NSString *DBUCountTestFailed = @"Count test failed";
NSString *DBUNotNilTestFailed = @"Not nil test failed";
NSString *DBUExceptionTestFailed = @"An exception test failed";
NSString *DBUObjectNotFound = @"Object not found";
NSString *DBUNilTestFailed = @"Nil test failed";
NSString *DBUClassTestFailed = @"Class test failed";
NSString *DBUDesignedToFailTestPassed = @"Designed to fail test passed";

static BOOL _setup = NO;
static MonoAssembly *monoAssembly;

@interface EventTarget : NSObject <EventTarget>
@property NSUInteger event1Fired;
@property NSUInteger event2Fired;

@end

@interface Dubrovnik_Unit_Tests()

- (void)doTestReferenceClass:(Class)testClass;
- (id)doTestConstructorsWithclass:(Class)testClass;
- (void)doTestFields:(id)refObject class:(Class)testClass;
- (void)doTestExtensionMethods:(id)refObject class:(Class)testClass;
- (void)doTestMethods:(id)refObject class:(Class)testClass;
- (void)doTestProperties:(id)refObject class:(Class)testClass;
- (void)doTestStructRepresentation:(id)refObject class:(Class)testClass;
- (void)doTestInterfaceRepresentation:(id)refObject class:(Class)testClass;
- (void)doTestArrayProperties:(id)refObject class:(Class)testClass;
- (void)doTestArrayListRepresentation:(id)refObject class:(Class)testClass;
- (void)doTestArrayMethods:(id)refObject class:(Class)testClass;
- (void)doTestPointerProperties:(id)refObject class:(Class)testClass;
- (void)doTestPointerMethods:(id)refObject class:(Class)testClass;
@end

#warning NSData implementation is not tested

@implementation Dubrovnik_Unit_Tests

- (void)setUp
{
    if (_setup) return;
    
    _setup = YES;
    _verbose = YES;
    
    [super setUp];
    
    // the unit test assembly exe is in the OCUnit test bundle resource folder.
    // if it is missing then make sure to build the dotNet unit test solution.
    // TODO: automate .NET component build
    NSString *assemblyName = @"Dubrovnik.UnitTests";
    NSString *assemblyFile = [[NSBundle bundleForClass:[self class]] pathForResource:assemblyName ofType:@"exe"];
    
    // validate the assembly
    if (![[NSFileManager defaultManager] fileExistsAtPath:assemblyFile]) {
        STAssertTrue(NO, @"Managed test assembly not found. Did you build it?");
        abort();
    }
    
    // use the default mono environment
    DBManagedEnvironment *monoEnv = [DBManagedEnvironment defaultEnvironment];

    // the environment delegate must be able to load assemblies on demand
    [monoEnv setDelegate:self];
         
    // open the assembly 
    monoAssembly = [monoEnv openAssembly:assemblyName path:assemblyFile];
    STAssertTrue(monoAssembly, @"Cannot open assembly : %@", assemblyFile);
    
    // invoke the assembly static main.
    // this prepares the application domain and validates that the assembly is loaded and functional.
    // the assembly will remain loaded and accessible once the assmbly invocation completes.
    // this operation should only be performed once on any given managed environment.
    int argc = 1;
    char *argv[] = {(char *)assemblyFile.UTF8String};
    int retval = [monoEnv invokeAssembly:monoAssembly prepareThreading:NO argCount:argc arguments:argv];
    STAssertTrue(retval == 0, @"Call to assembly entry point failed");
}

- (void)tearDown
{
    // Terminate the environment
    [[DBManagedEnvironment currentEnvironment] terminate];
    
    [super tearDown];
}

// mono_object_to_string is buggy
// https://github.com/mono/mono/pull/708/files
MonoString *
mono_object_to_string_ex (MonoObject *obj, MonoObject **exc)
{
	static MonoMethod *to_string = NULL;
	MonoMethod *method;
    void *target = obj;
    
	//g_assert (obj);
    
	if (!to_string)
		to_string = mono_class_get_method_from_name_flags (mono_get_object_class (), "ToString", 0, 0x0040 | 0x0006);
    
	method = mono_object_get_virtual_method (obj, to_string);
    
    // Unbox value type if needed
    if (mono_class_is_valuetype (mono_method_get_class (method))) {
        target = mono_object_unbox (obj);
    }
    
    return (MonoString *) mono_runtime_invoke (method, target, NULL, exc);
}

- (void)testDateRepresentation
{
    NSDate *dateNow = [NSDate date];
    MonoObject *monoDateTime = [dateNow monoDateTime];
    NSDate *dateFromMonoObject = [NSDate dateWithMonoDateTime:monoDateTime];
    
    // validate the NSDate representation
    STAssertTrue(fabs([dateFromMonoObject timeIntervalSinceDate:dateNow]) < 0.1, @"bad date");  // sanity check
    
    // validate the Mono representatiom
    int64_t ticks = DB_UNBOX_INT64(DBMonoObjectGetProperty(monoDateTime, "Ticks"));
    MonoString *monoString = mono_object_to_string_ex(monoDateTime, NULL);
    NSString *dateString = [NSString stringWithMonoString:monoString];
    NSLog(@"NSDate date = %@ Mono DateTime = %@ ticks = %lld", dateNow, dateString, ticks);
    
    //[DBManagedObject logMonoClassInfo:mono_object_get_class(monoObject)];
}

- (void)testNumberRepresentation
{
    // test
    DBNumber *n1 = [@((int)1) dbNumberFromIntValue];
    STAssertTrue(*(int *)[n1 valuePointer] == 1, DBUEqualityTestFailed);
    STAssertTrue([n1 valuePointer] == [n1 valuePointer], DBUEqualityTestFailed);
    STAssertTrue(*(int *)[n1 valuePointer] == *(int *)[n1 valuePointer], DBUEqualityTestFailed);
    
    // basic equality
    DBNumber *n2 = [DBNumber numberWithInt:1];
    STAssertTrue(*(int *)[n2 valuePointer] == 1, DBUEqualityTestFailed);
    STAssertTrue(*(int *)[n2 valuePointer] == *(int *)[n1 valuePointer], DBUEqualityTestFailed);
    
    // create int from MonoObject
    int intValue = 10289;
    DBNumber *nInt = [[DBTypeManager sharedManager] objectWithMonoObject:DB_BOX_INT32(intValue)];
    STAssertTrue(strcmp([nInt objCType], @encode(int)) == 0, DBUEqualityTestFailed);
    STAssertTrue(*(int *)[nInt valuePointer] == intValue, DBUEqualityTestFailed);
    
    // create long long from MonoObject
    long long longLongValue = LONG_LONG_MAX;
    DBNumber *nLongLong = [NSNumber objectWithMonoObject:DB_BOX_INT64(longLongValue)];
    STAssertTrue(strcmp([nLongLong objCType], @encode(long long)) == 0, DBUEqualityTestFailed);
    STAssertTrue(*(long long *)[nLongLong valuePointer] == longLongValue, DBUEqualityTestFailed);

    // create double from MonoObject
    double doubleValue = 13245456.;
    DBNumber *nDouble = [NSNumber numberWithMonoObject:DB_BOX_DOUBLE(doubleValue)];
    STAssertTrue(strcmp([nDouble objCType], @encode(double)) == 0, DBUEqualityTestFailed);
    STAssertTrue(*(double *)[nDouble valuePointer] == doubleValue, DBUEqualityTestFailed);
    
    // test DBNumber
    DBNumber *dn = [[DBNumber alloc] initWithInt:100];
    DBNumber *dn1 = [DBNumber numberWithInt:100];
    STAssertTrue([[dn stringValue] isEqualToString:@"100"], DBUEqualityTestFailed);
    
    // test NSNumber methods
    STAssertTrue([dn compare:@((int)100)] == NSOrderedSame, DBUEqualityTestFailed);
    STAssertTrue([dn compare:@((float)100)] == NSOrderedSame, DBUEqualityTestFailed);
    STAssertTrue([dn isEqualToNumber:dn1], DBUEqualityTestFailed);
    STAssertTrue([dn isEqualToNumber:@((int)100)], DBUEqualityTestFailed);
    STAssertNotNil([dn descriptionWithLocale:nil], DBUNotNilTestFailed);
    
    // test encoding
    STAssertTrue([@([[DBNumber numberWithBool:YES] monoObjCType]) isEqualToString:@(@encode(BOOL))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithChar:1] monoObjCType]) isEqualToString:@(@encode(char))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithUnsignedChar:1] monoObjCType]) isEqualToString:@(@encode(unsigned char))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithShort:1] monoObjCType]) isEqualToString:@(@encode(short))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithUnsignedShort:1] monoObjCType]) isEqualToString:@(@encode(unsigned short))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithInt:1] monoObjCType]) isEqualToString:@(@encode(int))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithUnsignedInt:1] monoObjCType]) isEqualToString:@(@encode(unsigned int))], DBUEqualityTestFailed);
    
    // long encoding wants to default  long long - some though neede perhaps
    STAssertTrue([@([[DBNumber numberWithLong:1] monoObjCType]) isEqualToString:@"l"], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithUnsignedLong:1] monoObjCType]) isEqualToString:@(@encode(unsigned long))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithLongLong:1] monoObjCType]) isEqualToString:@(@encode(long long))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithUnsignedLongLong:1] monoObjCType]) isEqualToString:@(@encode(unsigned long long))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithFloat:1] monoObjCType]) isEqualToString:@(@encode(float))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithDouble:1] monoObjCType]) isEqualToString:@(@encode(double))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithInteger:1] monoObjCType]) isEqualToString:@(@encode(NSInteger))], DBUEqualityTestFailed);
    STAssertTrue([@([[DBNumber numberWithUnsignedInteger:1] monoObjCType]) isEqualToString:@(@encode(NSUInteger))], DBUEqualityTestFailed);
    STAssertFalse([@([[DBNumber numberWithUnsignedInteger:1] monoObjCType]) isEqualToString:@(@encode(char))], DBUDesignedToFailTestPassed);
    
    // test setCompareEnforcesTypeMatch
    DBNumber *typeMatchIntN = [@55 dbNumberFromIntValue];
    DBNumber *typeMatchLongN = [@55 dbNumberFromLongValue];
    DBNumber *typeMatchFloatN = [@55 dbNumberFromFloatValue];
    
    DBNumber *typeMatchDoubleN = [@55 dbNumberFromDoubleValue];
    
    // test default behaviour with NSNumber
    STAssertTrue([typeMatchIntN isEqual:@55.], DBUEqualityTestFailed);
    STAssertTrue([typeMatchLongN isEqual:@55.], DBUEqualityTestFailed);
    STAssertTrue([typeMatchFloatN isEqual:@55.], DBUEqualityTestFailed);

    // test default behaviour with DBNumber
    STAssertTrue([typeMatchIntN isEqual:typeMatchDoubleN], DBUEqualityTestFailed);
    STAssertTrue([typeMatchLongN isEqual:typeMatchDoubleN], DBUEqualityTestFailed);
    STAssertTrue([typeMatchFloatN isEqual:typeMatchDoubleN], DBUEqualityTestFailed);
    
    // enforce comparison type match
    [typeMatchIntN setCompareEnforcesTypeMatch];
    [typeMatchLongN setCompareEnforcesTypeMatch];
    [typeMatchFloatN setCompareEnforcesTypeMatch];
    
    // NSumber behaviour should remain unchanged
    STAssertTrue([typeMatchIntN isEqual:@55.], DBUEqualityTestFailed);
    STAssertTrue([typeMatchLongN isEqual:@55.], DBUEqualityTestFailed);
    STAssertTrue([typeMatchFloatN isEqual:@55.], DBUEqualityTestFailed);
    
    // DBNumber should fail to match instance initialised with another type
    STAssertFalse([typeMatchIntN isEqual:typeMatchDoubleN], DBUInequalityTestFailed);
    STAssertFalse([typeMatchLongN isEqual:typeMatchDoubleN], DBUInequalityTestFailed);
    STAssertFalse([typeMatchFloatN isEqual:typeMatchDoubleN], DBUInequalityTestFailed);
    
    // DBNumber should match instance initialised with matching type
    STAssertTrue([typeMatchIntN isEqual:[@55 dbNumberFromIntValue]], DBUEqualityTestFailed);
    STAssertTrue([typeMatchLongN isEqual:[@55 dbNumberFromLongValue]], DBUEqualityTestFailed);
    STAssertTrue([typeMatchFloatN isEqual:[@55 dbNumberFromFloatValue]], DBUEqualityTestFailed);
    
}

- (void)testStringRepresentation
{
    NSString *string1 = @"I am the test string";
    DBString *string2 = [DBString objectWithMonoObject:[string1 monoString]];
    STAssertTrue([string1 isEqualToString:string2], DBUEqualityTestFailed);
    
    // create string from mono object
    NSString *string3 = [[DBTypeManager sharedManager] objectWithMonoObject:[string2 representedMonoObject]];
    STAssertTrue([string1 isEqualToString:string3], DBUEqualityTestFailed);
}

- (void)testReferenceClass
{
    NSUInteger initialInstanceCount = 0;
    NSUInteger finalInstanceCount = 0;

    
#if DB_RUN_MANUAL_CODE_TEST == 1
    
    m_runningAutoGenCodeTest = NO;
    
    // When adding support for new features it is best to
    // ensure that the manually coded reference class passes its tests first.
    // DB_RUN_AUTO_GENERATED_CODE_TEST can be #defined as 0
    //
    // Once the manually code class performs as required it can be used
    // as a guide for implementing the auto generated code
    
    NSLog(@"==============================================");
    NSLog(@"Testing manually generated reference object");
    NSLog(@"==============================================");
    
    initialInstanceCount = [DBManagedObject cachedInstanceCount];
    @autoreleasepool {
        
        // test reference class
        [self doTestReferenceClass:[DBUReferenceObject class]];
        
        // managed object allocation
        id managedObject = [[DBUReferenceObject alloc] init];
        (void)managedObject;
        
        // unmanaged object allocation
        NSString *unmanagedObject = [NSString stringWithFormat:@"%@", @"TEST"];
        (void)unmanagedObject;
        
    }
    
    // all managed objects instantiated withing the autorelease block above should have been dealloced
    [DBManagedObject logInstanceCache:DBLogInstanceCacheItems];
    finalInstanceCount = [DBManagedObject cachedInstanceCount];
    
    // we leak 1 due to a raised exception
    STAssertTrue(finalInstanceCount == initialInstanceCount + 1, DBUEqualityTestFailed);
    
#endif
    
#if DB_RUN_AUTO_GENERATED_CODE_TEST == 1
    
    m_runningAutoGenCodeTest = YES;
    
    NSLog(@"==============================================");
    NSLog(@"Testing auto generated reference object");
    NSLog(@"==============================================");
    
    initialInstanceCount = [DBManagedObject cachedInstanceCount];

    @autoreleasepool {
        [self doTestReferenceClass:[DUReferenceObject_ class]];
    }
    
    // all managed objects instantiated within the autorelease block above should have been dealloced
    [DBManagedObject logInstanceCache:DBLogInstanceCacheItems];
    finalInstanceCount = [DBManagedObject cachedInstanceCount];

    // we leak 1 due to a raised exception
    STAssertTrue(finalInstanceCount == initialInstanceCount + 1, DBUEqualityTestFailed);

    //
    // enumerations
    //
    STAssertTrue(Dubrovnik_UnitTests_IntEnum_val1 == [DBUIntEnum val1], DBUEqualityTestFailed);
    STAssertTrue(Dubrovnik_UnitTests_IntEnum_val2 == [DBUIntEnum val2], DBUEqualityTestFailed);
    STAssertTrue(Dubrovnik_UnitTests_IntEnum_val3 == [DBUIntEnum val3], DBUEqualityTestFailed);
    STAssertTrue(Dubrovnik_UnitTests_IntEnum_val4 == [DBUIntEnum val4], DBUEqualityTestFailed);

    STAssertTrue(Dubrovnik_UnitTests_LongEnum_val1 == eDBULongEnum_Val1, DBUEqualityTestFailed);
    STAssertTrue(Dubrovnik_UnitTests_LongEnum_val2 == eDBULongEnum_Val2, DBUEqualityTestFailed);
    STAssertTrue(Dubrovnik_UnitTests_LongEnum_val3 == eDBULongEnum_Val3, DBUEqualityTestFailed);
    STAssertTrue(Dubrovnik_UnitTests_LongEnum_val4 == eDBULongEnum_Val4, DBUEqualityTestFailed);
#endif
    
    // instance tests
    NSUInteger itemCount = 100;
    NSMutableArray *itemArray  = [NSMutableArray arrayWithCapacity:itemCount];
    
    initialInstanceCount = [DBManagedObject cachedInstanceCount];
    
    @autoreleasepool {

        // allocate objects
        for (NSUInteger i = 0; i < itemCount; i++) {
            DBManagedObject *managedObject = [DBManagedObject objectWithMonoObject:(MonoObject *)[DBUTestString monoString]];
            [itemArray addObject:managedObject];
        }
        
        [itemArray removeAllObjects];
        
        // drain the pool. all managed instances allocated in this autorelease bloack should have been released.
    }
    
    // instance count should be restored to initial value
    finalInstanceCount = [DBManagedObject cachedInstanceCount];
    STAssertTrue(finalInstanceCount == initialInstanceCount, DBUEqualityTestFailed);
    
}

- (id)doTestConstructorsWithclass:(Class)testClass
{
    
    //
    // default constructor
    //
    id refObject = [testClass new];
    
    STAssertNotNil(refObject, DBUObjectNotCreated);
    
    // log the class
    if (0) {
        [refObject logMonoClassInfo];
    }
    
    //
    // constructor overloads
    //
    NSString *ctorString = @"Constructor with one string argument";
    refObject = [testClass new_withValue:(id)ctorString];
    STAssertNotNil(refObject, DBUObjectNotCreated);
    STAssertTrue([[refObject stringProperty] isEqualToString:ctorString], DBUEqualityTestFailed);
    
    NSString *ctorString1 = @"Constructor with two ";
    NSString *ctorString2 = @"string arguments";
    refObject = [testClass new_withValue1:ctorString1 value2:ctorString2];
    STAssertNotNil(refObject, DBUObjectNotCreated);
    STAssertTrue([[refObject stringProperty] isEqualToString:[ctorString1 stringByAppendingString:ctorString2]], DBUEqualityTestFailed);
    
    return refObject;
}

- (void)doTestGenericConstructors:(Class)testClass
{
    // allocate list<System.Char> and populate
    /* TODO
    
    Test fails
     
    8 bit type name encoding collisions at work here
    char bool byte
     
    DBSystem_Collections_Generic_ListA1 *charList = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[DBNumChar(14), DBNumChar(89)]];
    [charList add:[DBNumChar(24) managedObject]];
    [charList add:[DBNumChar(67) managedObject]];
    STAssertTrue([[charList list] charAtIndex:2] == 24, DBUEqualityTestFailed);
    STAssertTrue([[charList list] charAtIndex:3] == 67, DBUEqualityTestFailed);
    STAssertTrue(charList.count == 4, DBUEqualityTestFailed);
     */
    
    // allocate list<System.Int16> and populate
    DBSystem_Collections_Generic_ListA1 *int16List = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[DBNumShort(12), DBNumShort(45)]];
    [int16List add:[DBNumShort(63) managedObject]];
    [int16List add:[DBNumShort(84) managedObject]];
    DBSystem_Collections_IList *int16IList = [int16List list];
    STAssertTrue([int16IList int16AtIndex:2] == 63, DBUEqualityTestFailed);
    STAssertTrue([int16IList int16AtIndex:3] == 84, DBUEqualityTestFailed);
    STAssertTrue(int16List.count == 4, DBUEqualityTestFailed);
    
    // allocate list<System.Int32> and populate
    DBSystem_Collections_Generic_ListA1 *int32List = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[DBNumInt(1), DBNumInt(2)]];
    [int32List add:[DBNumInt(3) managedObject]];
    [int32List add:[DBNumInt(4) managedObject]];
    STAssertTrue([[int32List list] int32AtIndex:2] == 3, DBUEqualityTestFailed);
    STAssertTrue([[int32List list] int32AtIndex:3] == 4, DBUEqualityTestFailed);
    STAssertTrue(int32List.count == 4, DBUEqualityTestFailed);
    
    // allocate list<System.Int64> and populate
    DBSystem_Collections_Generic_ListA1 *int64List = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[DBNumLongLong(10), DBNumLongLong(20)]];
    [int64List add:[DBNumLongLong(30) managedObject]];
    [int64List add:[DBNumLongLong(40) managedObject]];
    STAssertTrue([[int64List list] int64AtIndex:2] == 30, DBUEqualityTestFailed);
    STAssertTrue([[int64List list] int64AtIndex:3] == 40, DBUEqualityTestFailed);
    STAssertTrue(int64List.count == 4, DBUEqualityTestFailed);
    
    // allocate list<System.Single> and populate
#warning FAILING : embedded API calling type must be single not float!
    DBSystem_Collections_Generic_ListA1 *floatList = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[DBNumFloat(11), DBNumFloat(12)]];
    [floatList add:[DBNumFloat(13) managedObject]];
    [floatList add:[DBNumFloat(14) managedObject]];
    STAssertTrue([[floatList list] floatAtIndex:2] == 13, DBUEqualityTestFailed);
    STAssertTrue([[floatList list] floatAtIndex:3] == 14, DBUEqualityTestFailed);
    STAssertTrue(floatList.count == 4, DBUEqualityTestFailed);
    
    // allocate list<System.Double> and populate
    DBSystem_Collections_Generic_ListA1 *doubleList = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[DBNumDouble(21), DBNumDouble(22)]];
    [doubleList add:[DBNumDouble(23) managedObject]];
    [doubleList add:[DBNumDouble(24) managedObject]];
    STAssertTrue([[doubleList list] doubleAtIndex:2] == 23, DBUEqualityTestFailed);
    STAssertTrue([[doubleList list] doubleAtIndex:3] == 24, DBUEqualityTestFailed);
    STAssertTrue(doubleList.count == 4, DBUEqualityTestFailed);

    
    // allocate list<string> and populate
    NSString *item = @"item 0";
    DBSystem_Collections_Generic_ListA1 *stringList = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[item, @"item 1"]];
    [stringList add:[@"item 2" managedString]];
    [stringList add:[@"item 3" managedString]];
    STAssertTrue(stringList.count == 4, DBUEqualityTestFailed);
    
    // create array representation and validate
    NSArray *stringArray = [stringList array];
    STAssertTrue(stringArray.count == 4, DBUEqualityTestFailed);
    STAssertTrue([stringArray[0] isEqualToString:item], DBUEqualityTestFailed);
    STAssertTrue([stringArray[3] isEqualToString:@"item 3"], DBUEqualityTestFailed);
    
    // derive ListA1 from array
    NSArray *stringArray2 = @[@"1", @"10", @"100", @"1000",];
    DBSystem_Collections_Generic_ListA1 *numbersList = [stringArray2 dbscgListA1];
    STAssertTrue(numbersList.count == 4, DBUEqualityTestFailed);

    // allocate list<testClass> and populate
    id refObject1 = [testClass new];
    id refObject2 = [testClass new];
    DBSystem_Collections_Generic_ListA1 *refObjectList = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[refObject1, refObject2]];
    STAssertTrue(refObjectList.count == 2, DBUEqualityTestFailed);
    
    NSArray *refObjectArray = [refObjectList array];
    STAssertTrue(refObjectArray.count == 2, DBUEqualityTestFailed);
    STAssertTrue([refObjectArray[0] isEqual:refObject1], DBUEqualityTestFailed);
    STAssertTrue([refObjectArray[1] isEqual:refObject2], DBUEqualityTestFailed);
    
    // test exception when add invalid type to generic collection
    BOOL genericParameterExceptionRaised = NO;
    @try {
        // this will cause a leak
        [refObjectList add:[@"I should raise" managedObject]];
    }
    @catch (NSException *exception) {
        genericParameterExceptionRaised = YES;
    }
    @finally {
        STAssertTrue(genericParameterExceptionRaised, DBUExceptionTestFailed);
    }
}

- (void)doTestForEquality:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)

    // we should retrieve the same object here as we have class equality
    System_Object *object = [[testClass alloc] initWithMonoObject:[refObject monoObject]];
    STAssertTrue(refObject == object, DBUInequalityTestFailed);

    // we should retrieve another object here as we have class inequality
    System_Object *object1 = [[System_Object alloc] initWithMonoObject:[refObject monoObject]];
    
    STAssertTrue(refObject != object1, DBUInequalityTestFailed);
    STAssertTrue([refObject monoObject] == object1.monoObject, DBUEqualityTestFailed);
    STAssertTrue([refObject isEqual:object1], DBUEqualityTestFailed);
    
    // compare two separate instances of the same object
    System_Object *object2 = [self doTestConstructorsWithclass:testClass];
    System_Object *object3 = [self doTestConstructorsWithclass:testClass];
    STAssertTrue(object2 != object3, DBUInequalityTestFailed);
    STAssertTrue(object2.monoObject != object3.monoObject, DBUInequalityTestFailed);
    STAssertTrue([[(id)object2 stringProperty] isEqual:[(id)object3 stringProperty]], DBUEqualityTestFailed);
    STAssertTrue([object2 hash] == [object3 hash], DBUEqualityTestFailed);
    
    // inclusion of managed object equality testing is optional
    object2.testForManagedObjectEquality = YES;
    STAssertTrue([object2 isEqual:object3], DBUEqualityTestFailed);
    object2.testForManagedObjectEquality = NO;
    STAssertTrue(![object2 isEqual:object3], DBUEqualityTestFailed);
    
    // object equality is determined on the basis of the stringProperty.
    NSString *eProperty = [(id)object3 stringProperty];
    [(id)object3 setStringProperty:[NSString stringWithFormat:@"+%@", eProperty]];
    STAssertTrue([object2 hash] != [object3 hash], DBUInequalityTestFailed);
    STAssertTrue(![object2 isEqual:object3], DBUInequalityTestFailed);
}

- (void)doTestFields:(id)refObject class:(Class)testClass
{
   
    //
    // class fields
    //
    if (YES) {
        // class string field
        NSString *classStringField = [testClass classStringField];
        STAssertTrue([classStringField dbTestString:DBUTestString], DBUSubstringTestFailed);
        
        // string setter
        classStringField = [classStringField stringByAppendingString:@" : modified"];
        [testClass setClassStringField:classStringField];
        STAssertTrue([[testClass classStringField] isEqualToString:classStringField], DBUEqualityTestFailed);
        
        // class int field
        [testClass setClassIntField:1]; // set initially otherwise test fails when called again
        int32_t classIntField = [testClass classIntField];
        STAssertTrue(classIntField == 1, DBUEqualityTestFailed);
        
        // int setter
        classIntField = 10;
        [testClass setClassIntField:classIntField];
        STAssertTrue([testClass classIntField] == classIntField, DBUEqualityTestFailed);
    }
    
    // class date field
    if (YES) {
        NSDate *classDateField = [testClass classDateField];
        NSDate *testDate = [NSDate dateWithString:@"2014-04-06 00:00:00 +0000"];
        STAssertTrue([classDateField compare:testDate] == NSOrderedSame, DBUEqualityTestFailed);
    }
    
    //
    // instance fields
    //
    
    // string field
    NSString *stringField = [refObject stringField];
    STAssertNotNil(stringField, DBUObjectIsNil);
    
    // string setter
    stringField = [stringField stringByAppendingString:@" : modified"];
    [refObject setStringField:stringField];
    STAssertTrue([[refObject stringField] isEqualToString:stringField], DBUEqualityTestFailed);
    
    // int field
    int32_t intField = [refObject intField];
    STAssertTrue(intField == 1, DBUEqualityTestFailed);
    
    // int setter
    intField = 10;
    [refObject setIntField:intField];
    STAssertTrue([refObject intField] == intField, DBUEqualityTestFailed);
    
    // date field
    if (YES) {
        NSDate *dateField = [refObject dateField];
        STAssertNotNil(dateField, DBUObjectIsNil);
    }
}

- (void)doTestExtensionMethods:(id)refObject class:(Class)testClass
{
    #pragma unused(testClass)
    
    //
    // extension methods
    //
    if ([refObject respondsToSelector:@selector(extensionString)]) {
        NSString *extensionString = [refObject extensionString];
        STAssertNotNil(extensionString, DBUObjectIsNil);
    }
}

- (void)doTestMethods:(id)refObject class:(Class)testClass
{
    
#pragma unused(testClass)
    
    //
    // string methods + overloads
    //
    NSString *stringMethod = [refObject stringMethod];
    STAssertNotNil(stringMethod, DBUObjectIsNil);
    
    NSString *stringMethod1 = [refObject stringMethod_withS1:@"1"];
    STAssertNotNil(stringMethod1, DBUObjectIsNil);
    
    NSString *stringMethodWithInt = [refObject stringMethod_withN:100];
    STAssertTrue([stringMethodWithInt dbTestString:@"100"], DBUSubstringTestFailed);
    
    // These two tests account for the overload situation where the managed method
    // parameter names match. In this case additional type information is appended to
    // the interleaved parameters to create a unique signature.
    NSString *stringMethod2 = [refObject stringMethod_withS1String:@"1" s2String:@"2"];
    STAssertNotNil(stringMethod2, DBUObjectIsNil);
    
    MonoString *monoString = mono_string_new(mono_domain_get(), "2");
    DBManagedObject *stringObj = [DBManagedObject objectWithMonoObject:(MonoObject *)monoString];
    NSString *stringMethod3 = [refObject stringMethod_withS1String:@"1" s2Object:stringObj];
    STAssertNotNil(stringMethod3, DBUObjectIsNil);
    
    //
    // date methods
    //
    NSDate *dateMethod = [refObject dateMethod_withD1:[NSDate date]];
    STAssertNotNil(dateMethod, DBUObjectIsNil);
    
    //
    // mixed methods
    //
    
    NSString *mixedMethod1 = [refObject mixedMethod1_withIntarg:1111 longArg:-2222 floatArg:33.33f doubleArg:-44.44 dateArg:[NSDate date] stringArg:@"GeneralTest" refObjectArg:refObject];
    STAssertTrue([mixedMethod1 dbTestString:DBUTestString], DBUSubstringTestFailed);
    STAssertTrue([mixedMethod1 dbTestString:@"1111"], DBUSubstringTestFailed);
    STAssertTrue([mixedMethod1 dbTestString:@"-2222"], DBUSubstringTestFailed);
    STAssertTrue([mixedMethod1 dbTestString:@"33.33"], DBUSubstringTestFailed);
    STAssertTrue([mixedMethod1 dbTestString:@"-44.44"], DBUSubstringTestFailed);
    STAssertTrue([mixedMethod1 dbTestString:@"GeneralTest"], DBUSubstringTestFailed);
    NSLog(@"%@", mixedMethod1);
    
    // TODO: mixed methods to cover all value types
    
    //
    // int methods
    //
    int32_t intToDouble = 1;
    int32_t intDoubled = [refObject doubleIt_withXInt:intToDouble];
    STAssertTrue(intDoubled == 2 * intToDouble, DBUEqualityTestFailed);
    
#if DB_VALUETYPE_BY_REFERENCE_SUPPORT == 1
    // value type by ref
    [refObject doubleIt_withXIntRef:&intToDouble];
    STAssertTrue(intDoubled == intToDouble, DBUEqualityTestFailed);
#endif
    
    //
    // Generic argument methods
    //
    DBSystem_Collections_Generic_ListA1 *list = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[@"1", @"2"]];
    [refObject reverseList_withList:list];
    NSArray *revList = [list array];
    NSAssert([revList[0] isEqualToString:@"2"], DBUEqualityTestFailed);
    NSAssert([revList[1] isEqualToString:@"1"], DBUEqualityTestFailed);
 

    DBSystem_Collections_Generic_ListA1 *intList = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[DBNumInt(1), DBNumInt(2)]];
    [refObject reverseList_withList:intList];
    revList = [intList array];
    NSAssert([revList[0] isEqualTo:@(2)], DBUEqualityTestFailed);
    NSAssert([revList[1] isEqualTo:@(1)], DBUEqualityTestFailed);
    
    DBSystem_Collections_Generic_ListA1 *list1 = [DBSystem_Collections_Generic_ListA1 listWithObjects:@[@"1", @"2"]];
    NSString *addList = [refObject addIEnumerable_withList:(id)list1];
    NSAssert([addList isEqualToString:@"12"], DBUEqualityTestFailed);
    
    //
    // static methods
    //
    NSString *classDescription = (NSString *)[testClass classDescription];
    STAssertTrue([classDescription dbTestString:DBUTestString], DBUSubstringTestFailed);
}

- (void)doTestRefMethods:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
    
    NSString *s1 = DBUTestString;
    
    // pass string by reference
    [refObject stringMethodWithStringRef_withS1Ref:&s1];
    STAssertTrue([s1 isEqualToString:[DBUTestString stringByAppendingString:DBUTestString]], DBUEqualityTestFailed);
    
}

- (void)doTestPointerMethods:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
    
    // int 32 pointer
    int32_t x = 101, y = 202;
    int32_t int32Sum = [refObject sumAndSwitch_withIntPtrX:&x intPtrY:&y];
    STAssertTrue(int32Sum == x + y, DBUEqualityTestFailed);
    STAssertTrue(x == 202, DBUEqualityTestFailed);
    STAssertTrue(y == 101, DBUEqualityTestFailed);
    
    // int 64 pointer
    int64_t x64 = 202, y64 = 303;
    int64_t int64Sum = [refObject sumAndSwitch_withInt64PtrX:&x64 int64PtrY:&y64];
    STAssertTrue(int64Sum == x64 + y64, DBUEqualityTestFailed);
    STAssertTrue(x64 == 303, DBUEqualityTestFailed);
    STAssertTrue(y64 == 202, DBUEqualityTestFailed);
    
    // float pointer
    float xfloat = 404, yfloat = 505;
    float floatSum = [refObject sumAndSwitch_withFloatPtrX:&xfloat floatPtrY:&yfloat];
    STAssertTrue(floatSum == xfloat + yfloat, DBUEqualityTestFailed);
    STAssertTrue(xfloat == 505, DBUEqualityTestFailed);
    STAssertTrue(yfloat == 404, DBUEqualityTestFailed);
    
    // double pointer
    double xdouble = 606, ydouble = 772;
    double doubleSum = [refObject sumAndSwitch_withDoublePtrX:&xdouble doublePtrY:&ydouble];
    STAssertTrue(doubleSum == xdouble + ydouble, DBUEqualityTestFailed);
    STAssertTrue(xdouble == 772, DBUEqualityTestFailed);
    STAssertTrue(ydouble == 606, DBUEqualityTestFailed);
}


- (void)doTestArrayMethods:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
    
    // int 64 array
    NSArray *int64NSArray = @[@0L, @1L, @2L, @4L, @8L, @16L, @32L, @64L, @128L, @256L];
    DBSystem_Array *int64Array = [int64NSArray dbsArrayWithTypeName:DBType_System_Int64];
    int64_t int64Total = [refObject sum_withInt64Array:int64Array];
    STAssertTrue(int64Total == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 256, DBUEqualityTestFailed);
    
    // int 32 array
    NSArray *int32NSArray = @[@0, @1, @2, @4, @8, @16, @32, @64, @128, @257];
    DBSystem_Array *int32Array = [int32NSArray dbsArrayWithTypeName:DBType_System_Int32];
    int32_t int32Total = [refObject sum_withInt32Array:int32Array];
    STAssertTrue(int32Total == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 257, DBUEqualityTestFailed);
    
    // int 16 array
    NSArray *int16NSArray = @[@0, @1, @2, @4, @8, @16, @32, @64, @128, @255];
    DBSystem_Array *int16Array = [int16NSArray dbsArrayWithTypeName:DBType_System_Int16];
    int16_t int16Total = [refObject sum_withInt16Array:int16Array];
    STAssertTrue(int16Total == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 255, DBUEqualityTestFailed);
    
    // byte array
    NSArray *byteNSArray = @[@0, @1, @2, @4, @8, @16, @32, @64];
    DBSystem_Array *byteArray = [byteNSArray dbsArrayWithTypeName:DBType_System_Byte];
    int8_t byteTotal = [refObject sum_withByteArray:byteArray];
    STAssertTrue(byteTotal == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64, DBUEqualityTestFailed);
    
    // float array
    NSArray *floatNSArray = @[@0.0F, @1.0F, @2.0F, @4.0F, @8.0F, @16.0F, @32.0F, @64.0F, @128.0F, @258.0F];
    DBSystem_Array *floatArray = [floatNSArray dbsArrayWithTypeName:DBType_System_Single];
    float floatTotal = [refObject sum_withFloatArray:floatArray];
    STAssertTrue(floatTotal == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 258, DBUEqualityTestFailed);
    
    // double array
    NSArray *doubleNSArray = @[@0.0, @1.0, @2.0, @4.0, @8.0, @16.0F, @32.0, @64.0, @128.0, @259.0];
    DBSystem_Array *doubleArray = [doubleNSArray dbsArrayWithTypeName:DBType_System_Double];
    double doubleTotal = [refObject sum_withDoubleArray:doubleArray];
    STAssertTrue(doubleTotal == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 259, DBUEqualityTestFailed);
    
    // string array
    NSArray *stringNSArray = @[DBUTestString, @" 1", @" 2"];
    DBSystem_Array *stringArray = [stringNSArray dbsArrayWithTypeName:DBType_System_String];
    NSString *stringTotal = [refObject sum_withStringArray:stringArray];
    NSString *stringTest = [NSString stringWithFormat:@"%@ %@ %@", DBUTestString, @"1", @"2"];
    STAssertTrue([stringTotal isEqual:stringTest], DBUEqualityTestFailed);
}

- (void)doTestPointerProperties:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
    
    // string pointer
    NSString *stringPointer = @"It's okay to point at me like that.";
    [refObject setPointer:(__bridge void *)(stringPointer)];
    void * voidPtr = [refObject pointer];
    STAssertTrue(voidPtr == (__bridge void *)stringPointer, DBUEqualityTestFailed);
    
    // int32 pointer
    int32_t theInt = 10101;
    [refObject setInt32Pointer:&theInt];
    int32_t *int32Pointer = [refObject int32Pointer];
    STAssertTrue(*int32Pointer == theInt, DBUEqualityTestFailed);
}

- (void)doTestPropertyPersistence:(id)refObject class:(Class)testClass
{
#pragma unused(refObject, testClass)

    // repeated calls to a property should return the same object
    // unless the setter has been called or the property has been changed
    // by a managed code, most likely as a side effect
#warning TODO: test property persistence for generated code
    
}

- (void)doTestArrayProperties:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
    
    // string array
    DBSystem_Array *stringArray = [refObject stringArray];
    STAssertTrue([stringArray count] == 3, DBUCountTestFailed);
    
    NSMutableString *ms = [NSMutableString new];
    for (uint32_t i = 0; i < [stringArray count]; i++) {
        NSString * s = [stringArray objectAtIndex:i];
        [ms appendFormat:@"%@ ", s];
    }
    STAssertTrue([ms dbTestString:DBUTestString], DBUSubstringTestFailed);
    
    // derive string mono array from NSArray
    NSArray *stringNSArray = @[DBUTestString, @"1", @"2"];
    stringArray = [stringNSArray dbsArrayWithTypeName:DBType_System_String];
    [refObject setStringArray:stringArray];   // set
    stringArray = [refObject stringArray];    // get
    STAssertTrue([stringArray count] == 3, DBUCountTestFailed);
    ms = [NSMutableString new];
    for (uint32_t i = 0; i < [stringArray count]; i++) {
        NSString * s = [stringArray objectAtIndex:i];
        [ms appendFormat:@"%@ ", s];
    }
    STAssertTrue([ms dbTestString:DBUTestString], DBUSubstringTestFailed);
    
    // int64 array
    DBSystem_Array *int64Array = [refObject int64Array];
    STAssertTrue([int64Array count] == 10, DBUCountTestFailed);
    
    int64_t n = 0;
    for (uint32_t i = 0; i < [int64Array count]; i++) {
        n += [int64Array int64AtIndex:i];
    }
    STAssertTrue(n == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 256, DBUEqualityTestFailed);

    // mutate the property array
    [int64Array setInt64AtIndex:[int64Array count] - 1 value:1];
    [refObject setInt64Array:int64Array];   // set
    int64Array = [refObject int64Array];    // get
    STAssertTrue([int64Array count] == 10, DBUCountTestFailed);
    n = 0;
    for (uint32_t i = 0; i < [int64Array count]; i++) {
        n += [int64Array int64AtIndex:i];
    }
    STAssertTrue(n == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 1, DBUEqualityTestFailed);
    
    // derive 64 bit mono array from NSArray
    NSArray *int64NSArray = @[@0L, @1L, @2L, @4L, @8L, @16L, @32L, @64L, @128L, @128L];
    int64Array = [int64NSArray dbsArrayWithTypeName:DBType_System_Int64];
    [refObject setInt64Array:int64Array];   // set
    int64Array = [refObject int64Array];    // get
    STAssertTrue([int64Array count] == 10, DBUCountTestFailed);
    n = 0;
    for (uint32_t i = 0; i < [int64Array count]; i++) {
      n += [int64Array int64AtIndex:i];
    }
    STAssertTrue(n == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 128, DBUEqualityTestFailed);

    // int32 array
    DBSystem_Array *int32Array = [refObject int32Array];
    STAssertTrue([int32Array count] == 10, DBUCountTestFailed);
    
    n = 0;
    for (uint32_t i = 0; i < [int32Array count]; i++) {
        n += [int32Array int32AtIndex:i];
    }
    STAssertTrue(n == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 256, DBUEqualityTestFailed);

    // derive 32 bit mono array from NSArray
    NSArray *int32NSArray = @[@0, @1, @2, @4, @8, @16, @32, @64, @128, @120];
    int32Array = [int32NSArray dbsArrayWithTypeName:DBType_System_Int32];
    [refObject setInt32Array:int32Array];   // set
    int32Array = [refObject int32Array];    // get
    STAssertTrue([int32Array count] == 10, DBUCountTestFailed);
    n = 0;
    for (uint32_t i = 0; i < [int32Array count]; i++) {
        n += [int32Array int32AtIndex:i];
    }
    STAssertTrue(n == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 120, DBUEqualityTestFailed);
    
    // int16 array
    DBSystem_Array *int16Array = [refObject int16Array];
    STAssertTrue([int16Array count] == 10, DBUCountTestFailed);
    
    n = 0;
    for (uint32_t i = 0; i < [int16Array count]; i++) {
        n += [int16Array int16AtIndex:i];
    }
    STAssertTrue(n == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 256, DBUEqualityTestFailed);
    
    // float array
    DBSystem_Array *floatArray = [refObject floatArray];
    STAssertTrue([floatArray count] == 10, DBUCountTestFailed);
    
    float f = 0;
    for (uint32_t i = 0; i < [floatArray count]; i++) {
        f += [floatArray floatAtIndex:i];
    }
    STAssertTrue(f == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 256, DBUEqualityTestFailed);

    // derive float mono array from NSArray
    NSArray *floatNSArray = @[@0.0F, @1.0F, @2.0F, @4.0F, @8.0F, @16.0F, @32.0F, @64.0F, @128.0F, @116.0F];
    floatArray = [floatNSArray dbsArrayWithTypeName:DBType_System_Single];
    [refObject setFloatArray:floatArray];   // set
    floatArray = [refObject floatArray];    // get
    STAssertTrue([floatArray count] == 10, DBUCountTestFailed);
    n = 0;
    for (uint32_t i = 0; i < [floatArray count]; i++) {
        n += [floatArray floatAtIndex:i];
    }
    STAssertTrue(n == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 116, DBUEqualityTestFailed);
    
    // double array
    DBSystem_Array *doubleArray = [refObject doubleArray];
    STAssertTrue([doubleArray count] == 10, DBUCountTestFailed);
    
    double d = 0;
    for (uint32_t i = 0; i < [doubleArray count]; i++) {
        d += [doubleArray doubleAtIndex:i];
    }
    STAssertTrue(d == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 256, DBUEqualityTestFailed);

    // derive double mono array from NSArray
    NSArray *doubleNSArray = @[@0.0, @1.0, @2.0, @4.0, @8.0, @16.0, @32.0, @64.0, @128.0, @110.0];
    doubleArray = [doubleNSArray dbsArrayWithTypeName:DBType_System_Double];
    [refObject setDoubleArray:doubleArray];   // set
    doubleArray = [refObject doubleArray];    // get
    STAssertTrue([doubleArray count] == 10, DBUCountTestFailed);
    n = 0;
    for (uint32_t i = 0; i < [doubleArray count]; i++) {
        n += [doubleArray doubleAtIndex:i];
    }
    STAssertTrue(n == 0 + 1 + 2 + 4 + 8 + 16 + 32 + 64 + 128 + 110, DBUEqualityTestFailed);
    
    // bool array
    DBSystem_Array *boolArray = [refObject boolArray];
    STAssertTrue([boolArray count] == 10, DBUCountTestFailed);
    
    for (uint32_t i = 0; i < [boolArray count]; i++) {
        bool b = [boolArray boolAtIndex:i];
        STAssertTrue(b == (i % 2 == 0 ? YES : NO), DBUEqualityTestFailed);
    }
}

- (void)doTestNotifyingProperties:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
    
    [refObject setNotifyingProperty1:DBUTestString];
    [refObject setNotifyingProperty2:DBUTestString];
    
}

- (void)doTestGenericMethods:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
}

- (void)doTestGenericProperties:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
    
#warning TODO: add tests for all possible List<T> types
    
    // List<string>
    DBSystem_Collections_Generic_ListA1 *listOfStrings = [refObject stringList];
    NSArray *arrayOfStrings = [listOfStrings array];
    STAssertTrue([arrayOfStrings[0] dbTestString:DBUTestString], DBUSubstringTestFailed);
    STAssertTrue([arrayOfStrings[0] dbTestString:@" 1"], DBUSubstringTestFailed);
    STAssertTrue([arrayOfStrings[1] dbTestString:DBUTestString], DBUSubstringTestFailed);
    STAssertTrue([arrayOfStrings[1] dbTestString:@" 2"], DBUSubstringTestFailed);
    
    // List<int>
    DBSystem_Collections_Generic_ListA1 *listOfInts = [refObject intList];
    NSArray *arrayOfInts = [listOfInts array];
    STAssertTrue([arrayOfInts count] == 3, DBUCountTestFailed);
    STAssertTrue([arrayOfInts[0] intValue] == 1, DBUEqualityTestFailed);
    STAssertTrue([arrayOfInts[1] intValue] == -10, DBUEqualityTestFailed);
    STAssertTrue([arrayOfInts[2] intValue] == 100, DBUEqualityTestFailed);

    // List<uint>
    DBSystem_Collections_Generic_ListA1 *listOfUInts = [refObject uIntList];
    NSArray *arrayOfUInts = [listOfUInts array];
    STAssertTrue([arrayOfUInts count] == 2, DBUCountTestFailed);
    STAssertTrue([arrayOfUInts[0] unsignedIntValue] == 2, DBUEqualityTestFailed);
    STAssertTrue([arrayOfUInts[1] unsignedIntValue] == 20, DBUEqualityTestFailed);

    // List<float>
    DBSystem_Collections_Generic_ListA1 *listOfFloats = [refObject floatList];
    NSArray *arrayOfFloats = [listOfFloats array];
    STAssertTrue([arrayOfFloats count] == 3, DBUCountTestFailed);
    STAssertTrue([arrayOfFloats[0] floatValue] == 1., DBUEqualityTestFailed);
    STAssertTrue([arrayOfFloats[1] floatValue] == 2., DBUEqualityTestFailed);
    STAssertTrue([arrayOfFloats[2] floatValue] == 3., DBUEqualityTestFailed);
    
    // List<double>
    DBSystem_Collections_Generic_ListA1 *listOfDoubles = [refObject doubleList];
    NSArray *arrayOfDoubles = [listOfDoubles array];
    STAssertTrue([arrayOfDoubles count] == 2, DBUCountTestFailed);
    STAssertTrue([arrayOfDoubles[0] doubleValue] == 11., DBUEqualityTestFailed);
    STAssertTrue([arrayOfDoubles[1] doubleValue] == 22., DBUEqualityTestFailed);
    
    //============================
    // Dictionary<string,string>
    //=============================
    DBSystem_Collections_Generic_DictionaryA2 *stringStringDictA2 = [refObject stringStringDictionary];
    
    // test all keys
    NSArray *stringStringDictKeys = [stringStringDictA2 allKeys];
    STAssertTrue([stringStringDictKeys count] == 2, DBUCountTestFailed);
    STAssertTrue([stringStringDictKeys containsObject:@"keyForString1"], DBUObjectNotFound);
    STAssertTrue([stringStringDictKeys containsObject:@"keyForString2"], DBUObjectNotFound);
    
    // test all values
    NSArray *stringStringDictValues = [stringStringDictA2 allValues];
    STAssertTrue([stringStringDictValues count] == 2, DBUCountTestFailed);
    STAssertTrue([stringStringDictValues containsObject:@"Dubrovnik.UnitTests 1"], DBUObjectNotFound);
    STAssertTrue([stringStringDictValues containsObject:@"Dubrovnik.UnitTests 2"], DBUObjectNotFound);
    
    // test keys and values
    id key = stringStringDictKeys[0];
    id value = [stringStringDictA2 objectForKey:key];
    STAssertTrue([value dbTestString:@"1"], DBUSubstringTestFailed);
    key = stringStringDictKeys[1];
    STAssertTrue([[stringStringDictA2 objectForKey:key] dbTestString:@"2"], DBUSubstringTestFailed);
    
    // test NSDictionary representation
    NSDictionary *stringStringDict = [stringStringDictA2 dictionary];
    STAssertTrue([stringStringDict[@"keyForString1"] dbTestString:@"Dubrovnik.UnitTests 1"], DBUSubstringTestFailed);
    STAssertTrue([stringStringDict[@"keyForString2"] dbTestString:@"Dubrovnik.UnitTests 2"], DBUSubstringTestFailed);

    //============================
    // Dictionary<int,int>
    //=============================
    DBSystem_Collections_Generic_DictionaryA2 *intIntDictA2 = [refObject intIntDictionary];
    
    // test all keys
    NSArray *intIntDictKeys = [intIntDictA2 allKeys];
    STAssertTrue([intIntDictKeys count] == 2, DBUCountTestFailed);
    STAssertTrue([intIntDictKeys containsObject:@1], DBUObjectNotFound);
    STAssertTrue([intIntDictKeys containsObject:@3], DBUObjectNotFound);

    // test all values
    NSArray *intIntDictValues = [intIntDictA2 allValues];
    STAssertTrue([intIntDictValues count] == 2, DBUCountTestFailed);
    STAssertTrue([intIntDictValues containsObject:@2], DBUObjectNotFound);
    STAssertTrue([intIntDictValues containsObject:@6], DBUObjectNotFound);

    // test keys and values
    key = intIntDictKeys[0];
    value = [intIntDictA2 objectForKey:key];
    STAssertTrue([value intValue] == 2, DBUEqualityTestFailed);

    // key is a DBManagedObject containing a boxed int
    int intKey = [intIntDictKeys[1] intValue];
    value = [intIntDictA2 objectForKey:[DBManagedObject objectWithMonoObject:DB_BOX_INT32(intKey)]];
    STAssertTrue([value intValue] == 6, DBUEqualityTestFailed);
    
    // key is a DBNumber representing an int
    value = [intIntDictA2 objectForKey:[DBNumber numberWithInt:intKey]];
    STAssertTrue([value intValue] == 6, DBUEqualityTestFailed);
    
    // object for key requires a type that represnts a mono type
    BOOL numberTypeExceptionRaised = NO;
    @try {
        value = [intIntDictA2 objectForKey:@(intKey)];
    }
    @catch (NSException *e) {
        numberTypeExceptionRaised = YES;
    }
    @finally {
        STAssertTrue(numberTypeExceptionRaised, DBUExceptionTestFailed);
    }

    // key is a literal number representing an int
    NSNumber *literalNumberKey = [@((int)intKey) dbNumberFromIntValue];
    const char *typeEncoding = [literalNumberKey objCType];
    STAssertTrue(strcmp(typeEncoding, @encode(int)) == 0, DBUEqualityTestFailed);
    value = [intIntDictA2 objectForKey:literalNumberKey];
    STAssertTrue([value intValue] == 6, DBUEqualityTestFailed);
    
    // test NSDictionary representation
    NSDictionary *intIntDict = [intIntDictA2 dictionary];
    STAssertTrue([intIntDict[@(1)] intValue] == 2, DBUEqualityTestFailed);
    STAssertTrue([intIntDict[@(3)] intValue] == 6, DBUEqualityTestFailed);

    //============================
    // Dictionary<string,object>
    //=============================
    DBSystem_Collections_Generic_DictionaryA2 *stringObjectDictA2 = [refObject stringObjectDictionary];
    
    // test all keys
    NSArray *stringObjectDictKeys = [stringObjectDictA2 allKeys];
    STAssertTrue([stringObjectDictKeys count] == 6, DBUCountTestFailed);
    STAssertTrue([stringObjectDictKeys containsObject:@"keyForString"], DBUObjectNotFound);
    STAssertTrue([stringObjectDictKeys containsObject:@"keyForInteger"], DBUObjectNotFound);
    STAssertTrue([stringObjectDictKeys containsObject:@"keyForFloat"], DBUObjectNotFound);
    STAssertTrue([stringObjectDictKeys containsObject:@"keyForListA1"], DBUObjectNotFound);
    STAssertTrue([stringObjectDictKeys containsObject:@"keyForDictionaryA2"], DBUObjectNotFound);
    STAssertTrue([stringObjectDictKeys containsObject:@"keyForStringArray"], DBUObjectNotFound);
    
    // test all values
    NSArray *stringObjectDictValues = [stringObjectDictA2 allValues];
    STAssertTrue([stringObjectDictValues count] == 6, DBUCountTestFailed);
    
    STAssertTrue([stringObjectDictValues containsObject:@"Dubrovnik.UnitTests"], DBUObjectNotFound);
    STAssertTrue([stringObjectDictValues containsObject:@100], DBUObjectNotFound);
    STAssertTrue([stringObjectDictValues containsObject:@1001.], DBUObjectNotFound);

    // test all DictionaryA2 values for keys
    value = [stringObjectDictA2 objectForKey:@"keyForString"];
    STAssertTrue([value dbTestString:@"Dubrovnik.UnitTests"], DBUObjectNotFound);

    value = [stringObjectDictA2 objectForKey:@"keyForInteger"];
    STAssertTrue([value intValue] == 100, DBUObjectNotFound);

    value = [stringObjectDictA2 objectForKey:@"keyForFloat"];
    STAssertTrue([value intValue] == 1001., DBUObjectNotFound);

    // ListA1 object
    value = [stringObjectDictA2 objectForKey:@"keyForListA1"];
    STAssertTrue([value isKindOfClass:[DBSystem_Collections_Generic_ListA1 class]], DBUClassTestFailed);

    NSArray *keyListA1Array = [(DBSystem_Collections_Generic_ListA1 *)value array];
    STAssertTrue([keyListA1Array containsObject:@"Dubrovnik1"], DBUObjectNotFound);
    STAssertTrue([keyListA1Array containsObject:@"Dubrovnik2"], DBUObjectNotFound);

    // DictionaryA2 object
    value = [stringObjectDictA2 objectForKey:@"keyForDictionaryA2"];
    STAssertTrue([value isKindOfClass:[DBSystem_Collections_Generic_DictionaryA2 class]], DBUClassTestFailed);

    STAssertTrue([(DBSystem_Collections_Generic_DictionaryA2 *)value objectForKey:@"subKey1"], DBUObjectNotFound);
    STAssertTrue([(DBSystem_Collections_Generic_DictionaryA2 *)value objectForKey:@"subKey2"], DBUObjectNotFound);
    STAssertFalse([(DBSystem_Collections_Generic_DictionaryA2 *)value objectForKey:@"subKeyN"], DBUDesignedToFailTestPassed);

    //  new string[] object
    DBSystem_Array *subItemDBArray = [stringObjectDictA2 objectForKey:@"keyForStringArray"];
    NSArray *subItemArray = [subItemDBArray array];
    STAssertTrue([subItemArray containsObject:@"Dubrovnik SubItem1"], DBUObjectNotFound);
    STAssertTrue([subItemArray containsObject:@"Dubrovnik SubItem2"], DBUObjectNotFound);
    STAssertFalse([subItemArray containsObject:@"Dubrovnik SubItem3"], DBUDesignedToFailTestPassed);
    
    //============================
    // Dictionary<object,object>
    //=============================
    DBSystem_Collections_Generic_DictionaryA2 *objectObjectDictA2 = [refObject objectObjectDictionary];

    // test all keys
    NSArray *objectObjectDictKeys = [objectObjectDictA2 allKeys];
    STAssertTrue([objectObjectDictKeys count] == 5, DBUCountTestFailed);

    STAssertTrue([objectObjectDictKeys containsObject:@"keyForString"], DBUObjectNotFound);
    STAssertTrue([objectObjectDictKeys containsObject:@"keyForInteger"], DBUObjectNotFound);
    STAssertTrue([objectObjectDictKeys containsObject:@"keyForFloat"], DBUObjectNotFound);
    STAssertTrue([objectObjectDictKeys containsObject:@1], DBUObjectNotFound);
    STAssertTrue([objectObjectDictKeys containsObject:[DBNumber numberWithFloat:1]], DBUObjectNotFound);
    
    // test all values
    NSArray *objectObjectDictValues = [objectObjectDictA2 allValues];
    STAssertTrue([objectObjectDictValues count] == 5, DBUCountTestFailed);
 
    STAssertTrue([objectObjectDictValues containsObject:@"Dubrovnik.UnitTests"], DBUObjectNotFound);
    STAssertTrue([objectObjectDictValues containsObject:@100], DBUObjectNotFound);
    STAssertTrue([objectObjectDictValues containsObject:@1001.F], DBUObjectNotFound);
    STAssertTrue([objectObjectDictValues containsObject:@8], DBUObjectNotFound);
    STAssertTrue([objectObjectDictValues containsObject:@"Dubrovnik.UnitTests 2"], DBUObjectNotFound);

    // test all DictionaryA2 values for keys
    value = [objectObjectDictA2 objectForKey:@"keyForString"];
    STAssertTrue(value && [value isKindOfClass:[NSString class]] && [value isEqual:@"Dubrovnik.UnitTests"], DBUObjectNotFound);
    
    value = [objectObjectDictA2 objectForKey:@"keyForInteger"];
    STAssertTrue(value && [value isKindOfClass:[NSNumber class]] && [value isEqual:@100], DBUObjectNotFound);
    
    value = [objectObjectDictA2 objectForKey:@"keyForFloat"];
    STAssertTrue(value && [value isKindOfClass:[NSNumber class]] && [value isEqual:@1001.F], DBUObjectNotFound);
    
    value = [objectObjectDictA2 objectForKey:[@1 dbNumberFromIntValue]];   // key must be a managed number
    STAssertTrue(value && [value isKindOfClass:[NSNumber class]] && [value isEqual:@8], DBUObjectNotFound);

    value = [objectObjectDictA2 objectForKey:[@1 dbNumberFromFloatValue]]; // key must be a managed number
    STAssertTrue(value && [value isKindOfClass:[NSString class]] && [value isEqual:@"Dubrovnik.UnitTests 2"], DBUObjectNotFound);

    // test all NSDictionary values for keys
    NSDictionary *objectObjectDict = [objectObjectDictA2 dictionary];
    STAssertTrue([objectObjectDict count] == 5, DBUCountTestFailed);
    
    value = [objectObjectDict objectForKey:@"keyForString"];
    STAssertTrue(value && [value isKindOfClass:[NSString class]] && [value isEqual:@"Dubrovnik.UnitTests"], DBUObjectNotFound);
    
    value = [objectObjectDict objectForKey:@"keyForInteger"];
    STAssertTrue(value && [value isKindOfClass:[NSNumber class]] && [value isEqual:@100], DBUObjectNotFound);
    
    value = [objectObjectDict objectForKey:@"keyForFloat"];
    STAssertTrue(value && [value isKindOfClass:[NSNumber class]] && [value isEqual:@1001.F], DBUObjectNotFound);

    // these are subtle tests that indicate that Dictionary<K,V> keys are type sensitive.
    // managed int 1 and float 1 are different keys.
    // to access a key which has a type duplicate in an NSDictionary use a DBNumber as shown.
    
    // NSNumber access will fail
    value = [objectObjectDict objectForKey:@1];
    STAssertNil(value, DBUNilTestFailed);

    DBNumber *managedKey = [@1 dbNumberFromIntValue];
    [managedKey setCompareEnforcesTypeMatch];
    
    value = [objectObjectDict objectForKey:managedKey];
    STAssertTrue(value && [value isKindOfClass:[NSNumber class]] && [value isEqual:@8], DBUObjectNotFound);

    managedKey = [@1 dbNumberFromFloatValue];
    [managedKey setCompareEnforcesTypeMatch];

    value = [objectObjectDict objectForKey:managedKey]; // key must be a managed number
    STAssertTrue(value && [value isKindOfClass:[NSString class]] && [value isEqual:@"Dubrovnik.UnitTests 2"], DBUObjectNotFound);

    
    //=======================================
    // Dictionary<int,Dictionary<int,string>>
    //=======================================
    DBSystem_Collections_Generic_DictionaryA2 *intIntStringDictA2 = [refObject intIntStringDictionaryDictionary];
    
    // test all keys
    NSArray *intIntStringDictDictKeys = [intIntStringDictA2 allKeys];
    STAssertTrue([intIntStringDictDictKeys count] == 2, DBUCountTestFailed);
    STAssertTrue([intIntStringDictDictKeys containsObject:@0], DBUObjectNotFound);
    STAssertTrue([intIntStringDictDictKeys containsObject:@1], DBUObjectNotFound);

    // sub dict 1
    DBSystem_Collections_Generic_DictionaryA2 *subDict1 = [intIntStringDictA2 objectForKey:[@0 dbNumberFromIntValue]];
    
    // test all keys
    NSArray *subDict1Keys = [subDict1 allKeys];
    STAssertTrue([subDict1Keys count] == 2, DBUCountTestFailed);
    STAssertTrue([subDict1Keys containsObject:@0], DBUObjectNotFound);
    STAssertTrue([subDict1Keys containsObject:@1], DBUObjectNotFound);

    // test all values
    NSString *stringValue = [subDict1 objectForKey:[@0 dbNumberFromIntValue]];
    STAssertTrue([stringValue isEqualToString:@"string0"], DBUEqualityTestFailed);

    stringValue = [subDict1 objectForKey:[@1 dbNumberFromIntValue]];
    STAssertTrue([stringValue isEqualToString:@"string1"], DBUEqualityTestFailed);
    
    // sub dict 2
    DBSystem_Collections_Generic_DictionaryA2 *subDict2 = [intIntStringDictA2 objectForKey:[@1 dbNumberFromIntValue]];
    
    // test all keys
    NSArray *subDict2Keys = [subDict2 allKeys];
    STAssertTrue([subDict2Keys count] == 2, DBUCountTestFailed);
    STAssertTrue([subDict2Keys containsObject:@10], DBUObjectNotFound);
    STAssertTrue([subDict2Keys containsObject:@11], DBUObjectNotFound);

    // test all values
    stringValue = [subDict2 objectForKey:[@10 dbNumberFromIntValue]];
    STAssertTrue([stringValue isEqualToString:@"string10"], DBUEqualityTestFailed);
    
    stringValue = [subDict2 objectForKey:[@11 dbNumberFromIntValue]];
    STAssertTrue([stringValue isEqualToString:@"string11"], DBUEqualityTestFailed);
    
    //============================
    // System.Nullable<T>
    //=============================
    System_NullableA1 *intNullable = [refObject intNullable];
    STAssertTrue(intNullable != nil, DBUNotNilTestFailed);
    STAssertTrue([[intNullable numberValue] intValue] == 1, DBUEqualityTestFailed);
    
    
    // set value to null
    System_NullableA1 *intNullable2 = [System_NullableA1 newNullableFromObject:nil withTypeArgumentName:@"int32_t"];
    [refObject setIntNullable:intNullable2];
    intNullable = [refObject intNullable];
    STAssertTrue(intNullable == nil, DBUNilTestFailed);
    
    
    // get float null
    System_NullableA1 *floatNullable = [refObject floatNullable];
    STAssertTrue(floatNullable == nil, DBUNilTestFailed);

    System_NullableA1 *floatNullable2 = [System_NullableA1 newNullableFromObject:@((float)5) withTypeArgumentName:@"float"];
    [refObject setFloatNullable:floatNullable2];
    floatNullable = [refObject floatNullable];
    STAssertTrue(floatNullable != nil, DBUNotNilTestFailed);
    STAssertTrue([[floatNullable numberValue] floatValue] == 5, DBUEqualityTestFailed);
    
    //=========================================================
    // Generic reference object
    // Dubrovnik.UnitTests.GenericReferenceObject<T, U>"
    // This generic type is defined by the unit test assembly
    //=========================================================
    // T string
    // U string
    DBUGenericReferenceObjectA2 *refObjectA2 = [refObject stringStringGenericReferenceObject];
    
    // properties
    id gp1 = refObjectA2.genericPropertyWithTypeParameterT;
    STAssertTrue([gp1 isEqual:@"I am of type T == string"], DBUEqualityTestFailed);
    
    id gp2 = refObjectA2.genericPropertyWithTypeParameterU;
    STAssertTrue([gp2 isEqual:@"I am of type U == string"], DBUEqualityTestFailed);
    
    // methods
    System_String *ms1 = [@"I am of type T == string" managedString];
    System_String *ms2 = [@"I am of type U == string" managedString];
    id gm1 = [refObjectA2 genericMethodReturningParameterTypeT_withParameterT:ms1 parameterU:ms2];
    STAssertTrue([gm1 isEqual:@"I am of type T == string"], DBUEqualityTestFailed);

    id gm2 = [refObjectA2 genericMethodReturningParameterTypeU_withParameterT:ms1 parameterU:ms2];
    STAssertTrue([gm2 isEqual:@"I am of type U == string"], DBUEqualityTestFailed);
    
}

- (void)doTestArrayListRepresentation:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
    // string array list
    DBSystem_Collections_ArrayList *stringArrayList = [refObject stringArrayList];
    STAssertTrue([stringArrayList count] == 3, DBUCountTestFailed);
    
    NSMutableString *ms = [NSMutableString new];
    for (uint32_t i = 0; i < [stringArrayList count]; i++) {
        NSString * s = [stringArrayList objectAtIndex:i];
        [ms appendFormat:@"%@ ", s];
    }
    STAssertTrue([ms dbTestString:DBUTestString], DBUSubstringTestFailed);
}

- (void)doTestStructRepresentation:(id)refObject class:(Class)testClass
{
    
#pragma unused(testClass)

    //
    // Managed struct handling
    //
    id refStruct = [refObject referenceStructMethod_withS1:@"ReferenceStruct"];
    STAssertNotNil(refStruct, DBUObjectIsNil);
    
    NSString *refStructStringProperty = [refStruct stringProperty];
    STAssertTrue([refStructStringProperty dbTestString:DBUTestString], DBUSubstringTestFailed);
    
    NSString *refStructStringMethod = [refStruct stringMethod_withS1:@"ReferenceStruct"];
    STAssertTrue([refStructStringMethod dbTestString:DBUTestString], DBUSubstringTestFailed);
    
    // log the struct
    if (0) {
        [refStruct logMonoClassInfo];
    }
}

- (void)doTestInterfaceRepresentation:(id)refObject class:(Class)testClass
{

    #pragma unused(testClass)
    
    //
    // managed interface property
    //

    // get managed interface object
    id minimRefObject = [refObject minimalReferenceObject];
    
    // query interface method
    NSString * minimalRefString = [minimRefObject stringMethod_withS1:@"1" n:2];
    STAssertTrue([minimalRefString dbTestString:DBUTestString], DBUSubstringTestFailed);
    
    // query explicit interface implementation properties.
    // we should be able to access the same property with three different return types via the
    // original object and two explicit interface references.
    
    // BOOL
    BOOL boolValue = [(DBUReferenceObject *)refObject exIntTestProperty];   // cast need to silence type warning
    NSAssert(boolValue == YES, DBUEqualityTestFailed);
    
    // int
    Dubrovnik_UnitTests_IReferenceObject1 *refObject1 = [refObject referenceObject1];
    [refObject1 setExIntTestProperty:89467];
    int32_t intValue = [refObject1 exIntTestProperty];
    
    NSAssert(intValue == 89467, DBUEqualityTestFailed);
    
    // float
    Dubrovnik_UnitTests_IReferenceObject2 *refObject2 = [refObject referenceObject2];
    [refObject2 setExIntTestProperty:20202.f];
    float floatValue = [refObject2 exIntTestProperty];

    NSAssert(floatValue == 20202.f, DBUEqualityTestFailed);
}

- (void)doTestProperties:(id)refObject class:(Class)testClass
{
    //
    // class properties
    //
    NSString *classStringProperty = [testClass classStringProperty];
    STAssertTrue([classStringProperty isEqualToString:@"Dubrovnik.UnitTests static property"], DBUEqualityTestFailed);

    NSDate *classDateProperty = [testClass classDateProperty];
    NSDate *testDate = [NSDate dateWithString:@"2014-04-06 00:00:00 +0000"];
    STAssertTrue([classDateProperty compare:testDate] == NSOrderedSame, DBUEqualityTestFailed);

    //
    // string property
    //
    NSString *stringProperty = [refObject stringProperty];
    STAssertNotNil(stringProperty, DBUObjectIsNil);
    
    // setter
    stringProperty = [stringProperty stringByAppendingString:@" : modified"];
    [refObject setStringProperty:stringProperty];
    STAssertTrue([[refObject stringProperty] isEqualToString:stringProperty], DBUEqualityTestFailed);
    
    //
    // int32 property
    //
    int32_t int32 = [refObject int32Number];
    STAssertTrue(int32 != 0, DBUEqualityTestFailed);
    
    // setter
    int32 = 320;
    [refObject setInt32Number:int32];
    STAssertTrue([refObject int32Number] == int32, DBUEqualityTestFailed);
    
    //
    // int64 property
    //
    int64_t int64 = [refObject int64Number];
    STAssertTrue(int64 != 0, DBUEqualityTestFailed);
    
    // setter
    int64 = 640;
    [refObject setInt64Number:int64];
    STAssertTrue([refObject int64Number] == int64, DBUEqualityTestFailed);
    
    //
    // object property
    //
    id refObject2 = [[testClass alloc] init];
    STAssertNotNil(refObject2, DBUObjectNotCreated);
    
    NSString *refObject2StringProperty = @"This is general test 2";
    [refObject2 setStringProperty:refObject2StringProperty];
    [refObject setReferenceObjectRelative:refObject2];
    STAssertTrue([[[refObject referenceObjectRelative] stringProperty] isEqualToString:refObject2StringProperty], DBUEqualityTestFailed);
    
    //
    // date property
    //
    
    NSDate *dateNow = [refObject date];
    STAssertNotNil(dateNow, DBUObjectIsNil);
    STAssertTrue([[NSDate date] timeIntervalSinceDate:dateNow] < 60, DBULessThanTestFailed);    // Why 60? In case we we trigger a breakpoint, take a peek  and then continue.
    
    [refObject setDate:dateNow];
    
    // setter
    NSDate *dateFuture = [NSDate dateWithTimeIntervalSinceNow:60*60*24];
    [refObject setDate:dateFuture];
    NSDate *dateTomorrow = [refObject date];
    NSTimeInterval futureInterval = [dateFuture timeIntervalSinceReferenceDate];
    NSTimeInterval tomorrowInterval = [dateTomorrow timeIntervalSinceReferenceDate];
    NSTimeInterval interval = fabs(futureInterval - tomorrowInterval);
    STAssertTrue(interval < 0.1, DBULessThanTestFailed);
    
    if (_verbose) {
        NSLog(@"Now : %@", dateNow);
        NSLog(@"Future : %@", dateFuture);
        NSLog(@"Tomorrow : %@", dateTomorrow);
    }
    
    //
    // decimal number property
    //
    NSDecimalNumber *decimalNumber = [refObject decimalNumber];
    STAssertTrue(decimalNumber.doubleValue > 0.1, DBUGreaterThanTestFailed);
    
    // setter
    NSDecimalNumber *newDecimalNumber = [NSDecimalNumber decimalNumberWithString:@"500.5005"];
    [refObject setDecimalNumber:newDecimalNumber];
    STAssertTrue([[refObject decimalNumber] isEqualTo:newDecimalNumber], DBUEqualityTestFailed);
    
    if (_verbose) {
        NSLog(@"Decimal number : %@", decimalNumber);
        NSLog(@"New decimal number : %@", [refObject decimalNumber]);
    }
    
    //
    // enumeration properties
    //
    eDBUIntEnum intEnumeration = [refObject intEnumeration];
    STAssertTrue(intEnumeration == [DBUIntEnum val1], DBUEqualityTestFailed);
    
    int64_t longEnumeration = [refObject longEnumeration];
    STAssertTrue(longEnumeration == eDBULongEnum_Val1, DBUEqualityTestFailed);
    
    // setter
    [refObject setIntEnumeration:[DBUIntEnum val4]];
    STAssertTrue([refObject intEnumeration] == [DBUIntEnum val4], DBUEqualityTestFailed);
    
    // we can set it out of range too - so be careful!
    [refObject setIntEnumeration:[DBUIntEnum val4] * 10];
    STAssertTrue([refObject intEnumeration] == [DBUIntEnum val4] * 10, DBUEqualityTestFailed);
    
    [refObject setLongEnumeration:eDBULongEnum_Val4];
    STAssertTrue([refObject longEnumeration] == eDBULongEnum_Val4, DBUEqualityTestFailed);

}

- (void)doTestReferenceClass:(Class)testClass
{
    
    //===================================
    // constructors
    //===================================
    id refObject = [self doTestConstructorsWithclass:testClass];
    
    [self doTestGenericConstructors:testClass];

    //===================================
    // events
    //===================================
    
    // the fact that the manually generated object does not have a class
    // name that matches the managed object class causes the event tests to fail.
    // hence we call them on the auto generated code only
    if (m_runningAutoGenCodeTest) {
        [self doTestEvents:refObject class:testClass];
    }
    
    //===================================
    // equality
    //===================================
    [self doTestForEquality:refObject class:testClass];

    //===================================
    // fields
    //===================================
    [self doTestFields:refObject class:testClass];

    //===================================
    // methods
    //===================================
    [self doTestMethods:refObject class:testClass];
    [self doTestExtensionMethods:refObject class:testClass];
    [self doTestArrayMethods:refObject class:testClass];
    [self doTestPointerMethods:refObject class:testClass];
    [self doTestRefMethods:refObject class:testClass];
    [self doTestGenericMethods:refObject class:testClass];

    //===================================
    // properties
    //===================================
    [self doTestProperties:refObject class:testClass];
    [self doTestArrayProperties:refObject class:testClass];
    [self doTestGenericProperties:refObject class:testClass];
    [self doTestPointerProperties:refObject class:testClass];
    [self doTestPropertyPersistence:refObject class:testClass];
    [self doTestNotifyingProperties:refObject class:testClass];

    //===================================
    // representations
    //===================================
    [self doTestStructRepresentation:refObject class:testClass];
    [self doTestInterfaceRepresentation:refObject class:testClass];
    [self doTestArrayListRepresentation:refObject class:testClass];
}

// managed event callbacks that route events back to registered event target
static void DubrovnikEventHandlerICall1(MonoObject* monoSender, MonoObject* monoEventArgs)
{
    
    [DBManagedEvent dispatchEventFromMonoSender:monoSender
                                      eventArgs:monoEventArgs
                                      eventName:@"UnitTestEvent1"
                             targetSelectorName:@"event1ReceivedFromSender:item:"];
}

- (void)event1ReceivedFromSender:(DBManagedObject *)sender item:(System_EventArgs *)item
{
#pragma unused(sender, item)
    self.event1Fired++;
}

static void DubrovnikEventHandlerICall2(MonoObject* monoSender, MonoObject* monoEventArgs)
{
    [DBManagedEvent dispatchEventFromMonoSender:monoSender
                                      eventArgs:monoEventArgs
                                      eventName:@"UnitTestEvent2"
                             targetSelectorName:@"event2ReceivedFromSender:item:"];
}

- (void)event2ReceivedFromSender:(id)sender item:(System_EventArgs *)item
{
#pragma unused(sender, item)
    self.event2Fired++;
}

#define REST_EVENT_VARS(X)    self.event1Fired = X; \
self.event2Fired = X; \
testObject.event1Fired = X; \
testObject.event2Fired = X; \
eventTarget.event1Fired = X; \
eventTarget.event2Fired = X; \
eventTarget1.event1Fired = X; \
eventTarget1.event2Fired = X

- (void)doTestEvents:(id)refObject class:(Class)testClass
{
#pragma unused(testClass)
    
    NSPointerArray * targets = nil;
    
    //=============================================
    // managed event API
    //
    // this API allows managed events to be fully
    // configured from unmanaged code.
    //=============================================
    
    // register unmanaged handlers for the managed events.
    // this associates a static managed event handler function with a static unmanaged handler function
    static BOOL m_eventHandlersRegistered = NO;
    if (!m_eventHandlersRegistered) {
        [DBManagedEvent registerManagedEventHandler:@"DubrovnikEventHandlerICall1" unmanagedHandler:&DubrovnikEventHandlerICall1];
        [DBManagedEvent registerManagedEventHandler:@"DubrovnikEventHandlerICall2" unmanagedHandler:&DubrovnikEventHandlerICall2];
        
        m_eventHandlersRegistered = YES;
    }
    

    //
    // add managed event handlers
    // this associates a managed event with a particular static managed event handler as registered above.
    // when the event fires it calls the managed function which is implemented by the unmanaged handler function.
    // the DBManagedEvent event dispatcher then dispatches a selector back to self et voila.
    //
    [self addManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent1" handlerMethodName:@"DubrovnikEventHandlerICall1"];
    [self addManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent2" handlerMethodName:@"DubrovnikEventHandlerICall2"];

    // check that targets have been set
    targets = [DBManagedEvent eventTargetsForSender:refObject eventName:@"UnitTestEvent1"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue([targets db_indexForObjectPointer:self] != NSUIntegerMax, DBUEqualityTestFailed);
    
    targets = [DBManagedEvent eventTargetsForSender:refObject eventName:@"UnitTestEvent2"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue([targets db_indexForObjectPointer:self] != NSUIntegerMax, DBUEqualityTestFailed);

    //
    // define another object of the same class to check that we can have multiple event subscribers
    // with the same class
    //
    Dubrovnik_Unit_Tests * testObject = [[self class] new];
    [testObject addManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent1" handlerMethodName:@"DubrovnikEventHandlerICall1"];
    [testObject addManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent2" handlerMethodName:@"DubrovnikEventHandlerICall2"];

    // check that targets have been set
    targets = [DBManagedEvent eventTargetsForSender:refObject eventName:@"UnitTestEvent1"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue([targets db_indexForObjectPointer:testObject] != NSUIntegerMax, DBUEqualityTestFailed);
    
    targets = [DBManagedEvent eventTargetsForSender:refObject eventName:@"UnitTestEvent2"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue([targets db_indexForObjectPointer:testObject] != NSUIntegerMax, DBUEqualityTestFailed);

    //
    // define an event target of another class
    //
    EventTarget *eventTarget = [EventTarget new];
    [eventTarget addManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent1" handlerMethodName:@"DubrovnikEventHandlerICall1"];
    [eventTarget addManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent2" handlerMethodName:@"DubrovnikEventHandlerICall2"];
    
    // check that targets have been set
    targets = [DBManagedEvent eventTargetsForSender:refObject eventName:@"UnitTestEvent1"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue([targets db_indexForObjectPointer:eventTarget] != NSUIntegerMax, DBUEqualityTestFailed);
    
    targets = [DBManagedEvent eventTargetsForSender:refObject eventName:@"UnitTestEvent2"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue([targets db_indexForObjectPointer:eventTarget] != NSUIntegerMax, DBUEqualityTestFailed);

    //
    // define another event source of this class
    //
    id refObject1 = [testClass new];
    [refObject1 setStringProperty:[[NSDate date] description]];
    EventTarget *eventTarget1 = [EventTarget new];
    [eventTarget1 addManagedEventHandlerForObject:refObject1 eventName:@"UnitTestEvent1" handlerMethodName:@"DubrovnikEventHandlerICall1"];
    [eventTarget1 addManagedEventHandlerForObject:refObject1 eventName:@"UnitTestEvent2" handlerMethodName:@"DubrovnikEventHandlerICall2"];
    
    // check that targets have been set
    targets = [DBManagedEvent eventTargetsForSender:refObject1 eventName:@"UnitTestEvent1"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue([targets db_indexForObjectPointer:eventTarget1] != NSUIntegerMax, DBUEqualityTestFailed);
    
    targets = [DBManagedEvent eventTargetsForSender:refObject1 eventName:@"UnitTestEvent2"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue([targets db_indexForObjectPointer:eventTarget1] != NSUIntegerMax, DBUEqualityTestFailed);

    // raise events
    REST_EVENT_VARS(0);
    
    [refObject raiseUnitTestEvent1];
    [refObject1 raiseUnitTestEvent1];
    STAssertTrue(self.event1Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(self.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event1Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(testObject.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event1Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(eventTarget1.event1Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget1.event2Fired == 0, DBUEqualityTestFailed);
    
    REST_EVENT_VARS(0);
    
    [refObject raiseUnitTestEvent2];
    [refObject1 raiseUnitTestEvent2];
    STAssertTrue(self.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(self.event2Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(testObject.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event2Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event2Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget1.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(eventTarget1.event2Fired == 1, DBUEqualityTestFailed);
    
    // remove handler 1 for self
    [self removeManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent1" handlerMethodName:@"DubrovnikEventHandlerICall1"];
    REST_EVENT_VARS(0);
    
    [refObject raiseUnitTestEvent1];
    [refObject raiseUnitTestEvent2];
    STAssertTrue(self.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(self.event2Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(testObject.event1Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(testObject.event2Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event1Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event2Fired == 1, DBUEqualityTestFailed);

    // remove handler 1 for testObject
    [testObject removeManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent1" handlerMethodName:@"DubrovnikEventHandlerICall1"];
    REST_EVENT_VARS(0);

    [refObject raiseUnitTestEvent1];
    [refObject raiseUnitTestEvent2];
    STAssertTrue(self.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(self.event2Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(testObject.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event2Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event1Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event2Fired == 1, DBUEqualityTestFailed);
    
    // remove handler 2 for self
    [self removeManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent2" handlerMethodName:@"DubrovnikEventHandlerICall2"];
    REST_EVENT_VARS(0);

    [refObject raiseUnitTestEvent1];
    [refObject raiseUnitTestEvent2];
    STAssertTrue(self.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(self.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event2Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event1Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event2Fired == 1, DBUEqualityTestFailed);
    
    // remove handler 2 for testObject
    [testObject removeManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent2" handlerMethodName:@"DubrovnikEventHandlerICall2"];
    REST_EVENT_VARS(0);
    
    [refObject raiseUnitTestEvent1];
    [refObject raiseUnitTestEvent2];
    STAssertTrue(self.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(self.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event1Fired == 1, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event2Fired == 1, DBUEqualityTestFailed);

    // remove handler 1 for eventTarget
    [eventTarget removeManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent1" handlerMethodName:@"DubrovnikEventHandlerICall1"];
    REST_EVENT_VARS(0);
    
    [refObject raiseUnitTestEvent1];
    [refObject raiseUnitTestEvent2];
    STAssertTrue(self.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(self.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event2Fired == 1, DBUEqualityTestFailed);
    
    // remove handler 2 for eventTarget
    [eventTarget removeManagedEventHandlerForObject:refObject eventName:@"UnitTestEvent2" handlerMethodName:@"DubrovnikEventHandlerICall2"];
    REST_EVENT_VARS(0);
    
    [refObject raiseUnitTestEvent1];
    [refObject raiseUnitTestEvent2];
    STAssertTrue(self.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(self.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(testObject.event2Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event1Fired == 0, DBUEqualityTestFailed);
    STAssertTrue(eventTarget.event2Fired == 0, DBUEqualityTestFailed);

    // check that targets have been set to zero
    targets = [DBManagedEvent eventTargetsForSender:refObject eventName:@"UnitTestEvent1"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue(targets.count == 0, DBUEqualityTestFailed);
    
    [DBManagedEvent eventTargetsForSender:refObject eventName:@"UnitTestEvent2"];
    STAssertNotNil(targets, DBUNotNilTestFailed);
    STAssertTrue(targets.count == 0, DBUEqualityTestFailed);
}

#pragma mark -
#pragma mark DBManagedEnvironmentDelegate methods

- (NSString *)managedEnvironment:(DBManagedEnvironment *)monoEnv pathToAssemblyName:(const char *)name
{
#pragma unused(monoEnv)
#pragma unused(name)
    NSString *path = nil;

    // Provide a path to the named assembly dll.
    // If nil is returned then the environment will attempt to load the assembly from the default mono version on the assembly root path.
    
    return path;
}

@end

@implementation EventTarget

- (void)event1ReceivedFromSender:(DBManagedObject *)sender item:(System_EventArgs *)item
{
#pragma unused(sender, item)
    
    self.event1Fired++;
}

- (void)event2ReceivedFromSender:(DBManagedObject *)sender item:(System_EventArgs *)item
{
#pragma unused(sender, item)
    self.event2Fired++;
}

@end
