//------------------------------------------------------------------------------
// <auto-generated tool="Dubrovnik.CodeGenerator">
//
// System_XML.m
//
// Dubrovnik based OS X Cocoa Objective-C to Mono bindings.
//
// This code was generated using a tool available as part of:
// http://github.com/ThesaurusSoftware/Dubrovnik
// This code has dependencies on the above project.
//
// Date:     20/09/2017 11:11:28
//
// Assembly: System.XML
// Fullname: System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Path:     C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.XML.dll
//
// Platform: Microsoft Windows NT 6.2.9200.0
// OS Arch:  64 bit
// Process:  32 bit
// Target:   mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Runtime:  4.0.30319.42000
//
// Asm Ref:  mscorlib
// Fullname: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Asm Ref:  System
// Fullname: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Asm Ref:  System.Data.SqlXml
// Fullname: System.Data.SqlXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//
// Asm Ref:  System.Configuration
// Fullname: System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
#import "System_XML.h"

// ARC is required
#if  ! __has_feature(objc_arc)
#error This file requires ARC. 
#endif


/*

Order here is Enumerations, Interface protocols, Structs, Classes, Explicit interface classes

*/

// Dubrovnik.CodeGenerator made System_Xml_ConformanceLevel.m
// Dubrovnik.CodeGenerator made System_Xml_DtdProcessing.m
// Dubrovnik.CodeGenerator made System_Xml_EntityHandling.m
// Dubrovnik.CodeGenerator made System_Xml_Formatting.m
// Dubrovnik.CodeGenerator made System_Xml_NamespaceHandling.m
// Dubrovnik.CodeGenerator made System_Xml_NewLineHandling.m
// Dubrovnik.CodeGenerator made System_Xml_ReadState.m
// Dubrovnik.CodeGenerator made System_Xml_ValidationType.m
// Dubrovnik.CodeGenerator made System_Xml_WhitespaceHandling.m
// Dubrovnik.CodeGenerator made System_Xml_WriteState.m
// Dubrovnik.CodeGenerator made System_Xml_XmlDateTimeSerializationMode.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNamespaceScope.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNodeChangedAction.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNodeOrder.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNodeType.m
// Dubrovnik.CodeGenerator made System_Xml_XmlOutputMethod.m
// Dubrovnik.CodeGenerator made System_Xml_XmlSpace.m
// Dubrovnik.CodeGenerator made System_Xml_XmlTokenizedType.m
// Dubrovnik.CodeGenerator made System_Xml_Resolvers_XmlKnownDtds.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaContentProcessing.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaContentType.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaDatatypeVariety.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaDerivationMethod.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaForm.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaInference__InferenceOption.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaUse.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaValidationFlags.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaValidity.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSeverityType.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlTypeCode.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_CodeGenerationOptions.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlMappingAccess.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Configuration_DateTimeSerializationSection__DateTimeSerializationMode.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XmlCaseOrder.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XmlDataType.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XmlSortOrder.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XPathNamespaceScope.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XPathNodeType.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XPathResultType.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlDeserializationEvents.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNameTable.m
// Dubrovnik.CodeGenerator made System_Xml_NameTable.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNode.m
// Dubrovnik.CodeGenerator made System_Xml_XmlAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNamedNodeMap.m
// Dubrovnik.CodeGenerator made System_Xml_XmlAttributeCollection.m
// Dubrovnik.CodeGenerator made System_Xml_XmlLinkedNode.m
// Dubrovnik.CodeGenerator made System_Xml_XmlCharacterData.m
// Dubrovnik.CodeGenerator made System_Xml_XmlCDataSection.m
// Dubrovnik.CodeGenerator made System_Xml_XmlComment.m
// Dubrovnik.CodeGenerator made System_Xml_XmlConvert.m
// Dubrovnik.CodeGenerator made System_Xml_XmlDeclaration.m
// Dubrovnik.CodeGenerator made System_Xml_XmlDocument.m
// Dubrovnik.CodeGenerator made System_Xml_XmlDocumentFragment.m
// Dubrovnik.CodeGenerator made System_Xml_XmlDocumentType.m
// Dubrovnik.CodeGenerator made System_Xml_XmlElement.m
// Dubrovnik.CodeGenerator made System_Xml_XmlEntity.m
// Dubrovnik.CodeGenerator made System_Xml_XmlEntityReference.m
// Dubrovnik.CodeGenerator made System_Xml_XmlException.m
// Dubrovnik.CodeGenerator made System_Xml_XmlImplementation.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNamespaceManager.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNodeChangedEventArgs.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNodeChangedEventHandler.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNodeList.m
// Dubrovnik.CodeGenerator made System_Xml_XmlReader.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNodeReader.m
// Dubrovnik.CodeGenerator made System_Xml_XmlNotation.m
// Dubrovnik.CodeGenerator made System_Xml_XmlParserContext.m
// Dubrovnik.CodeGenerator made System_Xml_XmlProcessingInstruction.m
// Dubrovnik.CodeGenerator made System_Xml_XmlQualifiedName.m
// Dubrovnik.CodeGenerator made System_Xml_XmlReaderSettings.m
// Dubrovnik.CodeGenerator made System_Xml_XmlResolver.m
// Dubrovnik.CodeGenerator made System_Xml_XmlSecureResolver.m
// Dubrovnik.CodeGenerator made System_Xml_XmlSignificantWhitespace.m
// Dubrovnik.CodeGenerator made System_Xml_XmlText.m
// Dubrovnik.CodeGenerator made System_Xml_XmlTextReader.m
// Dubrovnik.CodeGenerator made System_Xml_XmlWriter.m
// Dubrovnik.CodeGenerator made System_Xml_XmlTextWriter.m
// Dubrovnik.CodeGenerator made System_Xml_XmlUrlResolver.m
// Dubrovnik.CodeGenerator made System_Xml_XmlValidatingReader.m
// Dubrovnik.CodeGenerator made System_Xml_XmlWhitespace.m
// Dubrovnik.CodeGenerator made System_Xml_XmlWriterSettings.m
// Dubrovnik.CodeGenerator made System_Xml_XmlXapResolver.m
// Dubrovnik.CodeGenerator made System_Xml_Resolvers_XmlPreloadedResolver.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_ValidationEventArgs.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_ValidationEventHandler.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XPathItem.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlAtomicValue.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaObject.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchema.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaAnnotated.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaParticle.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaGroupBase.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaAll.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaAnnotation.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaAny.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaAnyAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaAppInfo.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaAttributeGroup.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaAttributeGroupRef.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaChoice.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaCollection.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaCollectionEnumerator.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaCompilationSettings.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaContentModel.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaComplexContent.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaContent.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaComplexContentExtension.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaComplexContentRestriction.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaType.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaComplexType.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaDatatype.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaDocumentation.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaElement.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaEnumerationFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaException.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaExternal.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaNumericFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaFractionDigitsFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaGroup.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaGroupRef.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaIdentityConstraint.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaImport.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaInclude.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaInference.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaInferenceException.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaInfo.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaKey.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaKeyref.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaLengthFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaMaxExclusiveFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaMaxInclusiveFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaMaxLengthFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaMinExclusiveFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaMinInclusiveFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaMinLengthFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaNotation.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaObjectCollection.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaObjectEnumerator.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaObjectTable.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaPatternFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaRedefine.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSequence.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSimpleContent.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSimpleContentExtension.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSimpleContentRestriction.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSimpleType.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSimpleTypeContent.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSimpleTypeList.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSimpleTypeRestriction.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaSimpleTypeUnion.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaTotalDigitsFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaUnique.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaValidationException.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaValidator.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaWhiteSpaceFacet.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlSchemaXPath.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_XmlValueGetter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_CodeExporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_CodeIdentifier.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_CodeIdentifiers.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_ImportContext.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SchemaImporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapAttributeAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapAttributeOverrides.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapAttributes.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapCodeExporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapElementAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapEnumAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapIgnoreAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapIncludeAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapReflectionImporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapSchemaExporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapSchemaImporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapSchemaMember.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_SoapTypeAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_UnreferencedObjectEventArgs.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_UnreferencedObjectEventHandler.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlAnyAttributeAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlAnyElementAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlAnyElementAttributes.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlArrayAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlArrayItemAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlArrayItemAttributes.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlAttributeAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlAttributeEventArgs.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlAttributeEventHandler.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlAttributeOverrides.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlAttributes.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlChoiceIdentifierAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlCodeExporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlElementAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlElementAttributes.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlElementEventArgs.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlElementEventHandler.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlEnumAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlIgnoreAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlIncludeAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlMapping.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlMemberMapping.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlMembersMapping.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlNamespaceDeclarationsAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlNodeEventArgs.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlNodeEventHandler.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlReflectionImporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlReflectionMember.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlRootAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSchemaEnumerator.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSchemaExporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSchemaImporter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSchemaProviderAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSchemas.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializationCollectionFixupCallback.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializationFixupCallback.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializationGeneratedCode.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializationReadCallback.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializationReader.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializationWriteCallback.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializationWriter.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializer.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializerAssemblyAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializerFactory.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializerImplementation.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializerNamespaces.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlSerializerVersionAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlTextAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlTypeAttribute.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_XmlTypeMapping.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Advanced_SchemaImporterExtension.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Advanced_SchemaImporterExtensionCollection.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Configuration_DateTimeSerializationSection.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Configuration_RootedPathValidator.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Configuration_SchemaImporterExtensionElement.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Configuration_SchemaImporterExtensionElementCollection.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Configuration_SchemaImporterExtensionsSection.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Configuration_SerializationSectionGroup.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_Configuration_XmlSerializerSection.m
// Dubrovnik.CodeGenerator made System_Xml_XmlConfiguration_XmlReaderSection.m
// Dubrovnik.CodeGenerator made System_Xml_XmlConfiguration_XsltConfigSection.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XPathDocument.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XPathException.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XPathExpression.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XPathNavigator.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_XPathNodeIterator.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_XslCompiledTransform.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_XsltArgumentList.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_XsltException.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_XsltCompileException.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_XsltContext.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_XsltMessageEncounteredEventArgs.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_XsltMessageEncounteredEventHandler.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_XslTransform.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_XsltSettings.m
// Dubrovnik.CodeGenerator made System_Xml_IApplicationResourceStreamResolver.m
// Dubrovnik.CodeGenerator made System_Xml_IHasXmlNode.m
// Dubrovnik.CodeGenerator made System_Xml_IXmlLineInfo.m
// Dubrovnik.CodeGenerator made System_Xml_IXmlNamespaceResolver.m
// Dubrovnik.CodeGenerator made System_Xml_Schema_IXmlSchemaInfo.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_IXmlSerializable.m
// Dubrovnik.CodeGenerator made System_Xml_Serialization_IXmlTextParser.m
// Dubrovnik.CodeGenerator made System_Xml_XPath_IXPathNavigable.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_IXsltContextFunction.m
// Dubrovnik.CodeGenerator made System_Xml_Xsl_IXsltContextVariable.m
