//++Dubrovnik.CodeGenerator System_Security_Permissions_HostProtectionResource.h
//
// Managed enumeration : HostProtectionResource
//
typedef NS_ENUM(int32_t, System_Security_Permissions_HostProtectionResource) {
	System_Security_Permissions_HostProtectionResource_All = 511,
	System_Security_Permissions_HostProtectionResource_ExternalProcessMgmt = 4,
	System_Security_Permissions_HostProtectionResource_ExternalThreading = 16,
	System_Security_Permissions_HostProtectionResource_MayLeakOnAbort = 256,
	System_Security_Permissions_HostProtectionResource_None = 0,
	System_Security_Permissions_HostProtectionResource_SecurityInfrastructure = 64,
	System_Security_Permissions_HostProtectionResource_SelfAffectingProcessMgmt = 8,
	System_Security_Permissions_HostProtectionResource_SelfAffectingThreading = 32,
	System_Security_Permissions_HostProtectionResource_SharedState = 2,
	System_Security_Permissions_HostProtectionResource_Synchronization = 1,
	System_Security_Permissions_HostProtectionResource_UI = 128,
};
//--Dubrovnik.CodeGenerator