//++Dubrovnik.CodeGenerator System_Runtime_InteropServices_VarEnum.h
//
// Managed enumeration : VarEnum
//
typedef NS_ENUM(int32_t, System_Runtime_InteropServices_VarEnum) {
	System_Runtime_InteropServices_VarEnum_VT_ARRAY = 8192,
	System_Runtime_InteropServices_VarEnum_VT_BLOB = 65,
	System_Runtime_InteropServices_VarEnum_VT_BLOB_OBJECT = 70,
	System_Runtime_InteropServices_VarEnum_VT_BOOL = 11,
	System_Runtime_InteropServices_VarEnum_VT_BSTR = 8,
	System_Runtime_InteropServices_VarEnum_VT_BYREF = 16384,
	System_Runtime_InteropServices_VarEnum_VT_CARRAY = 28,
	System_Runtime_InteropServices_VarEnum_VT_CF = 71,
	System_Runtime_InteropServices_VarEnum_VT_CLSID = 72,
	System_Runtime_InteropServices_VarEnum_VT_CY = 6,
	System_Runtime_InteropServices_VarEnum_VT_DATE = 7,
	System_Runtime_InteropServices_VarEnum_VT_DECIMAL = 14,
	System_Runtime_InteropServices_VarEnum_VT_DISPATCH = 9,
	System_Runtime_InteropServices_VarEnum_VT_EMPTY = 0,
	System_Runtime_InteropServices_VarEnum_VT_ERROR = 10,
	System_Runtime_InteropServices_VarEnum_VT_FILETIME = 64,
	System_Runtime_InteropServices_VarEnum_VT_HRESULT = 25,
	System_Runtime_InteropServices_VarEnum_VT_I1 = 16,
	System_Runtime_InteropServices_VarEnum_VT_I2 = 2,
	System_Runtime_InteropServices_VarEnum_VT_I4 = 3,
	System_Runtime_InteropServices_VarEnum_VT_I8 = 20,
	System_Runtime_InteropServices_VarEnum_VT_INT = 22,
	System_Runtime_InteropServices_VarEnum_VT_LPSTR = 30,
	System_Runtime_InteropServices_VarEnum_VT_LPWSTR = 31,
	System_Runtime_InteropServices_VarEnum_VT_NULL = 1,
	System_Runtime_InteropServices_VarEnum_VT_PTR = 26,
	System_Runtime_InteropServices_VarEnum_VT_R4 = 4,
	System_Runtime_InteropServices_VarEnum_VT_R8 = 5,
	System_Runtime_InteropServices_VarEnum_VT_RECORD = 36,
	System_Runtime_InteropServices_VarEnum_VT_SAFEARRAY = 27,
	System_Runtime_InteropServices_VarEnum_VT_STORAGE = 67,
	System_Runtime_InteropServices_VarEnum_VT_STORED_OBJECT = 69,
	System_Runtime_InteropServices_VarEnum_VT_STREAM = 66,
	System_Runtime_InteropServices_VarEnum_VT_STREAMED_OBJECT = 68,
	System_Runtime_InteropServices_VarEnum_VT_UI1 = 17,
	System_Runtime_InteropServices_VarEnum_VT_UI2 = 18,
	System_Runtime_InteropServices_VarEnum_VT_UI4 = 19,
	System_Runtime_InteropServices_VarEnum_VT_UI8 = 21,
	System_Runtime_InteropServices_VarEnum_VT_UINT = 23,
	System_Runtime_InteropServices_VarEnum_VT_UNKNOWN = 13,
	System_Runtime_InteropServices_VarEnum_VT_USERDEFINED = 29,
	System_Runtime_InteropServices_VarEnum_VT_VARIANT = 12,
	System_Runtime_InteropServices_VarEnum_VT_VECTOR = 4096,
	System_Runtime_InteropServices_VarEnum_VT_VOID = 24,
};
//--Dubrovnik.CodeGenerator