//++Dubrovnik.CodeGenerator System_Threading_Tasks_TaskContinuationOptions.h
//
// Managed enumeration : TaskContinuationOptions
//
typedef NS_ENUM(int32_t, System_Threading_Tasks_TaskContinuationOptions) {
	System_Threading_Tasks_TaskContinuationOptions_AttachedToParent = 4,
	System_Threading_Tasks_TaskContinuationOptions_DenyChildAttach = 8,
	System_Threading_Tasks_TaskContinuationOptions_ExecuteSynchronously = 524288,
	System_Threading_Tasks_TaskContinuationOptions_HideScheduler = 16,
	System_Threading_Tasks_TaskContinuationOptions_LazyCancellation = 32,
	System_Threading_Tasks_TaskContinuationOptions_LongRunning = 2,
	System_Threading_Tasks_TaskContinuationOptions_None = 0,
	System_Threading_Tasks_TaskContinuationOptions_NotOnCanceled = 262144,
	System_Threading_Tasks_TaskContinuationOptions_NotOnFaulted = 131072,
	System_Threading_Tasks_TaskContinuationOptions_NotOnRanToCompletion = 65536,
	System_Threading_Tasks_TaskContinuationOptions_OnlyOnCanceled = 196608,
	System_Threading_Tasks_TaskContinuationOptions_OnlyOnFaulted = 327680,
	System_Threading_Tasks_TaskContinuationOptions_OnlyOnRanToCompletion = 393216,
	System_Threading_Tasks_TaskContinuationOptions_PreferFairness = 1,
};
//--Dubrovnik.CodeGenerator